-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    OutPadConv2_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    OutPadConv2_V_ce0 : OUT STD_LOGIC;
    OutPadConv2_V_we0 : OUT STD_LOGIC;
    OutPadConv2_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    average_pooling1d_1_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    average_pooling1d_1_V_ce0 : OUT STD_LOGIC;
    average_pooling1d_1_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of CNN_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_780 : STD_LOGIC_VECTOR (10 downto 0) := "11110000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv7_7C : STD_LOGIC_VECTOR (6 downto 0) := "1111100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln105_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln108_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_reg_305 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln108_1_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln108_1_reg_310 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln108_fu_216_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln108_reg_315 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln108_2_fu_238_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln108_1_fu_268_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_fu_58 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln107_fu_243_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n_load : STD_LOGIC_VECTOR (5 downto 0);
    signal c_fu_62 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln105_1_fu_152_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten172_fu_66 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln105_fu_120_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten172_load : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln107_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln105_1_fu_146_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln105_fu_138_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_184_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl33_mid2_fu_168_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal n_5_cast61_fu_176_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln108_1_fu_206_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln108_fu_212_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_mid8_fu_160_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal n_5_cast_fu_180_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln108_3_fu_222_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln108_fu_228_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln108_2_fu_232_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln108_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    c_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_62 <= select_ln105_1_fu_152_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_62 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten172_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten172_fu_66 <= add_ln105_fu_120_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten172_fu_66 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    n_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln105_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_fu_58 <= add_ln107_fu_243_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_58 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln105_fu_114_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln108_reg_315 <= add_ln108_fu_216_p2;
                icmp_ln108_1_reg_310 <= icmp_ln108_1_fu_200_p2;
                icmp_ln108_reg_305 <= icmp_ln108_fu_194_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    OutPadConv2_V_address0 <= zext_ln108_1_fu_268_p1(11 - 1 downto 0);

    OutPadConv2_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            OutPadConv2_V_ce0 <= ap_const_logic_1;
        else 
            OutPadConv2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    OutPadConv2_V_d0 <= 
        ap_const_lv32_0 when (or_ln108_fu_264_p2(0) = '1') else 
        average_pooling1d_1_V_q0;

    OutPadConv2_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            OutPadConv2_V_we0 <= ap_const_logic_1;
        else 
            OutPadConv2_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln105_1_fu_146_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv6_1));
    add_ln105_fu_120_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten172_load) + unsigned(ap_const_lv11_1));
    add_ln107_fu_243_p2 <= std_logic_vector(unsigned(select_ln105_fu_138_p3) + unsigned(ap_const_lv6_1));
    add_ln108_1_fu_206_p2 <= std_logic_vector(unsigned(p_shl33_mid2_fu_168_p3) + unsigned(n_5_cast61_fu_176_p1));
    add_ln108_2_fu_232_p2 <= std_logic_vector(signed(sext_ln108_fu_228_p1) + signed(p_mid8_fu_160_p3));
    add_ln108_3_fu_222_p2 <= std_logic_vector(unsigned(n_5_cast_fu_180_p1) + unsigned(ap_const_lv7_7C));
    add_ln108_fu_216_p2 <= std_logic_vector(unsigned(zext_ln108_fu_212_p1) + unsigned(p_mid8_fu_160_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln105_fu_114_p2)
    begin
        if (((icmp_ln105_fu_114_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_62)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_62;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten172_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten172_fu_66)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten172_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten172_load <= indvar_flatten172_fu_66;
        end if; 
    end process;


    ap_sig_allocacmp_n_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, n_fu_58, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_n_load <= n_fu_58;
        end if; 
    end process;

    average_pooling1d_1_V_address0 <= zext_ln108_2_fu_238_p1(11 - 1 downto 0);

    average_pooling1d_1_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            average_pooling1d_1_V_ce0 <= ap_const_logic_1;
        else 
            average_pooling1d_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln105_fu_114_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten172_load = ap_const_lv11_780) else "0";
    icmp_ln107_fu_132_p2 <= "1" when (ap_sig_allocacmp_n_load = ap_const_lv6_28) else "0";
    icmp_ln108_1_fu_200_p2 <= "1" when (unsigned(select_ln105_fu_138_p3) > unsigned(ap_const_lv6_23)) else "0";
    icmp_ln108_fu_194_p2 <= "1" when (tmp_fu_184_p4 = ap_const_lv4_0) else "0";
    n_5_cast61_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln105_fu_138_p3),9));
    n_5_cast_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln105_fu_138_p3),7));
    or_ln108_fu_264_p2 <= (icmp_ln108_reg_305 or icmp_ln108_1_reg_310);
    p_mid8_fu_160_p3 <= (select_ln105_1_fu_152_p3 & ap_const_lv5_0);
    p_shl33_mid2_fu_168_p3 <= (select_ln105_1_fu_152_p3 & ap_const_lv3_0);
    select_ln105_1_fu_152_p3 <= 
        add_ln105_1_fu_146_p2 when (icmp_ln107_fu_132_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln105_fu_138_p3 <= 
        ap_const_lv6_0 when (icmp_ln107_fu_132_p2(0) = '1') else 
        ap_sig_allocacmp_n_load;
        sext_ln108_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln108_3_fu_222_p2),11));

    tmp_fu_184_p4 <= select_ln105_fu_138_p3(5 downto 2);
    zext_ln108_1_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln108_reg_315),64));
    zext_ln108_2_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln108_2_fu_232_p2),64));
    zext_ln108_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln108_1_fu_206_p2),11));
end behav;
