-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_loop_for_3_channel_pad_1_loop_for_channel_pad_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    OutPadConv1_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    OutPadConv1_V_ce0 : OUT STD_LOGIC;
    OutPadConv1_V_we0 : OUT STD_LOGIC;
    OutPadConv1_V_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    average_pooling1d_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    average_pooling1d_V_ce0 : OUT STD_LOGIC;
    average_pooling1d_V_q0 : IN STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of CNN_CNN_Pipeline_loop_for_3_channel_pad_1_loop_for_channel_pad_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_900 : STD_LOGIC_VECTOR (11 downto 0) := "100100000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv7_48 : STD_LOGIC_VECTOR (6 downto 0) := "1001000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv7_43 : STD_LOGIC_VECTOR (6 downto 0) := "1000011";
    constant ap_const_lv8_FC : STD_LOGIC_VECTOR (7 downto 0) := "11111100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln57_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln60_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_321 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln60_1_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_1_reg_326 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln60_fu_232_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln60_reg_331 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln60_2_fu_254_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln60_1_fu_284_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_fu_62 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln59_fu_259_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n_load : STD_LOGIC_VECTOR (6 downto 0);
    signal c_fu_66 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln57_1_fu_156_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten102_fu_70 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln57_fu_124_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten102_load : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln59_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln57_1_fu_150_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln57_fu_164_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_mid4_fu_168_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln59_mid2_v_fu_180_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln57_fu_142_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_200_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln57_1_fu_188_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal n_3_cast49_fu_192_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln60_1_fu_222_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln60_fu_228_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln57_fu_176_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal n_3_cast_fu_196_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln60_3_fu_238_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln60_fu_244_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln60_2_fu_248_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln60_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    c_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln57_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_66 <= select_ln57_1_fu_156_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_66 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten102_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln57_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten102_fu_70 <= add_ln57_fu_124_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten102_fu_70 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    n_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln57_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_fu_62 <= add_ln59_fu_259_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_62 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln57_fu_118_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln60_reg_331 <= add_ln60_fu_232_p2;
                icmp_ln60_1_reg_326 <= icmp_ln60_1_fu_216_p2;
                icmp_ln60_reg_321 <= icmp_ln60_fu_210_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    OutPadConv1_V_address0 <= zext_ln60_1_fu_284_p1(12 - 1 downto 0);

    OutPadConv1_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            OutPadConv1_V_ce0 <= ap_const_logic_1;
        else 
            OutPadConv1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    OutPadConv1_V_d0 <= 
        ap_const_lv31_0 when (or_ln60_fu_280_p2(0) = '1') else 
        average_pooling1d_V_q0;

    OutPadConv1_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            OutPadConv1_V_we0 <= ap_const_logic_1;
        else 
            OutPadConv1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln57_1_fu_150_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv6_1));
    add_ln57_fu_124_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten102_load) + unsigned(ap_const_lv12_1));
    add_ln59_fu_259_p2 <= std_logic_vector(unsigned(select_ln57_fu_142_p3) + unsigned(ap_const_lv7_1));
    add_ln60_1_fu_222_p2 <= std_logic_vector(unsigned(zext_ln57_1_fu_188_p1) + unsigned(n_3_cast49_fu_192_p1));
    add_ln60_2_fu_248_p2 <= std_logic_vector(signed(sext_ln60_fu_244_p1) + signed(p_mid4_fu_168_p3));
    add_ln60_3_fu_238_p2 <= std_logic_vector(unsigned(n_3_cast_fu_196_p1) + unsigned(ap_const_lv8_FC));
    add_ln60_fu_232_p2 <= std_logic_vector(unsigned(zext_ln60_fu_228_p1) + unsigned(zext_ln57_fu_176_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln57_fu_118_p2)
    begin
        if (((icmp_ln57_fu_118_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_66)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_66;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten102_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten102_fu_70)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten102_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten102_load <= indvar_flatten102_fu_70;
        end if; 
    end process;


    ap_sig_allocacmp_n_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, n_fu_62, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_n_load <= n_fu_62;
        end if; 
    end process;

    average_pooling1d_V_address0 <= zext_ln60_2_fu_254_p1(11 - 1 downto 0);

    average_pooling1d_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            average_pooling1d_V_ce0 <= ap_const_logic_1;
        else 
            average_pooling1d_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln57_fu_118_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten102_load = ap_const_lv12_900) else "0";
    icmp_ln59_fu_136_p2 <= "1" when (ap_sig_allocacmp_n_load = ap_const_lv7_48) else "0";
    icmp_ln60_1_fu_216_p2 <= "1" when (unsigned(select_ln57_fu_142_p3) > unsigned(ap_const_lv7_43)) else "0";
    icmp_ln60_fu_210_p2 <= "1" when (tmp_fu_200_p4 = ap_const_lv5_0) else "0";
    n_3_cast49_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln57_fu_142_p3),9));
    n_3_cast_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln57_fu_142_p3),8));
    or_ln60_fu_280_p2 <= (icmp_ln60_reg_321 or icmp_ln60_1_reg_326);
    p_mid4_fu_168_p3 <= (trunc_ln57_fu_164_p1 & ap_const_lv6_0);
    select_ln57_1_fu_156_p3 <= 
        add_ln57_1_fu_150_p2 when (icmp_ln59_fu_136_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln57_fu_142_p3 <= 
        ap_const_lv7_0 when (icmp_ln59_fu_136_p2(0) = '1') else 
        ap_sig_allocacmp_n_load;
        sext_ln60_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln60_3_fu_238_p2),11));

    tmp_fu_200_p4 <= select_ln57_fu_142_p3(6 downto 2);
    trunc_ln57_fu_164_p1 <= select_ln57_1_fu_156_p3(5 - 1 downto 0);
    zext_ln57_1_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln59_mid2_v_fu_180_p3),9));
    zext_ln57_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid4_fu_168_p3),12));
    zext_ln59_mid2_v_fu_180_p3 <= (trunc_ln57_fu_164_p1 & ap_const_lv3_0);
    zext_ln60_1_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_reg_331),64));
    zext_ln60_2_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_2_fu_248_p2),64));
    zext_ln60_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_1_fu_222_p2),12));
end behav;
