-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_VITIS_LOOP_75_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    straight_attention_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce0 : OUT STD_LOGIC;
    straight_attention_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce1 : OUT STD_LOGIC;
    straight_attention_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce2 : OUT STD_LOGIC;
    straight_attention_V_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address3 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce3 : OUT STD_LOGIC;
    straight_attention_V_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address4 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce4 : OUT STD_LOGIC;
    straight_attention_V_q4 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address5 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce5 : OUT STD_LOGIC;
    straight_attention_V_q5 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address6 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce6 : OUT STD_LOGIC;
    straight_attention_V_q6 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address7 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce7 : OUT STD_LOGIC;
    straight_attention_V_q7 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address8 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce8 : OUT STD_LOGIC;
    straight_attention_V_q8 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address9 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce9 : OUT STD_LOGIC;
    straight_attention_V_q9 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address10 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce10 : OUT STD_LOGIC;
    straight_attention_V_q10 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address11 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce11 : OUT STD_LOGIC;
    straight_attention_V_q11 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address12 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce12 : OUT STD_LOGIC;
    straight_attention_V_q12 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address13 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce13 : OUT STD_LOGIC;
    straight_attention_V_q13 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address14 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce14 : OUT STD_LOGIC;
    straight_attention_V_q14 : IN STD_LOGIC_VECTOR (31 downto 0);
    straight_attention_V_address15 : OUT STD_LOGIC_VECTOR (9 downto 0);
    straight_attention_V_ce15 : OUT STD_LOGIC;
    straight_attention_V_q15 : IN STD_LOGIC_VECTOR (31 downto 0);
    global_average_pooling1d_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    global_average_pooling1d_V_ce0 : OUT STD_LOGIC;
    global_average_pooling1d_V_we0 : OUT STD_LOGIC;
    global_average_pooling1d_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of CNN_CNN_Pipeline_VITIS_LOOP_75_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv10_4 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_const_lv10_5 : STD_LOGIC_VECTOR (9 downto 0) := "0000000101";
    constant ap_const_lv10_6 : STD_LOGIC_VECTOR (9 downto 0) := "0000000110";
    constant ap_const_lv10_7 : STD_LOGIC_VECTOR (9 downto 0) := "0000000111";
    constant ap_const_lv10_8 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_const_lv10_9 : STD_LOGIC_VECTOR (9 downto 0) := "0000001001";
    constant ap_const_lv10_A : STD_LOGIC_VECTOR (9 downto 0) := "0000001010";
    constant ap_const_lv10_B : STD_LOGIC_VECTOR (9 downto 0) := "0000001011";
    constant ap_const_lv10_C : STD_LOGIC_VECTOR (9 downto 0) := "0000001100";
    constant ap_const_lv10_D : STD_LOGIC_VECTOR (9 downto 0) := "0000001101";
    constant ap_const_lv10_E : STD_LOGIC_VECTOR (9 downto 0) := "0000001110";
    constant ap_const_lv10_F : STD_LOGIC_VECTOR (9 downto 0) := "0000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln75_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_reg_1600 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_reg_1600_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln813_30_fu_1583_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_30_reg_1689 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln78_fu_316_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln78_1_fu_327_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_2_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_3_fu_349_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_4_fu_360_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_5_fu_371_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_6_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_7_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_8_fu_404_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_9_fu_415_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_10_fu_426_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_11_fu_437_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_12_fu_448_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_13_fu_459_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_14_fu_470_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_15_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_9_cast116_fu_1589_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal hs_fu_74 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln75_3_fu_298_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_461_fu_304_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_308_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_fu_321_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_1_fu_332_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_2_fu_343_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_3_fu_354_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_4_fu_365_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_5_fu_376_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_6_fu_387_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_7_fu_398_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_8_fu_409_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_9_fu_420_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_10_fu_431_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_11_fu_442_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_12_fu_453_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_13_fu_464_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln78_14_fu_475_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln1303_fu_499_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_s_fu_505_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_fu_515_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_2_fu_525_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_fu_491_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_3_fu_519_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_3_fu_535_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_fu_539_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_4_fu_559_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_3_fu_565_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_4_fu_575_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_4_fu_585_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_61_fu_551_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_5_fu_579_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_5_fu_595_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_1_fu_599_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_6_fu_619_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_5_fu_625_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_6_fu_635_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_6_fu_645_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_62_fu_611_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_7_fu_639_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_7_fu_655_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_2_fu_659_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_8_fu_679_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_7_fu_685_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_8_fu_695_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_8_fu_705_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_63_fu_671_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_9_fu_699_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_9_fu_715_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_3_fu_719_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_10_fu_739_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_9_fu_745_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_10_fu_755_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_10_fu_765_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_64_fu_731_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_11_fu_759_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_11_fu_775_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_4_fu_779_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_12_fu_799_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_11_fu_805_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_12_fu_815_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_12_fu_825_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_65_fu_791_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_13_fu_819_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_13_fu_835_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_5_fu_839_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_14_fu_859_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_13_fu_865_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_14_fu_875_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_14_fu_885_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_66_fu_851_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_15_fu_879_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_15_fu_895_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_6_fu_899_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_16_fu_919_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_15_fu_925_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_16_fu_935_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_16_fu_945_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_67_fu_911_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_17_fu_939_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_17_fu_955_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_7_fu_959_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_18_fu_979_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_17_fu_985_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_18_fu_995_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_18_fu_1005_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_68_fu_971_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_19_fu_999_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_19_fu_1015_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_8_fu_1019_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_20_fu_1039_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_19_fu_1045_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_20_fu_1055_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_20_fu_1065_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_69_fu_1031_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_21_fu_1059_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_21_fu_1075_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_9_fu_1079_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_22_fu_1099_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_21_fu_1105_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_22_fu_1115_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_22_fu_1125_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_70_fu_1091_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_23_fu_1119_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_23_fu_1135_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_10_fu_1139_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_24_fu_1159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_23_fu_1165_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_24_fu_1175_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_24_fu_1185_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_71_fu_1151_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_25_fu_1179_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_25_fu_1195_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_11_fu_1199_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_26_fu_1219_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_25_fu_1225_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_26_fu_1235_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_26_fu_1245_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_72_fu_1211_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_27_fu_1239_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_27_fu_1255_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_12_fu_1259_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_28_fu_1279_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_27_fu_1285_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_28_fu_1295_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_28_fu_1305_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_73_fu_1271_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_29_fu_1299_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_29_fu_1315_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_13_fu_1319_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_30_fu_1339_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_29_fu_1345_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_30_fu_1355_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_30_fu_1365_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_74_fu_1331_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_31_fu_1359_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_31_fu_1375_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_14_fu_1379_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln1303_32_fu_1399_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_31_fu_1405_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln1303_32_fu_1415_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln1303_32_fu_1425_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_75_fu_1391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_33_fu_1419_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal zext_ln1303_33_fu_1435_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln1303_15_fu_1439_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln78_1_fu_607_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_fu_547_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_fu_1451_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_2_fu_667_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_3_fu_727_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_22_fu_1461_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_2_fu_1467_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_1_fu_1457_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln813_23_fu_1471_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln78_4_fu_787_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_5_fu_847_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_24_fu_1481_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_6_fu_907_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_7_fu_967_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_25_fu_1491_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_5_fu_1497_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_4_fu_1487_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln813_26_fu_1501_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_6_fu_1507_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln813_3_fu_1477_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln78_8_fu_1027_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_9_fu_1087_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_28_fu_1517_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_10_fu_1147_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_11_fu_1207_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_29_fu_1527_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_8_fu_1533_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_7_fu_1523_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln813_31_fu_1537_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln78_12_fu_1267_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_13_fu_1327_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_32_fu_1547_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln78_14_fu_1387_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_fu_1447_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_33_fu_1557_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_11_fu_1563_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_10_fu_1553_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln813_34_fu_1567_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_12_fu_1573_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln813_9_fu_1543_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_35_fu_1577_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_27_fu_1511_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    hs_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln75_fu_292_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    hs_fu_74 <= add_ln75_3_fu_298_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    hs_fu_74 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln813_30_reg_1689 <= add_ln813_30_fu_1583_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                i_reg_1600 <= ap_sig_allocacmp_i;
                i_reg_1600_pp0_iter1_reg <= i_reg_1600;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln75_3_fu_298_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv7_1));
    add_ln813_22_fu_1461_p2 <= std_logic_vector(signed(sext_ln78_2_fu_667_p1) + signed(sext_ln78_3_fu_727_p1));
    add_ln813_23_fu_1471_p2 <= std_logic_vector(signed(sext_ln813_2_fu_1467_p1) + signed(sext_ln813_1_fu_1457_p1));
    add_ln813_24_fu_1481_p2 <= std_logic_vector(signed(sext_ln78_4_fu_787_p1) + signed(sext_ln78_5_fu_847_p1));
    add_ln813_25_fu_1491_p2 <= std_logic_vector(signed(sext_ln78_6_fu_907_p1) + signed(sext_ln78_7_fu_967_p1));
    add_ln813_26_fu_1501_p2 <= std_logic_vector(signed(sext_ln813_5_fu_1497_p1) + signed(sext_ln813_4_fu_1487_p1));
    add_ln813_27_fu_1511_p2 <= std_logic_vector(signed(sext_ln813_6_fu_1507_p1) + signed(sext_ln813_3_fu_1477_p1));
    add_ln813_28_fu_1517_p2 <= std_logic_vector(signed(sext_ln78_8_fu_1027_p1) + signed(sext_ln78_9_fu_1087_p1));
    add_ln813_29_fu_1527_p2 <= std_logic_vector(signed(sext_ln78_10_fu_1147_p1) + signed(sext_ln78_11_fu_1207_p1));
    add_ln813_30_fu_1583_p2 <= std_logic_vector(unsigned(add_ln813_35_fu_1577_p2) + unsigned(add_ln813_27_fu_1511_p2));
    add_ln813_31_fu_1537_p2 <= std_logic_vector(signed(sext_ln813_8_fu_1533_p1) + signed(sext_ln813_7_fu_1523_p1));
    add_ln813_32_fu_1547_p2 <= std_logic_vector(signed(sext_ln78_12_fu_1267_p1) + signed(sext_ln78_13_fu_1327_p1));
    add_ln813_33_fu_1557_p2 <= std_logic_vector(signed(sext_ln78_14_fu_1387_p1) + signed(sext_ln813_fu_1447_p1));
    add_ln813_34_fu_1567_p2 <= std_logic_vector(signed(sext_ln813_11_fu_1563_p1) + signed(sext_ln813_10_fu_1553_p1));
    add_ln813_35_fu_1577_p2 <= std_logic_vector(signed(sext_ln813_12_fu_1573_p1) + signed(sext_ln813_9_fu_1543_p1));
    add_ln813_fu_1451_p2 <= std_logic_vector(signed(sext_ln78_1_fu_607_p1) + signed(sext_ln78_fu_547_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln75_fu_292_p2)
    begin
        if (((icmp_ln75_fu_292_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, hs_fu_74, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i <= hs_fu_74;
        end if; 
    end process;

    empty_461_fu_304_p1 <= ap_sig_allocacmp_i(6 - 1 downto 0);
    global_average_pooling1d_V_address0 <= i_9_cast116_fu_1589_p1(6 - 1 downto 0);

    global_average_pooling1d_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            global_average_pooling1d_V_ce0 <= ap_const_logic_1;
        else 
            global_average_pooling1d_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    global_average_pooling1d_V_d0 <= add_ln813_30_reg_1689;

    global_average_pooling1d_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            global_average_pooling1d_V_we0 <= ap_const_logic_1;
        else 
            global_average_pooling1d_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    i_9_cast116_fu_1589_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_1600_pp0_iter1_reg),64));
    icmp_ln75_fu_292_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv7_40) else "0";
    or_ln78_10_fu_431_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_B);
    or_ln78_11_fu_442_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_C);
    or_ln78_12_fu_453_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_D);
    or_ln78_13_fu_464_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_E);
    or_ln78_14_fu_475_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_F);
    or_ln78_1_fu_332_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_2);
    or_ln78_2_fu_343_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_3);
    or_ln78_3_fu_354_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_4);
    or_ln78_4_fu_365_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_5);
    or_ln78_5_fu_376_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_6);
    or_ln78_6_fu_387_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_7);
    or_ln78_7_fu_398_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_8);
    or_ln78_8_fu_409_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_9);
    or_ln78_9_fu_420_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_A);
    or_ln78_fu_321_p2 <= (tmp_s_fu_308_p3 or ap_const_lv10_1);
    select_ln1303_10_fu_1139_p3 <= 
        sub_ln1303_23_fu_1119_p2 when (tmp_70_fu_1091_p3(0) = '1') else 
        zext_ln1303_23_fu_1135_p1;
    select_ln1303_11_fu_1199_p3 <= 
        sub_ln1303_25_fu_1179_p2 when (tmp_71_fu_1151_p3(0) = '1') else 
        zext_ln1303_25_fu_1195_p1;
    select_ln1303_12_fu_1259_p3 <= 
        sub_ln1303_27_fu_1239_p2 when (tmp_72_fu_1211_p3(0) = '1') else 
        zext_ln1303_27_fu_1255_p1;
    select_ln1303_13_fu_1319_p3 <= 
        sub_ln1303_29_fu_1299_p2 when (tmp_73_fu_1271_p3(0) = '1') else 
        zext_ln1303_29_fu_1315_p1;
    select_ln1303_14_fu_1379_p3 <= 
        sub_ln1303_31_fu_1359_p2 when (tmp_74_fu_1331_p3(0) = '1') else 
        zext_ln1303_31_fu_1375_p1;
    select_ln1303_15_fu_1439_p3 <= 
        sub_ln1303_33_fu_1419_p2 when (tmp_75_fu_1391_p3(0) = '1') else 
        zext_ln1303_33_fu_1435_p1;
    select_ln1303_1_fu_599_p3 <= 
        sub_ln1303_5_fu_579_p2 when (tmp_61_fu_551_p3(0) = '1') else 
        zext_ln1303_5_fu_595_p1;
    select_ln1303_2_fu_659_p3 <= 
        sub_ln1303_7_fu_639_p2 when (tmp_62_fu_611_p3(0) = '1') else 
        zext_ln1303_7_fu_655_p1;
    select_ln1303_3_fu_719_p3 <= 
        sub_ln1303_9_fu_699_p2 when (tmp_63_fu_671_p3(0) = '1') else 
        zext_ln1303_9_fu_715_p1;
    select_ln1303_4_fu_779_p3 <= 
        sub_ln1303_11_fu_759_p2 when (tmp_64_fu_731_p3(0) = '1') else 
        zext_ln1303_11_fu_775_p1;
    select_ln1303_5_fu_839_p3 <= 
        sub_ln1303_13_fu_819_p2 when (tmp_65_fu_791_p3(0) = '1') else 
        zext_ln1303_13_fu_835_p1;
    select_ln1303_6_fu_899_p3 <= 
        sub_ln1303_15_fu_879_p2 when (tmp_66_fu_851_p3(0) = '1') else 
        zext_ln1303_15_fu_895_p1;
    select_ln1303_7_fu_959_p3 <= 
        sub_ln1303_17_fu_939_p2 when (tmp_67_fu_911_p3(0) = '1') else 
        zext_ln1303_17_fu_955_p1;
    select_ln1303_8_fu_1019_p3 <= 
        sub_ln1303_19_fu_999_p2 when (tmp_68_fu_971_p3(0) = '1') else 
        zext_ln1303_19_fu_1015_p1;
    select_ln1303_9_fu_1079_p3 <= 
        sub_ln1303_21_fu_1059_p2 when (tmp_69_fu_1031_p3(0) = '1') else 
        zext_ln1303_21_fu_1075_p1;
    select_ln1303_fu_539_p3 <= 
        sub_ln1303_3_fu_519_p2 when (tmp_fu_491_p3(0) = '1') else 
        zext_ln1303_3_fu_535_p1;
        sext_ln78_10_fu_1147_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_10_fu_1139_p3),30));

        sext_ln78_11_fu_1207_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_11_fu_1199_p3),30));

        sext_ln78_12_fu_1267_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_12_fu_1259_p3),30));

        sext_ln78_13_fu_1327_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_13_fu_1319_p3),30));

        sext_ln78_14_fu_1387_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_14_fu_1379_p3),30));

        sext_ln78_1_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_1_fu_599_p3),30));

        sext_ln78_2_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_2_fu_659_p3),30));

        sext_ln78_3_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_3_fu_719_p3),30));

        sext_ln78_4_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_4_fu_779_p3),30));

        sext_ln78_5_fu_847_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_5_fu_839_p3),30));

        sext_ln78_6_fu_907_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_6_fu_899_p3),30));

        sext_ln78_7_fu_967_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_7_fu_959_p3),30));

        sext_ln78_8_fu_1027_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_8_fu_1019_p3),30));

        sext_ln78_9_fu_1087_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_9_fu_1079_p3),30));

        sext_ln78_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_fu_539_p3),30));

        sext_ln813_10_fu_1553_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_32_fu_1547_p2),31));

        sext_ln813_11_fu_1563_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_33_fu_1557_p2),31));

        sext_ln813_12_fu_1573_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_34_fu_1567_p2),32));

        sext_ln813_1_fu_1457_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_fu_1451_p2),31));

        sext_ln813_2_fu_1467_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_22_fu_1461_p2),31));

        sext_ln813_3_fu_1477_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_23_fu_1471_p2),32));

        sext_ln813_4_fu_1487_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_24_fu_1481_p2),31));

        sext_ln813_5_fu_1497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_25_fu_1491_p2),31));

        sext_ln813_6_fu_1507_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_26_fu_1501_p2),32));

        sext_ln813_7_fu_1523_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_28_fu_1517_p2),31));

        sext_ln813_8_fu_1533_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_29_fu_1527_p2),31));

        sext_ln813_9_fu_1543_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_31_fu_1537_p2),32));

        sext_ln813_fu_1447_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_15_fu_1439_p3),30));

    straight_attention_V_address0 <= zext_ln78_15_fu_481_p1(10 - 1 downto 0);
    straight_attention_V_address1 <= zext_ln78_14_fu_470_p1(10 - 1 downto 0);
    straight_attention_V_address10 <= zext_ln78_5_fu_371_p1(10 - 1 downto 0);
    straight_attention_V_address11 <= zext_ln78_4_fu_360_p1(10 - 1 downto 0);
    straight_attention_V_address12 <= zext_ln78_3_fu_349_p1(10 - 1 downto 0);
    straight_attention_V_address13 <= zext_ln78_2_fu_338_p1(10 - 1 downto 0);
    straight_attention_V_address14 <= zext_ln78_1_fu_327_p1(10 - 1 downto 0);
    straight_attention_V_address15 <= zext_ln78_fu_316_p1(10 - 1 downto 0);
    straight_attention_V_address2 <= zext_ln78_13_fu_459_p1(10 - 1 downto 0);
    straight_attention_V_address3 <= zext_ln78_12_fu_448_p1(10 - 1 downto 0);
    straight_attention_V_address4 <= zext_ln78_11_fu_437_p1(10 - 1 downto 0);
    straight_attention_V_address5 <= zext_ln78_10_fu_426_p1(10 - 1 downto 0);
    straight_attention_V_address6 <= zext_ln78_9_fu_415_p1(10 - 1 downto 0);
    straight_attention_V_address7 <= zext_ln78_8_fu_404_p1(10 - 1 downto 0);
    straight_attention_V_address8 <= zext_ln78_7_fu_393_p1(10 - 1 downto 0);
    straight_attention_V_address9 <= zext_ln78_6_fu_382_p1(10 - 1 downto 0);

    straight_attention_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce0 <= ap_const_logic_1;
        else 
            straight_attention_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce1 <= ap_const_logic_1;
        else 
            straight_attention_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce10_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce10 <= ap_const_logic_1;
        else 
            straight_attention_V_ce10 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce11_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce11 <= ap_const_logic_1;
        else 
            straight_attention_V_ce11 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce12_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce12 <= ap_const_logic_1;
        else 
            straight_attention_V_ce12 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce13_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce13 <= ap_const_logic_1;
        else 
            straight_attention_V_ce13 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce14_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce14 <= ap_const_logic_1;
        else 
            straight_attention_V_ce14 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce15_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce15 <= ap_const_logic_1;
        else 
            straight_attention_V_ce15 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce2 <= ap_const_logic_1;
        else 
            straight_attention_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce3 <= ap_const_logic_1;
        else 
            straight_attention_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce4 <= ap_const_logic_1;
        else 
            straight_attention_V_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce5 <= ap_const_logic_1;
        else 
            straight_attention_V_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce6 <= ap_const_logic_1;
        else 
            straight_attention_V_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce7 <= ap_const_logic_1;
        else 
            straight_attention_V_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce8 <= ap_const_logic_1;
        else 
            straight_attention_V_ce8 <= ap_const_logic_0;
        end if; 
    end process;


    straight_attention_V_ce9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            straight_attention_V_ce9 <= ap_const_logic_1;
        else 
            straight_attention_V_ce9 <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln1303_10_fu_739_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q11));
    sub_ln1303_11_fu_759_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_10_fu_755_p1));
    sub_ln1303_12_fu_799_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q10));
    sub_ln1303_13_fu_819_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_12_fu_815_p1));
    sub_ln1303_14_fu_859_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q9));
    sub_ln1303_15_fu_879_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_14_fu_875_p1));
    sub_ln1303_16_fu_919_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q8));
    sub_ln1303_17_fu_939_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_16_fu_935_p1));
    sub_ln1303_18_fu_979_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q7));
    sub_ln1303_19_fu_999_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_18_fu_995_p1));
    sub_ln1303_20_fu_1039_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q6));
    sub_ln1303_21_fu_1059_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_20_fu_1055_p1));
    sub_ln1303_22_fu_1099_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q5));
    sub_ln1303_23_fu_1119_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_22_fu_1115_p1));
    sub_ln1303_24_fu_1159_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q4));
    sub_ln1303_25_fu_1179_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_24_fu_1175_p1));
    sub_ln1303_26_fu_1219_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q3));
    sub_ln1303_27_fu_1239_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_26_fu_1235_p1));
    sub_ln1303_28_fu_1279_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q2));
    sub_ln1303_29_fu_1299_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_28_fu_1295_p1));
    sub_ln1303_30_fu_1339_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q1));
    sub_ln1303_31_fu_1359_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_30_fu_1355_p1));
    sub_ln1303_32_fu_1399_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q0));
    sub_ln1303_33_fu_1419_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_32_fu_1415_p1));
    sub_ln1303_3_fu_519_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_fu_515_p1));
    sub_ln1303_4_fu_559_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q14));
    sub_ln1303_5_fu_579_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_4_fu_575_p1));
    sub_ln1303_6_fu_619_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q13));
    sub_ln1303_7_fu_639_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_6_fu_635_p1));
    sub_ln1303_8_fu_679_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q12));
    sub_ln1303_9_fu_699_p2 <= std_logic_vector(unsigned(ap_const_lv29_0) - unsigned(zext_ln1303_8_fu_695_p1));
    sub_ln1303_fu_499_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(straight_attention_V_q15));
    tmp_61_fu_551_p3 <= straight_attention_V_q14(31 downto 31);
    tmp_62_fu_611_p3 <= straight_attention_V_q13(31 downto 31);
    tmp_63_fu_671_p3 <= straight_attention_V_q12(31 downto 31);
    tmp_64_fu_731_p3 <= straight_attention_V_q11(31 downto 31);
    tmp_65_fu_791_p3 <= straight_attention_V_q10(31 downto 31);
    tmp_66_fu_851_p3 <= straight_attention_V_q9(31 downto 31);
    tmp_67_fu_911_p3 <= straight_attention_V_q8(31 downto 31);
    tmp_68_fu_971_p3 <= straight_attention_V_q7(31 downto 31);
    tmp_69_fu_1031_p3 <= straight_attention_V_q6(31 downto 31);
    tmp_70_fu_1091_p3 <= straight_attention_V_q5(31 downto 31);
    tmp_71_fu_1151_p3 <= straight_attention_V_q4(31 downto 31);
    tmp_72_fu_1211_p3 <= straight_attention_V_q3(31 downto 31);
    tmp_73_fu_1271_p3 <= straight_attention_V_q2(31 downto 31);
    tmp_74_fu_1331_p3 <= straight_attention_V_q1(31 downto 31);
    tmp_75_fu_1391_p3 <= straight_attention_V_q0(31 downto 31);
    tmp_fu_491_p3 <= straight_attention_V_q15(31 downto 31);
    tmp_s_fu_308_p3 <= (empty_461_fu_304_p1 & ap_const_lv4_0);
    trunc_ln1303_10_fu_765_p4 <= straight_attention_V_q11(31 downto 4);
    trunc_ln1303_11_fu_805_p4 <= sub_ln1303_12_fu_799_p2(31 downto 4);
    trunc_ln1303_12_fu_825_p4 <= straight_attention_V_q10(31 downto 4);
    trunc_ln1303_13_fu_865_p4 <= sub_ln1303_14_fu_859_p2(31 downto 4);
    trunc_ln1303_14_fu_885_p4 <= straight_attention_V_q9(31 downto 4);
    trunc_ln1303_15_fu_925_p4 <= sub_ln1303_16_fu_919_p2(31 downto 4);
    trunc_ln1303_16_fu_945_p4 <= straight_attention_V_q8(31 downto 4);
    trunc_ln1303_17_fu_985_p4 <= sub_ln1303_18_fu_979_p2(31 downto 4);
    trunc_ln1303_18_fu_1005_p4 <= straight_attention_V_q7(31 downto 4);
    trunc_ln1303_19_fu_1045_p4 <= sub_ln1303_20_fu_1039_p2(31 downto 4);
    trunc_ln1303_20_fu_1065_p4 <= straight_attention_V_q6(31 downto 4);
    trunc_ln1303_21_fu_1105_p4 <= sub_ln1303_22_fu_1099_p2(31 downto 4);
    trunc_ln1303_22_fu_1125_p4 <= straight_attention_V_q5(31 downto 4);
    trunc_ln1303_23_fu_1165_p4 <= sub_ln1303_24_fu_1159_p2(31 downto 4);
    trunc_ln1303_24_fu_1185_p4 <= straight_attention_V_q4(31 downto 4);
    trunc_ln1303_25_fu_1225_p4 <= sub_ln1303_26_fu_1219_p2(31 downto 4);
    trunc_ln1303_26_fu_1245_p4 <= straight_attention_V_q3(31 downto 4);
    trunc_ln1303_27_fu_1285_p4 <= sub_ln1303_28_fu_1279_p2(31 downto 4);
    trunc_ln1303_28_fu_1305_p4 <= straight_attention_V_q2(31 downto 4);
    trunc_ln1303_29_fu_1345_p4 <= sub_ln1303_30_fu_1339_p2(31 downto 4);
    trunc_ln1303_2_fu_525_p4 <= straight_attention_V_q15(31 downto 4);
    trunc_ln1303_30_fu_1365_p4 <= straight_attention_V_q1(31 downto 4);
    trunc_ln1303_31_fu_1405_p4 <= sub_ln1303_32_fu_1399_p2(31 downto 4);
    trunc_ln1303_32_fu_1425_p4 <= straight_attention_V_q0(31 downto 4);
    trunc_ln1303_3_fu_565_p4 <= sub_ln1303_4_fu_559_p2(31 downto 4);
    trunc_ln1303_4_fu_585_p4 <= straight_attention_V_q14(31 downto 4);
    trunc_ln1303_5_fu_625_p4 <= sub_ln1303_6_fu_619_p2(31 downto 4);
    trunc_ln1303_6_fu_645_p4 <= straight_attention_V_q13(31 downto 4);
    trunc_ln1303_7_fu_685_p4 <= sub_ln1303_8_fu_679_p2(31 downto 4);
    trunc_ln1303_8_fu_705_p4 <= straight_attention_V_q12(31 downto 4);
    trunc_ln1303_9_fu_745_p4 <= sub_ln1303_10_fu_739_p2(31 downto 4);
    trunc_ln1303_s_fu_505_p4 <= sub_ln1303_fu_499_p2(31 downto 4);
    zext_ln1303_10_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_9_fu_745_p4),29));
    zext_ln1303_11_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_10_fu_765_p4),29));
    zext_ln1303_12_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_11_fu_805_p4),29));
    zext_ln1303_13_fu_835_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_12_fu_825_p4),29));
    zext_ln1303_14_fu_875_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_13_fu_865_p4),29));
    zext_ln1303_15_fu_895_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_14_fu_885_p4),29));
    zext_ln1303_16_fu_935_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_15_fu_925_p4),29));
    zext_ln1303_17_fu_955_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_16_fu_945_p4),29));
    zext_ln1303_18_fu_995_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_17_fu_985_p4),29));
    zext_ln1303_19_fu_1015_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_18_fu_1005_p4),29));
    zext_ln1303_20_fu_1055_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_19_fu_1045_p4),29));
    zext_ln1303_21_fu_1075_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_20_fu_1065_p4),29));
    zext_ln1303_22_fu_1115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_21_fu_1105_p4),29));
    zext_ln1303_23_fu_1135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_22_fu_1125_p4),29));
    zext_ln1303_24_fu_1175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_23_fu_1165_p4),29));
    zext_ln1303_25_fu_1195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_24_fu_1185_p4),29));
    zext_ln1303_26_fu_1235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_25_fu_1225_p4),29));
    zext_ln1303_27_fu_1255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_26_fu_1245_p4),29));
    zext_ln1303_28_fu_1295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_27_fu_1285_p4),29));
    zext_ln1303_29_fu_1315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_28_fu_1305_p4),29));
    zext_ln1303_30_fu_1355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_29_fu_1345_p4),29));
    zext_ln1303_31_fu_1375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_30_fu_1365_p4),29));
    zext_ln1303_32_fu_1415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_31_fu_1405_p4),29));
    zext_ln1303_33_fu_1435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_32_fu_1425_p4),29));
    zext_ln1303_3_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_2_fu_525_p4),29));
    zext_ln1303_4_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_3_fu_565_p4),29));
    zext_ln1303_5_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_4_fu_585_p4),29));
    zext_ln1303_6_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_5_fu_625_p4),29));
    zext_ln1303_7_fu_655_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_6_fu_645_p4),29));
    zext_ln1303_8_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_7_fu_685_p4),29));
    zext_ln1303_9_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_8_fu_705_p4),29));
    zext_ln1303_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_s_fu_505_p4),29));
    zext_ln78_10_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_9_fu_420_p2),64));
    zext_ln78_11_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_10_fu_431_p2),64));
    zext_ln78_12_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_11_fu_442_p2),64));
    zext_ln78_13_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_12_fu_453_p2),64));
    zext_ln78_14_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_13_fu_464_p2),64));
    zext_ln78_15_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_14_fu_475_p2),64));
    zext_ln78_1_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_fu_321_p2),64));
    zext_ln78_2_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_1_fu_332_p2),64));
    zext_ln78_3_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_2_fu_343_p2),64));
    zext_ln78_4_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_3_fu_354_p2),64));
    zext_ln78_5_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_4_fu_365_p2),64));
    zext_ln78_6_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_5_fu_376_p2),64));
    zext_ln78_7_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_6_fu_387_p2),64));
    zext_ln78_8_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_7_fu_398_p2),64));
    zext_ln78_9_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln78_8_fu_409_p2),64));
    zext_ln78_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_308_p3),64));
end behav;
