-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_loop_for_fc_2_loop_for_fa_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    select_ln115 : IN STD_LOGIC_VECTOR (5 downto 0);
    sext_ln115_2 : IN STD_LOGIC_VECTOR (61 downto 0);
    OutPadConv2_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    OutPadConv2_V_ce0 : OUT STD_LOGIC;
    OutPadConv2_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    s_V_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_V_7_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of CNN_CNN_Pipeline_loop_for_fc_2_loop_for_fa_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_1B0 : STD_LOGIC_VECTOR (8 downto 0) := "110110000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln120_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln120_reg_464 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_464_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_464_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_464_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_464_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_464_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_464_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_464_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln123_1_fu_333_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_1_reg_468_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal gmem1_addr_reg_473 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_V_reg_479 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1271_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln1271_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_fu_90 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_94 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln122_fu_361_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (3 downto 0);
    signal k_fu_98 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln120_3_fu_307_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten179_fu_102 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln120_fu_222_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten179_load : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_shl6_fu_184_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl7_fu_196_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl36_cast_fu_192_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln120_fu_180_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln122_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln120_1_fu_245_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl36_mid1_fu_255_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl34_mid1_fu_267_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl36_cast_mid1_fu_263_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_3_fu_275_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln123_fu_204_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln120_1_fu_251_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1271_1_fu_289_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1271_fu_210_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln120_2_fu_295_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln120_fu_237_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_4_cast_fu_319_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln123_2_fu_323_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln123_fu_329_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln120_1_fu_281_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal j_4_cast70_fu_315_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln115_2_cast_fu_150_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln1271_3_fu_339_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln120_2_fu_303_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln1271_2_fu_345_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal lhs_1_fu_402_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_1_fu_396_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_fu_410_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component CNN_mul_32s_32s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_48_1_1_U104 : component CNN_mul_32s_32s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        din0 => OutPadConv2_V_q0,
        din1 => r_V_reg_479,
        dout => r_V_1_fu_396_p2);

    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten179_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln120_fu_216_p2 = ap_const_lv1_0))) then 
                    indvar_flatten179_fu_102 <= add_ln120_fu_222_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten179_fu_102 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln120_fu_216_p2 = ap_const_lv1_0))) then 
                    j_fu_94 <= add_ln122_fu_361_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_94 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln120_fu_216_p2 = ap_const_lv1_0))) then 
                    k_fu_98 <= select_ln120_3_fu_307_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_98 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    lhs_fu_90 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter9 = ap_const_logic_1)) then 
                    lhs_fu_90 <= ret_V_fu_410_p2(47 downto 16);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln120_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln123_1_reg_468 <= add_ln123_1_fu_333_p2;
                gmem1_addr_reg_473 <= sext_ln1271_fu_351_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln123_1_reg_468_pp0_iter1_reg <= add_ln123_1_reg_468;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln120_reg_464 <= icmp_ln120_fu_216_p2;
                icmp_ln120_reg_464_pp0_iter1_reg <= icmp_ln120_reg_464;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln123_1_reg_468_pp0_iter2_reg <= add_ln123_1_reg_468_pp0_iter1_reg;
                add_ln123_1_reg_468_pp0_iter3_reg <= add_ln123_1_reg_468_pp0_iter2_reg;
                add_ln123_1_reg_468_pp0_iter4_reg <= add_ln123_1_reg_468_pp0_iter3_reg;
                add_ln123_1_reg_468_pp0_iter5_reg <= add_ln123_1_reg_468_pp0_iter4_reg;
                add_ln123_1_reg_468_pp0_iter6_reg <= add_ln123_1_reg_468_pp0_iter5_reg;
                add_ln123_1_reg_468_pp0_iter7_reg <= add_ln123_1_reg_468_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                icmp_ln120_reg_464_pp0_iter2_reg <= icmp_ln120_reg_464_pp0_iter1_reg;
                icmp_ln120_reg_464_pp0_iter3_reg <= icmp_ln120_reg_464_pp0_iter2_reg;
                icmp_ln120_reg_464_pp0_iter4_reg <= icmp_ln120_reg_464_pp0_iter3_reg;
                icmp_ln120_reg_464_pp0_iter5_reg <= icmp_ln120_reg_464_pp0_iter4_reg;
                icmp_ln120_reg_464_pp0_iter6_reg <= icmp_ln120_reg_464_pp0_iter5_reg;
                icmp_ln120_reg_464_pp0_iter7_reg <= icmp_ln120_reg_464_pp0_iter6_reg;
                r_V_reg_479 <= m_axi_gmem1_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    OutPadConv2_V_address0 <= zext_ln1271_fu_382_p1(11 - 1 downto 0);

    OutPadConv2_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            OutPadConv2_V_ce0 <= ap_const_logic_1;
        else 
            OutPadConv2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln120_1_fu_245_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv6_1));
    add_ln120_fu_222_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten179_load) + unsigned(ap_const_lv9_1));
    add_ln122_fu_361_p2 <= std_logic_vector(unsigned(select_ln120_fu_237_p3) + unsigned(ap_const_lv4_1));
    add_ln123_1_fu_333_p2 <= std_logic_vector(unsigned(zext_ln123_fu_329_p1) + unsigned(select_ln120_1_fu_281_p3));
    add_ln123_2_fu_323_p2 <= std_logic_vector(unsigned(select_ln115) + unsigned(j_4_cast_fu_319_p1));
    add_ln123_3_fu_275_p2 <= std_logic_vector(unsigned(p_shl34_mid1_fu_267_p3) + unsigned(p_shl36_cast_mid1_fu_263_p1));
    add_ln123_fu_204_p2 <= std_logic_vector(unsigned(p_shl7_fu_196_p3) + unsigned(p_shl36_cast_fu_192_p1));
    add_ln1271_1_fu_289_p2 <= std_logic_vector(unsigned(p_shl36_mid1_fu_255_p3) + unsigned(zext_ln120_1_fu_251_p1));
    add_ln1271_2_fu_345_p2 <= std_logic_vector(unsigned(add_ln1271_3_fu_339_p2) + unsigned(zext_ln120_2_fu_303_p1));
    add_ln1271_3_fu_339_p2 <= std_logic_vector(unsigned(j_4_cast70_fu_315_p1) + unsigned(sext_ln115_2_cast_fu_150_p1));
    add_ln1271_fu_210_p2 <= std_logic_vector(unsigned(p_shl6_fu_184_p3) + unsigned(zext_ln120_fu_180_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_gmem1_RVALID)
    begin
                ap_block_pp0_stage0_01001 <= ((m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter8, m_axi_gmem1_ARREADY, m_axi_gmem1_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1)) or ((m_axi_gmem1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter8, m_axi_gmem1_ARREADY, m_axi_gmem1_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1)) or ((m_axi_gmem1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter8_assign_proc : process(m_axi_gmem1_RVALID)
    begin
                ap_block_state9_pp0_stage0_iter8 <= (m_axi_gmem1_RVALID = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln120_fu_216_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln120_fu_216_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten179_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten179_fu_102)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten179_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten179_load <= indvar_flatten179_fu_102;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_94)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_94;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_98)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_98;
        end if; 
    end process;


    gmem1_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_ARREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_gmem1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln120_fu_216_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten179_load = ap_const_lv9_1B0) else "0";
    icmp_ln122_fu_231_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv4_9) else "0";
    j_4_cast70_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln120_fu_237_p3),63));
    j_4_cast_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln120_fu_237_p3),6));
    lhs_1_fu_402_p3 <= (lhs_fu_90 & ap_const_lv16_0);
    m_axi_gmem1_ARADDR <= gmem1_addr_reg_473;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_1;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    p_shl34_mid1_fu_267_p3 <= (add_ln120_1_fu_245_p2 & ap_const_lv5_0);
    p_shl36_cast_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl6_fu_184_p3),11));
    p_shl36_cast_mid1_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl36_mid1_fu_255_p3),11));
    p_shl36_mid1_fu_255_p3 <= (add_ln120_1_fu_245_p2 & ap_const_lv3_0);
    p_shl6_fu_184_p3 <= (ap_sig_allocacmp_k_1 & ap_const_lv3_0);
    p_shl7_fu_196_p3 <= (ap_sig_allocacmp_k_1 & ap_const_lv5_0);
    ret_V_fu_410_p2 <= std_logic_vector(unsigned(lhs_1_fu_402_p3) + unsigned(r_V_1_fu_396_p2));
    s_V_7_out <= lhs_fu_90;

    s_V_7_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln120_reg_464_pp0_iter7_reg)
    begin
        if (((icmp_ln120_reg_464_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_V_7_out_ap_vld <= ap_const_logic_1;
        else 
            s_V_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln120_1_fu_281_p3 <= 
        add_ln123_3_fu_275_p2 when (icmp_ln122_fu_231_p2(0) = '1') else 
        add_ln123_fu_204_p2;
    select_ln120_2_fu_295_p3 <= 
        add_ln1271_1_fu_289_p2 when (icmp_ln122_fu_231_p2(0) = '1') else 
        add_ln1271_fu_210_p2;
    select_ln120_3_fu_307_p3 <= 
        add_ln120_1_fu_245_p2 when (icmp_ln122_fu_231_p2(0) = '1') else 
        ap_sig_allocacmp_k_1;
    select_ln120_fu_237_p3 <= 
        ap_const_lv4_0 when (icmp_ln122_fu_231_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
        sext_ln115_2_cast_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln115_2),63));

        sext_ln1271_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1271_2_fu_345_p2),64));

    zext_ln120_1_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln120_1_fu_245_p2),9));
    zext_ln120_2_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln120_2_fu_295_p3),63));
    zext_ln120_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_1),9));
    zext_ln123_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln123_2_fu_323_p2),11));
    zext_ln1271_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln123_1_reg_468_pp0_iter7_reg),64));
end behav;
