-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_loop_for_channel_pool_0_loop_for_weight_pool_0 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    batch_normalization_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    batch_normalization_V_ce0 : OUT STD_LOGIC;
    batch_normalization_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_V_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    batch_normalization_V_ce1 : OUT STD_LOGIC;
    batch_normalization_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_V_address2 : OUT STD_LOGIC_VECTOR (12 downto 0);
    batch_normalization_V_ce2 : OUT STD_LOGIC;
    batch_normalization_V_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_V_address3 : OUT STD_LOGIC_VECTOR (12 downto 0);
    batch_normalization_V_ce3 : OUT STD_LOGIC;
    batch_normalization_V_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    average_pooling1d_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    average_pooling1d_V_ce0 : OUT STD_LOGIC;
    average_pooling1d_V_we0 : OUT STD_LOGIC;
    average_pooling1d_V_d0 : OUT STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of CNN_CNN_Pipeline_loop_for_channel_pool_0_loop_for_weight_pool_0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv13_2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_const_lv13_3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000011";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln9_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln21_fu_270_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_reg_420 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln813_9_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln813_fu_243_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln813_10_fu_254_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln813_11_fu_265_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln22_fu_372_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_fu_64 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln23_fu_276_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_y_load : STD_LOGIC_VECTOR (6 downto 0);
    signal z_fu_68 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln9_1_fu_194_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_z_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten92_fu_72 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln9_fu_162_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten92_load : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln12_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln9_1_fu_188_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln9_fu_202_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln9_fu_180_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_460_fu_218_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln_fu_222_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln17_fu_237_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln17_1_fu_248_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln17_2_fu_259_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal index_cast45_fu_214_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_mid3_fu_206_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln813_21_fu_303_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_14_fu_309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1303_fu_323_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1303_s_fu_329_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln1303_1_fu_339_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln1303_1_fu_349_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_fu_315_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1303_1_fu_343_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln1303_2_fu_359_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten92_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln9_fu_156_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten92_fu_72 <= add_ln9_fu_162_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten92_fu_72 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln9_fu_156_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    y_fu_64 <= add_ln23_fu_276_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_64 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    z_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln9_fu_156_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    z_fu_68 <= select_ln9_1_fu_194_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    z_fu_68 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_156_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln21_reg_420 <= add_ln21_fu_270_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln21_fu_270_p2 <= std_logic_vector(unsigned(index_cast45_fu_214_p1) + unsigned(p_mid3_fu_206_p3));
    add_ln23_fu_276_p2 <= std_logic_vector(unsigned(select_ln9_fu_180_p3) + unsigned(ap_const_lv7_1));
    add_ln813_14_fu_309_p2 <= std_logic_vector(unsigned(add_ln813_21_fu_303_p2) + unsigned(add_ln813_fu_297_p2));
    add_ln813_21_fu_303_p2 <= std_logic_vector(unsigned(batch_normalization_V_q2) + unsigned(batch_normalization_V_q0));
    add_ln813_fu_297_p2 <= std_logic_vector(unsigned(batch_normalization_V_q3) + unsigned(batch_normalization_V_q1));
    add_ln9_1_fu_188_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_z_load) + unsigned(ap_const_lv6_1));
    add_ln9_fu_162_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten92_load) + unsigned(ap_const_lv12_1));
    add_ln_fu_222_p4 <= ((trunc_ln9_fu_202_p1 & empty_460_fu_218_p1) & ap_const_lv2_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln9_fu_156_p2)
    begin
        if (((icmp_ln9_fu_156_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten92_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten92_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten92_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten92_load <= indvar_flatten92_fu_72;
        end if; 
    end process;


    ap_sig_allocacmp_y_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, y_fu_64, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_y_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_y_load <= y_fu_64;
        end if; 
    end process;


    ap_sig_allocacmp_z_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, z_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_z_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_z_load <= z_fu_68;
        end if; 
    end process;

    average_pooling1d_V_address0 <= zext_ln22_fu_372_p1(11 - 1 downto 0);

    average_pooling1d_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            average_pooling1d_V_ce0 <= ap_const_logic_1;
        else 
            average_pooling1d_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    average_pooling1d_V_d0 <= 
        sub_ln1303_1_fu_343_p2 when (tmp_fu_315_p3(0) = '1') else 
        zext_ln1303_2_fu_359_p1;

    average_pooling1d_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            average_pooling1d_V_we0 <= ap_const_logic_1;
        else 
            average_pooling1d_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    batch_normalization_V_address0 <= zext_ln813_11_fu_265_p1(13 - 1 downto 0);
    batch_normalization_V_address1 <= zext_ln813_10_fu_254_p1(13 - 1 downto 0);
    batch_normalization_V_address2 <= zext_ln813_fu_243_p1(13 - 1 downto 0);
    batch_normalization_V_address3 <= zext_ln813_9_fu_232_p1(13 - 1 downto 0);

    batch_normalization_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            batch_normalization_V_ce0 <= ap_const_logic_1;
        else 
            batch_normalization_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            batch_normalization_V_ce1 <= ap_const_logic_1;
        else 
            batch_normalization_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_V_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            batch_normalization_V_ce2 <= ap_const_logic_1;
        else 
            batch_normalization_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_V_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            batch_normalization_V_ce3 <= ap_const_logic_1;
        else 
            batch_normalization_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;

    empty_460_fu_218_p1 <= select_ln9_fu_180_p3(6 - 1 downto 0);
    icmp_ln12_fu_174_p2 <= "1" when (ap_sig_allocacmp_y_load = ap_const_lv7_40) else "0";
    icmp_ln9_fu_156_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten92_load = ap_const_lv12_800) else "0";
    index_cast45_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_fu_180_p3),11));
    or_ln17_1_fu_248_p2 <= (ap_const_lv13_2 or add_ln_fu_222_p4);
    or_ln17_2_fu_259_p2 <= (ap_const_lv13_3 or add_ln_fu_222_p4);
    or_ln17_fu_237_p2 <= (ap_const_lv13_1 or add_ln_fu_222_p4);
    p_mid3_fu_206_p3 <= (trunc_ln9_fu_202_p1 & ap_const_lv6_0);
    select_ln9_1_fu_194_p3 <= 
        add_ln9_1_fu_188_p2 when (icmp_ln12_fu_174_p2(0) = '1') else 
        ap_sig_allocacmp_z_load;
    select_ln9_fu_180_p3 <= 
        ap_const_lv7_0 when (icmp_ln12_fu_174_p2(0) = '1') else 
        ap_sig_allocacmp_y_load;
    sub_ln1303_1_fu_343_p2 <= std_logic_vector(unsigned(ap_const_lv31_0) - unsigned(zext_ln1303_1_fu_339_p1));
    sub_ln1303_fu_323_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(add_ln813_14_fu_309_p2));
    tmp_fu_315_p3 <= add_ln813_14_fu_309_p2(31 downto 31);
    trunc_ln1303_1_fu_349_p4 <= add_ln813_14_fu_309_p2(31 downto 2);
    trunc_ln1303_s_fu_329_p4 <= sub_ln1303_fu_323_p2(31 downto 2);
    trunc_ln9_fu_202_p1 <= select_ln9_1_fu_194_p3(5 - 1 downto 0);
    zext_ln1303_1_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_s_fu_329_p4),31));
    zext_ln1303_2_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1303_1_fu_349_p4),31));
    zext_ln22_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_reg_420),64));
    zext_ln813_10_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln17_1_fu_248_p2),64));
    zext_ln813_11_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln17_2_fu_259_p2),64));
    zext_ln813_9_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_222_p4),64));
    zext_ln813_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln17_fu_237_p2),64));
end behav;
