// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        sext_ln97,
        sext_ln97_1,
        sext_ln97_2,
        sext_ln97_3,
        re_lu_1_V_address0,
        re_lu_1_V_ce0,
        re_lu_1_V_q0,
        batch_normalization_1_V_address0,
        batch_normalization_1_V_ce0,
        batch_normalization_1_V_we0,
        batch_normalization_1_V_d0,
        grp_sqrt_fixed_33_17_s_fu_3113_p_din1,
        grp_sqrt_fixed_33_17_s_fu_3113_p_dout0,
        grp_sqrt_fixed_33_17_s_fu_3113_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [61:0] sext_ln97;
input  [61:0] sext_ln97_1;
input  [61:0] sext_ln97_2;
input  [61:0] sext_ln97_3;
output  [11:0] re_lu_1_V_address0;
output   re_lu_1_V_ce0;
input  [30:0] re_lu_1_V_q0;
output  [11:0] batch_normalization_1_V_address0;
output   batch_normalization_1_V_ce0;
output   batch_normalization_1_V_we0;
output  [31:0] batch_normalization_1_V_d0;
output  [32:0] grp_sqrt_fixed_33_17_s_fu_3113_p_din1;
input  [24:0] grp_sqrt_fixed_33_17_s_fu_3113_p_dout0;
output   grp_sqrt_fixed_33_17_s_fu_3113_p_ce;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg[63:0] m_axi_gmem1_ARADDR;
reg m_axi_gmem1_RREADY;
reg re_lu_1_V_ce0;
reg batch_normalization_1_V_ce0;
reg batch_normalization_1_V_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
reg   [0:0] icmp_ln97_reg_500;
reg    ap_block_state4_io;
wire    ap_block_state8_pp0_stage3_iter1;
reg    ap_block_state12_pp0_stage3_iter2;
wire    ap_block_state16_pp0_stage3_iter3;
wire    ap_block_state20_pp0_stage3_iter4;
wire    ap_block_state24_pp0_stage3_iter5;
wire    ap_block_state28_pp0_stage3_iter6;
wire    ap_block_state32_pp0_stage3_iter7;
wire    ap_block_state36_pp0_stage3_iter8;
wire    ap_block_state40_pp0_stage3_iter9;
wire    ap_block_state44_pp0_stage3_iter10;
wire    ap_block_state48_pp0_stage3_iter11;
wire    ap_block_state52_pp0_stage3_iter12;
wire    ap_block_state56_pp0_stage3_iter13;
wire    ap_block_state60_pp0_stage3_iter14;
wire    ap_block_state64_pp0_stage3_iter15;
wire    ap_block_state68_pp0_stage3_iter16;
wire    ap_block_state72_pp0_stage3_iter17;
reg    ap_block_pp0_stage3_subdone;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
wire  signed [62:0] sext_ln97_3_cast_fu_205_p1;
reg  signed [62:0] sext_ln97_3_cast_reg_485;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state13_pp0_stage0_iter3;
wire    ap_block_state17_pp0_stage0_iter4;
wire    ap_block_state21_pp0_stage0_iter5;
wire    ap_block_state25_pp0_stage0_iter6;
wire    ap_block_state29_pp0_stage0_iter7;
wire    ap_block_state33_pp0_stage0_iter8;
wire    ap_block_state37_pp0_stage0_iter9;
wire    ap_block_state41_pp0_stage0_iter10;
wire    ap_block_state45_pp0_stage0_iter11;
wire    ap_block_state49_pp0_stage0_iter12;
wire    ap_block_state53_pp0_stage0_iter13;
wire    ap_block_state57_pp0_stage0_iter14;
wire    ap_block_state61_pp0_stage0_iter15;
wire    ap_block_state65_pp0_stage0_iter16;
wire    ap_block_state69_pp0_stage0_iter17;
wire    ap_block_state73_pp0_stage0_iter18;
reg    ap_block_pp0_stage0_11001;
wire  signed [62:0] sext_ln97_2_cast_fu_209_p1;
reg  signed [62:0] sext_ln97_2_cast_reg_490;
wire  signed [62:0] sext_ln97_1_cast_fu_213_p1;
reg  signed [62:0] sext_ln97_1_cast_reg_495;
wire   [0:0] icmp_ln97_fu_239_p2;
reg   [0:0] icmp_ln97_reg_500_pp0_iter1_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter2_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter3_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter4_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter5_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter6_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter7_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter8_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter9_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter10_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter11_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter12_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter13_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter14_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter15_reg;
reg   [0:0] icmp_ln97_reg_500_pp0_iter16_reg;
wire   [62:0] zext_ln97_fu_293_p1;
reg   [62:0] zext_ln97_reg_504;
reg   [63:0] gmem1_addr_47_reg_511;
wire   [63:0] zext_ln813_fu_323_p1;
reg   [63:0] zext_ln813_reg_517;
reg   [63:0] zext_ln813_reg_517_pp0_iter1_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter2_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter3_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter4_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter5_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter6_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter7_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter8_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter9_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter10_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter11_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter12_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter13_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter14_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter15_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter16_reg;
reg   [63:0] zext_ln813_reg_517_pp0_iter17_reg;
reg   [63:0] gmem1_addr_48_reg_527;
wire    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state2_io;
wire    ap_block_state6_pp0_stage1_iter1;
reg    ap_block_state10_pp0_stage1_iter2;
wire    ap_block_state14_pp0_stage1_iter3;
wire    ap_block_state18_pp0_stage1_iter4;
wire    ap_block_state22_pp0_stage1_iter5;
wire    ap_block_state26_pp0_stage1_iter6;
wire    ap_block_state30_pp0_stage1_iter7;
wire    ap_block_state34_pp0_stage1_iter8;
wire    ap_block_state38_pp0_stage1_iter9;
wire    ap_block_state42_pp0_stage1_iter10;
wire    ap_block_state46_pp0_stage1_iter11;
wire    ap_block_state50_pp0_stage1_iter12;
wire    ap_block_state54_pp0_stage1_iter13;
wire    ap_block_state58_pp0_stage1_iter14;
wire    ap_block_state62_pp0_stage1_iter15;
wire    ap_block_state66_pp0_stage1_iter16;
wire    ap_block_state70_pp0_stage1_iter17;
reg    ap_block_pp0_stage1_11001;
reg   [63:0] gmem1_addr_49_reg_533;
reg   [63:0] gmem1_addr_50_reg_539;
reg   [30:0] lhs_reg_545;
reg   [30:0] lhs_reg_545_pp0_iter1_reg;
reg  signed [31:0] gmem1_addr_47_read_reg_550;
reg  signed [31:0] gmem1_addr_48_read_reg_555;
wire   [32:0] ret_V_fu_397_p2;
reg   [32:0] ret_V_reg_560;
reg   [32:0] ret_V_reg_560_pp0_iter3_reg;
reg   [32:0] ret_V_reg_560_pp0_iter4_reg;
wire   [32:0] add_ln97_4_fu_406_p2;
reg   [32:0] add_ln97_4_reg_565;
wire    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_state3_io;
wire    ap_block_state7_pp0_stage2_iter1;
reg    ap_block_state11_pp0_stage2_iter2;
wire    ap_block_state15_pp0_stage2_iter3;
wire    ap_block_state19_pp0_stage2_iter4;
wire    ap_block_state23_pp0_stage2_iter5;
wire    ap_block_state27_pp0_stage2_iter6;
wire    ap_block_state31_pp0_stage2_iter7;
wire    ap_block_state35_pp0_stage2_iter8;
wire    ap_block_state39_pp0_stage2_iter9;
wire    ap_block_state43_pp0_stage2_iter10;
wire    ap_block_state47_pp0_stage2_iter11;
wire    ap_block_state51_pp0_stage2_iter12;
wire    ap_block_state55_pp0_stage2_iter13;
wire    ap_block_state59_pp0_stage2_iter14;
wire    ap_block_state63_pp0_stage2_iter15;
wire    ap_block_state67_pp0_stage2_iter16;
wire    ap_block_state71_pp0_stage2_iter17;
reg    ap_block_pp0_stage2_11001;
reg  signed [31:0] gmem1_addr_49_read_reg_570;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter3_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter4_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter5_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter6_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter7_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter8_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter9_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter10_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter11_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter12_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter13_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter14_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter15_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter16_reg;
reg  signed [31:0] gmem1_addr_49_read_reg_570_pp0_iter17_reg;
reg   [31:0] gmem1_addr_50_read_reg_575;
reg    ap_block_pp0_stage3_11001;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter3_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter4_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter5_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter6_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter7_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter8_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter9_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter10_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter11_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter12_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter13_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter14_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter15_reg;
reg   [31:0] gmem1_addr_50_read_reg_575_pp0_iter16_reg;
reg   [24:0] sext_ln1303_1_reg_580;
reg   [31:0] trunc_ln818_2_reg_595;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg    grp_sqrt_fixed_33_17_s_fu_200_ap_ce;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call44;
wire    ap_block_state8_pp0_stage3_iter1_ignore_call44;
reg    ap_block_state12_pp0_stage3_iter2_ignore_call44;
wire    ap_block_state16_pp0_stage3_iter3_ignore_call44;
wire    ap_block_state20_pp0_stage3_iter4_ignore_call44;
wire    ap_block_state24_pp0_stage3_iter5_ignore_call44;
wire    ap_block_state28_pp0_stage3_iter6_ignore_call44;
wire    ap_block_state32_pp0_stage3_iter7_ignore_call44;
wire    ap_block_state36_pp0_stage3_iter8_ignore_call44;
wire    ap_block_state40_pp0_stage3_iter9_ignore_call44;
wire    ap_block_state44_pp0_stage3_iter10_ignore_call44;
wire    ap_block_state48_pp0_stage3_iter11_ignore_call44;
wire    ap_block_state52_pp0_stage3_iter12_ignore_call44;
wire    ap_block_state56_pp0_stage3_iter13_ignore_call44;
wire    ap_block_state60_pp0_stage3_iter14_ignore_call44;
wire    ap_block_state64_pp0_stage3_iter15_ignore_call44;
wire    ap_block_state68_pp0_stage3_iter16_ignore_call44;
wire    ap_block_state72_pp0_stage3_iter17_ignore_call44;
reg    ap_block_pp0_stage3_11001_ignoreCallOp165;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call44;
wire    ap_block_state5_pp0_stage0_iter1_ignore_call44;
reg    ap_block_state9_pp0_stage0_iter2_ignore_call44;
wire    ap_block_state13_pp0_stage0_iter3_ignore_call44;
wire    ap_block_state17_pp0_stage0_iter4_ignore_call44;
wire    ap_block_state21_pp0_stage0_iter5_ignore_call44;
wire    ap_block_state25_pp0_stage0_iter6_ignore_call44;
wire    ap_block_state29_pp0_stage0_iter7_ignore_call44;
wire    ap_block_state33_pp0_stage0_iter8_ignore_call44;
wire    ap_block_state37_pp0_stage0_iter9_ignore_call44;
wire    ap_block_state41_pp0_stage0_iter10_ignore_call44;
wire    ap_block_state45_pp0_stage0_iter11_ignore_call44;
wire    ap_block_state49_pp0_stage0_iter12_ignore_call44;
wire    ap_block_state53_pp0_stage0_iter13_ignore_call44;
wire    ap_block_state57_pp0_stage0_iter14_ignore_call44;
wire    ap_block_state61_pp0_stage0_iter15_ignore_call44;
wire    ap_block_state65_pp0_stage0_iter16_ignore_call44;
wire    ap_block_state69_pp0_stage0_iter17_ignore_call44;
wire    ap_block_state73_pp0_stage0_iter18_ignore_call44;
reg    ap_block_pp0_stage0_11001_ignoreCallOp166;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call44;
wire    ap_block_state6_pp0_stage1_iter1_ignore_call44;
reg    ap_block_state10_pp0_stage1_iter2_ignore_call44;
wire    ap_block_state14_pp0_stage1_iter3_ignore_call44;
wire    ap_block_state18_pp0_stage1_iter4_ignore_call44;
wire    ap_block_state22_pp0_stage1_iter5_ignore_call44;
wire    ap_block_state26_pp0_stage1_iter6_ignore_call44;
wire    ap_block_state30_pp0_stage1_iter7_ignore_call44;
wire    ap_block_state34_pp0_stage1_iter8_ignore_call44;
wire    ap_block_state38_pp0_stage1_iter9_ignore_call44;
wire    ap_block_state42_pp0_stage1_iter10_ignore_call44;
wire    ap_block_state46_pp0_stage1_iter11_ignore_call44;
wire    ap_block_state50_pp0_stage1_iter12_ignore_call44;
wire    ap_block_state54_pp0_stage1_iter13_ignore_call44;
wire    ap_block_state58_pp0_stage1_iter14_ignore_call44;
wire    ap_block_state62_pp0_stage1_iter15_ignore_call44;
wire    ap_block_state66_pp0_stage1_iter16_ignore_call44;
wire    ap_block_state70_pp0_stage1_iter17_ignore_call44;
reg    ap_block_pp0_stage1_11001_ignoreCallOp167;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call44;
wire    ap_block_state7_pp0_stage2_iter1_ignore_call44;
reg    ap_block_state11_pp0_stage2_iter2_ignore_call44;
wire    ap_block_state15_pp0_stage2_iter3_ignore_call44;
wire    ap_block_state19_pp0_stage2_iter4_ignore_call44;
wire    ap_block_state23_pp0_stage2_iter5_ignore_call44;
wire    ap_block_state27_pp0_stage2_iter6_ignore_call44;
wire    ap_block_state31_pp0_stage2_iter7_ignore_call44;
wire    ap_block_state35_pp0_stage2_iter8_ignore_call44;
wire    ap_block_state39_pp0_stage2_iter9_ignore_call44;
wire    ap_block_state43_pp0_stage2_iter10_ignore_call44;
wire    ap_block_state47_pp0_stage2_iter11_ignore_call44;
wire    ap_block_state51_pp0_stage2_iter12_ignore_call44;
wire    ap_block_state55_pp0_stage2_iter13_ignore_call44;
wire    ap_block_state59_pp0_stage2_iter14_ignore_call44;
wire    ap_block_state63_pp0_stage2_iter15_ignore_call44;
wire    ap_block_state67_pp0_stage2_iter16_ignore_call44;
wire    ap_block_state71_pp0_stage2_iter17_ignore_call44;
reg    ap_block_pp0_stage2_11001_ignoreCallOp168;
wire  signed [63:0] sext_ln97_4_fu_303_p1;
wire  signed [63:0] sext_ln97_6_fu_353_p1;
wire  signed [63:0] sext_ln97_8_fu_367_p1;
wire  signed [63:0] sext_ln97_10_fu_381_p1;
reg   [6:0] j_1_fu_90;
wire   [6:0] add_ln98_fu_328_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_1_load;
reg   [5:0] i_fu_94;
wire   [5:0] select_ln97_1_fu_277_p3;
reg   [5:0] ap_sig_allocacmp_i_load;
reg   [11:0] indvar_flatten152_fu_98;
wire   [11:0] add_ln97_fu_245_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten152_load;
wire   [0:0] icmp_ln98_fu_257_p2;
wire   [5:0] add_ln97_1_fu_271_p2;
wire  signed [62:0] sext_ln97_cast_fu_217_p1;
wire   [62:0] add_ln97_2_fu_297_p2;
wire   [6:0] select_ln97_fu_263_p3;
wire   [11:0] j_1_cast_fu_313_p1;
wire   [11:0] p_mid6_fu_285_p3;
wire   [11:0] add_ln99_fu_317_p2;
wire   [62:0] add_ln97_3_fu_349_p2;
wire   [62:0] add_ln97_5_fu_363_p2;
wire   [62:0] add_ln97_6_fu_377_p2;
wire   [32:0] zext_ln813_12_fu_394_p1;
wire  signed [32:0] sext_ln97_5_fu_391_p1;
wire  signed [32:0] sext_ln97_7_fu_403_p1;
wire   [48:0] grp_fu_422_p0;
wire   [25:0] grp_fu_422_p1;
wire   [47:0] grp_fu_422_p2;
wire  signed [47:0] r_V_4_fu_442_p0;
wire   [47:0] rhs_5_mid2_fu_431_p3;
wire   [47:0] r_V_4_fu_442_p2;
wire   [47:0] ret_V_1_fu_448_p2;
reg    grp_fu_422_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter17_stage0;
reg    ap_idle_pp0_0to16;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to18;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [48:0] grp_fu_422_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_sdiv_49ns_26ns_48_53_1 #(
    .ID( 1 ),
    .NUM_STAGE( 53 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 48 ))
sdiv_49ns_26ns_48_53_1_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_422_p0),
    .din1(grp_fu_422_p1),
    .ce(grp_fu_422_ce),
    .dout(grp_fu_422_p2)
);

CNN_mul_48s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_48s_32s_48_1_1_U92(
    .din0(r_V_4_fu_442_p0),
    .din1(gmem1_addr_49_read_reg_570_pp0_iter17_reg),
    .dout(r_V_4_fu_442_p2)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter17_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter18 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln97_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_94 <= select_ln97_1_fu_277_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_94 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln97_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten152_fu_98 <= add_ln97_fu_245_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten152_fu_98 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln97_fu_239_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_1_fu_90 <= add_ln98_fu_328_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_90 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        add_ln97_4_reg_565 <= add_ln97_4_fu_406_p2;
        gmem1_addr_49_read_reg_570 <= m_axi_gmem1_RDATA;
        gmem1_addr_49_read_reg_570_pp0_iter10_reg <= gmem1_addr_49_read_reg_570_pp0_iter9_reg;
        gmem1_addr_49_read_reg_570_pp0_iter11_reg <= gmem1_addr_49_read_reg_570_pp0_iter10_reg;
        gmem1_addr_49_read_reg_570_pp0_iter12_reg <= gmem1_addr_49_read_reg_570_pp0_iter11_reg;
        gmem1_addr_49_read_reg_570_pp0_iter13_reg <= gmem1_addr_49_read_reg_570_pp0_iter12_reg;
        gmem1_addr_49_read_reg_570_pp0_iter14_reg <= gmem1_addr_49_read_reg_570_pp0_iter13_reg;
        gmem1_addr_49_read_reg_570_pp0_iter15_reg <= gmem1_addr_49_read_reg_570_pp0_iter14_reg;
        gmem1_addr_49_read_reg_570_pp0_iter16_reg <= gmem1_addr_49_read_reg_570_pp0_iter15_reg;
        gmem1_addr_49_read_reg_570_pp0_iter17_reg <= gmem1_addr_49_read_reg_570_pp0_iter16_reg;
        gmem1_addr_49_read_reg_570_pp0_iter3_reg <= gmem1_addr_49_read_reg_570;
        gmem1_addr_49_read_reg_570_pp0_iter4_reg <= gmem1_addr_49_read_reg_570_pp0_iter3_reg;
        gmem1_addr_49_read_reg_570_pp0_iter5_reg <= gmem1_addr_49_read_reg_570_pp0_iter4_reg;
        gmem1_addr_49_read_reg_570_pp0_iter6_reg <= gmem1_addr_49_read_reg_570_pp0_iter5_reg;
        gmem1_addr_49_read_reg_570_pp0_iter7_reg <= gmem1_addr_49_read_reg_570_pp0_iter6_reg;
        gmem1_addr_49_read_reg_570_pp0_iter8_reg <= gmem1_addr_49_read_reg_570_pp0_iter7_reg;
        gmem1_addr_49_read_reg_570_pp0_iter9_reg <= gmem1_addr_49_read_reg_570_pp0_iter8_reg;
        sext_ln1303_1_reg_580 <= grp_sqrt_fixed_33_17_s_fu_3113_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem1_addr_47_read_reg_550 <= m_axi_gmem1_RDATA;
        icmp_ln97_reg_500 <= icmp_ln97_fu_239_p2;
        icmp_ln97_reg_500_pp0_iter10_reg <= icmp_ln97_reg_500_pp0_iter9_reg;
        icmp_ln97_reg_500_pp0_iter11_reg <= icmp_ln97_reg_500_pp0_iter10_reg;
        icmp_ln97_reg_500_pp0_iter12_reg <= icmp_ln97_reg_500_pp0_iter11_reg;
        icmp_ln97_reg_500_pp0_iter13_reg <= icmp_ln97_reg_500_pp0_iter12_reg;
        icmp_ln97_reg_500_pp0_iter14_reg <= icmp_ln97_reg_500_pp0_iter13_reg;
        icmp_ln97_reg_500_pp0_iter15_reg <= icmp_ln97_reg_500_pp0_iter14_reg;
        icmp_ln97_reg_500_pp0_iter16_reg <= icmp_ln97_reg_500_pp0_iter15_reg;
        icmp_ln97_reg_500_pp0_iter1_reg <= icmp_ln97_reg_500;
        icmp_ln97_reg_500_pp0_iter2_reg <= icmp_ln97_reg_500_pp0_iter1_reg;
        icmp_ln97_reg_500_pp0_iter3_reg <= icmp_ln97_reg_500_pp0_iter2_reg;
        icmp_ln97_reg_500_pp0_iter4_reg <= icmp_ln97_reg_500_pp0_iter3_reg;
        icmp_ln97_reg_500_pp0_iter5_reg <= icmp_ln97_reg_500_pp0_iter4_reg;
        icmp_ln97_reg_500_pp0_iter6_reg <= icmp_ln97_reg_500_pp0_iter5_reg;
        icmp_ln97_reg_500_pp0_iter7_reg <= icmp_ln97_reg_500_pp0_iter6_reg;
        icmp_ln97_reg_500_pp0_iter8_reg <= icmp_ln97_reg_500_pp0_iter7_reg;
        icmp_ln97_reg_500_pp0_iter9_reg <= icmp_ln97_reg_500_pp0_iter8_reg;
        sext_ln97_1_cast_reg_495 <= sext_ln97_1_cast_fu_213_p1;
        sext_ln97_2_cast_reg_490 <= sext_ln97_2_cast_fu_209_p1;
        sext_ln97_3_cast_reg_485 <= sext_ln97_3_cast_fu_205_p1;
        zext_ln813_reg_517_pp0_iter10_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter9_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter11_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter10_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter12_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter11_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter13_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter12_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter14_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter13_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter15_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter14_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter16_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter15_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter17_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter16_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter1_reg[11 : 0] <= zext_ln813_reg_517[11 : 0];
        zext_ln813_reg_517_pp0_iter2_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter1_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter3_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter2_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter4_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter3_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter5_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter4_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter6_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter5_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter7_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter6_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter8_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter7_reg[11 : 0];
        zext_ln813_reg_517_pp0_iter9_reg[11 : 0] <= zext_ln813_reg_517_pp0_iter8_reg[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln97_fu_239_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem1_addr_47_reg_511 <= sext_ln97_4_fu_303_p1;
        zext_ln813_reg_517[11 : 0] <= zext_ln813_fu_323_p1[11 : 0];
        zext_ln97_reg_504[5 : 0] <= zext_ln97_fu_293_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        gmem1_addr_48_read_reg_555 <= m_axi_gmem1_RDATA;
        lhs_reg_545_pp0_iter1_reg <= lhs_reg_545;
        ret_V_reg_560 <= ret_V_fu_397_p2;
        ret_V_reg_560_pp0_iter3_reg <= ret_V_reg_560;
        ret_V_reg_560_pp0_iter4_reg <= ret_V_reg_560_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln97_reg_500 == 1'd0))) begin
        gmem1_addr_48_reg_527 <= sext_ln97_6_fu_353_p1;
        gmem1_addr_49_reg_533 <= sext_ln97_8_fu_367_p1;
        gmem1_addr_50_reg_539 <= sext_ln97_10_fu_381_p1;
        lhs_reg_545 <= re_lu_1_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        gmem1_addr_50_read_reg_575 <= m_axi_gmem1_RDATA;
        gmem1_addr_50_read_reg_575_pp0_iter10_reg <= gmem1_addr_50_read_reg_575_pp0_iter9_reg;
        gmem1_addr_50_read_reg_575_pp0_iter11_reg <= gmem1_addr_50_read_reg_575_pp0_iter10_reg;
        gmem1_addr_50_read_reg_575_pp0_iter12_reg <= gmem1_addr_50_read_reg_575_pp0_iter11_reg;
        gmem1_addr_50_read_reg_575_pp0_iter13_reg <= gmem1_addr_50_read_reg_575_pp0_iter12_reg;
        gmem1_addr_50_read_reg_575_pp0_iter14_reg <= gmem1_addr_50_read_reg_575_pp0_iter13_reg;
        gmem1_addr_50_read_reg_575_pp0_iter15_reg <= gmem1_addr_50_read_reg_575_pp0_iter14_reg;
        gmem1_addr_50_read_reg_575_pp0_iter16_reg <= gmem1_addr_50_read_reg_575_pp0_iter15_reg;
        gmem1_addr_50_read_reg_575_pp0_iter3_reg <= gmem1_addr_50_read_reg_575;
        gmem1_addr_50_read_reg_575_pp0_iter4_reg <= gmem1_addr_50_read_reg_575_pp0_iter3_reg;
        gmem1_addr_50_read_reg_575_pp0_iter5_reg <= gmem1_addr_50_read_reg_575_pp0_iter4_reg;
        gmem1_addr_50_read_reg_575_pp0_iter6_reg <= gmem1_addr_50_read_reg_575_pp0_iter5_reg;
        gmem1_addr_50_read_reg_575_pp0_iter7_reg <= gmem1_addr_50_read_reg_575_pp0_iter6_reg;
        gmem1_addr_50_read_reg_575_pp0_iter8_reg <= gmem1_addr_50_read_reg_575_pp0_iter7_reg;
        gmem1_addr_50_read_reg_575_pp0_iter9_reg <= gmem1_addr_50_read_reg_575_pp0_iter8_reg;
        trunc_ln818_2_reg_595 <= {{ret_V_1_fu_448_p2[47:16]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone) & (icmp_ln97_reg_500 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (icmp_ln97_reg_500_pp0_iter16_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter17_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter17_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter17_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to16 = 1'b1;
    end else begin
        ap_idle_pp0_0to16 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to18 = 1'b1;
    end else begin
        ap_idle_pp0_1to18 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_94;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten152_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten152_load = indvar_flatten152_fu_98;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1_load = j_1_fu_90;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        batch_normalization_1_V_ce0 = 1'b1;
    end else begin
        batch_normalization_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        batch_normalization_1_V_we0 = 1'b1;
    end else begin
        batch_normalization_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (icmp_ln97_reg_500 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (icmp_ln97_reg_500 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (icmp_ln97_reg_500 == 1'd0)))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_422_ce = 1'b1;
    end else begin
        grp_fu_422_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp165)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp168)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp167)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp166)))) begin
        grp_sqrt_fixed_33_17_s_fu_200_ap_ce = 1'b1;
    end else begin
        grp_sqrt_fixed_33_17_s_fu_200_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_ARADDR = gmem1_addr_50_reg_539;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln97_reg_500 == 1'd0))) begin
        m_axi_gmem1_ARADDR = gmem1_addr_49_reg_533;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln97_reg_500 == 1'd0))) begin
        m_axi_gmem1_ARADDR = gmem1_addr_48_reg_527;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln97_reg_500 == 1'd0))) begin
        m_axi_gmem1_ARADDR = gmem1_addr_47_reg_511;
    end else begin
        m_axi_gmem1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln97_reg_500 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln97_reg_500 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln97_reg_500 == 1'd0)))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        re_lu_1_V_ce0 = 1'b1;
    end else begin
        re_lu_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to16 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter17_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to18 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln97_1_fu_271_p2 = (ap_sig_allocacmp_i_load + 6'd1);

assign add_ln97_2_fu_297_p2 = ($signed(zext_ln97_fu_293_p1) + $signed(sext_ln97_cast_fu_217_p1));

assign add_ln97_3_fu_349_p2 = ($signed(zext_ln97_reg_504) + $signed(sext_ln97_1_cast_reg_495));

assign add_ln97_4_fu_406_p2 = ($signed(sext_ln97_7_fu_403_p1) + $signed(33'd65));

assign add_ln97_5_fu_363_p2 = ($signed(zext_ln97_reg_504) + $signed(sext_ln97_2_cast_reg_490));

assign add_ln97_6_fu_377_p2 = ($signed(zext_ln97_reg_504) + $signed(sext_ln97_3_cast_reg_485));

assign add_ln97_fu_245_p2 = (ap_sig_allocacmp_indvar_flatten152_load + 12'd1);

assign add_ln98_fu_328_p2 = (select_ln97_fu_263_p3 + 7'd1);

assign add_ln99_fu_317_p2 = (j_1_cast_fu_313_p1 + p_mid6_fu_285_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem1_ARREADY == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp166 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem1_ARREADY == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (m_axi_gmem1_ARREADY == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp167 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_ignoreCallOp168 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_ignoreCallOp165 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter2 = (m_axi_gmem1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter2_ignore_call44 = (m_axi_gmem1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state11_pp0_stage2_iter2 = (m_axi_gmem1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state11_pp0_stage2_iter2_ignore_call44 = (m_axi_gmem1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage3_iter2 = (m_axi_gmem1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage3_iter2_ignore_call44 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_block_state13_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter3_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter3_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter3_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter3_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter4_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter4_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter4_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter4_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter5_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter5_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage2_iter5_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage3_iter5_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter6_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter6_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter6_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter6_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter7_ignore_call44 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((icmp_ln97_reg_500 == 1'd0) & (m_axi_gmem1_ARREADY == 1'b0));
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage1_iter7_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage2_iter7_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage3_iter7_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter8_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage1_iter8_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage2_iter8_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage3_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage3_iter8_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter9_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage1_iter9_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage2_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage2_iter9_ignore_call44 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((icmp_ln97_reg_500 == 1'd0) & (m_axi_gmem1_ARREADY == 1'b0));
end

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage3_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage3_iter9_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter10_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage1_iter10_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage2_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage2_iter10_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage3_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage3_iter10_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter11_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage1_iter11_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage2_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage2_iter11_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage3_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage3_iter11_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter12_ignore_call44 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((icmp_ln97_reg_500 == 1'd0) & (m_axi_gmem1_ARREADY == 1'b0));
end

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage1_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage1_iter12_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage2_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage2_iter12_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage3_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage3_iter12_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage0_iter13_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage1_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage1_iter13_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage2_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage2_iter13_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage3_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage3_iter13_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage0_iter14_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage1_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage1_iter14_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage2_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage2_iter14_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage3_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage3_iter14_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage0_iter15_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage1_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage1_iter15_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage2_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage2_iter15_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state64_pp0_stage3_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state64_pp0_stage3_iter15_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp0_stage0_iter16_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp0_stage1_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp0_stage1_iter16_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state67_pp0_stage2_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state67_pp0_stage2_iter16_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state68_pp0_stage3_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state68_pp0_stage3_iter16_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state69_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state69_pp0_stage0_iter17_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state70_pp0_stage1_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state70_pp0_stage1_iter17_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state71_pp0_stage2_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state71_pp0_stage2_iter17_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state72_pp0_stage3_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state72_pp0_stage3_iter17_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state73_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state73_pp0_stage0_iter18_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1_ignore_call44 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1_ignore_call44 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter2 = (m_axi_gmem1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter2_ignore_call44 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign batch_normalization_1_V_address0 = zext_ln813_reg_517_pp0_iter17_reg;

assign batch_normalization_1_V_d0 = trunc_ln818_2_reg_595;

assign grp_fu_422_p0 = {{ret_V_reg_560_pp0_iter4_reg}, {16'd0}};

assign grp_fu_422_p1 = grp_fu_422_p10;

assign grp_fu_422_p10 = sext_ln1303_1_reg_580;

assign grp_sqrt_fixed_33_17_s_fu_3113_p_ce = grp_sqrt_fixed_33_17_s_fu_200_ap_ce;

assign grp_sqrt_fixed_33_17_s_fu_3113_p_din1 = add_ln97_4_reg_565;

assign icmp_ln97_fu_239_p2 = ((ap_sig_allocacmp_indvar_flatten152_load == 12'd3072) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_257_p2 = ((ap_sig_allocacmp_j_1_load == 7'd64) ? 1'b1 : 1'b0);

assign j_1_cast_fu_313_p1 = select_ln97_fu_263_p3;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd1;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign p_mid6_fu_285_p3 = {{select_ln97_1_fu_277_p3}, {6'd0}};

assign r_V_4_fu_442_p0 = grp_fu_422_p2[47:0];

assign re_lu_1_V_address0 = zext_ln813_fu_323_p1;

assign ret_V_1_fu_448_p2 = (rhs_5_mid2_fu_431_p3 + r_V_4_fu_442_p2);

assign ret_V_fu_397_p2 = ($signed(zext_ln813_12_fu_394_p1) - $signed(sext_ln97_5_fu_391_p1));

assign rhs_5_mid2_fu_431_p3 = {{gmem1_addr_50_read_reg_575_pp0_iter16_reg}, {16'd0}};

assign select_ln97_1_fu_277_p3 = ((icmp_ln98_fu_257_p2[0:0] == 1'b1) ? add_ln97_1_fu_271_p2 : ap_sig_allocacmp_i_load);

assign select_ln97_fu_263_p3 = ((icmp_ln98_fu_257_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_1_load);

assign sext_ln97_10_fu_381_p1 = $signed(add_ln97_6_fu_377_p2);

assign sext_ln97_1_cast_fu_213_p1 = $signed(sext_ln97_1);

assign sext_ln97_2_cast_fu_209_p1 = $signed(sext_ln97_2);

assign sext_ln97_3_cast_fu_205_p1 = $signed(sext_ln97_3);

assign sext_ln97_4_fu_303_p1 = $signed(add_ln97_2_fu_297_p2);

assign sext_ln97_5_fu_391_p1 = gmem1_addr_47_read_reg_550;

assign sext_ln97_6_fu_353_p1 = $signed(add_ln97_3_fu_349_p2);

assign sext_ln97_7_fu_403_p1 = gmem1_addr_48_read_reg_555;

assign sext_ln97_8_fu_367_p1 = $signed(add_ln97_5_fu_363_p2);

assign sext_ln97_cast_fu_217_p1 = $signed(sext_ln97);

assign zext_ln813_12_fu_394_p1 = lhs_reg_545_pp0_iter1_reg;

assign zext_ln813_fu_323_p1 = add_ln99_fu_317_p2;

assign zext_ln97_fu_293_p1 = select_ln97_1_fu_277_p3;

always @ (posedge ap_clk) begin
    zext_ln97_reg_504[62:6] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter1_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter2_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter3_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter4_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter5_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter6_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter7_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter8_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter9_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter10_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter11_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter12_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter13_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter14_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter15_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter16_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln813_reg_517_pp0_iter17_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //CNN_CNN_Pipeline_VITIS_LOOP_97_1_VITIS_LOOP_98_2
