// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_channel_pool_1_loop_for_weight_pool_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        batch_normalization_1_V_address0,
        batch_normalization_1_V_ce0,
        batch_normalization_1_V_q0,
        batch_normalization_1_V_address1,
        batch_normalization_1_V_ce1,
        batch_normalization_1_V_q1,
        average_pooling1d_1_V_address0,
        average_pooling1d_1_V_ce0,
        average_pooling1d_1_V_we0,
        average_pooling1d_1_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] batch_normalization_1_V_address0;
output   batch_normalization_1_V_ce0;
input  [31:0] batch_normalization_1_V_q0;
output  [11:0] batch_normalization_1_V_address1;
output   batch_normalization_1_V_ce1;
input  [31:0] batch_normalization_1_V_q1;
output  [10:0] average_pooling1d_1_V_address0;
output   average_pooling1d_1_V_ce0;
output   average_pooling1d_1_V_we0;
output  [31:0] average_pooling1d_1_V_d0;

reg ap_idle;
reg batch_normalization_1_V_ce0;
reg batch_normalization_1_V_ce1;
reg average_pooling1d_1_V_ce0;
reg average_pooling1d_1_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_122_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] add_ln44_fu_210_p2;
reg   [10:0] add_ln44_reg_338;
wire   [63:0] zext_ln813_fu_194_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln813_9_fu_205_p1;
wire   [63:0] zext_ln45_fu_300_p1;
reg   [5:0] y_fu_54;
wire   [5:0] add_ln46_fu_216_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_y_load;
reg   [5:0] z_fu_58;
wire   [5:0] select_ln32_1_fu_160_p3;
reg   [5:0] ap_sig_allocacmp_z_load;
reg   [10:0] indvar_flatten162_fu_62;
wire   [10:0] add_ln32_fu_128_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten162_load;
wire   [0:0] icmp_ln35_fu_140_p2;
wire   [5:0] add_ln32_1_fu_154_p2;
wire   [5:0] select_ln32_fu_146_p3;
wire   [4:0] empty_459_fu_180_p1;
wire   [11:0] add_ln1_fu_184_p4;
wire   [11:0] or_ln40_fu_199_p2;
wire   [10:0] index_1_cast_fu_176_p1;
wire   [10:0] p_mid7_fu_168_p3;
wire   [31:0] add_ln813_15_fu_237_p2;
wire   [31:0] sub_ln1303_fu_251_p2;
wire   [30:0] lshr_ln1303_4_fu_257_p4;
wire   [31:0] zext_ln1303_fu_267_p1;
wire   [30:0] lshr_ln1303_5_fu_277_p4;
wire   [0:0] tmp_fu_243_p3;
wire   [31:0] sub_ln1303_2_fu_271_p2;
wire   [31:0] zext_ln1303_2_fu_287_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_122_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten162_fu_62 <= add_ln32_fu_128_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten162_fu_62 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_122_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_54 <= add_ln46_fu_216_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_54 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_122_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            z_fu_58 <= select_ln32_1_fu_160_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            z_fu_58 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_122_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln44_reg_338 <= add_ln44_fu_210_p2;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_122_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten162_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten162_load = indvar_flatten162_fu_62;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 6'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z_load = 6'd0;
    end else begin
        ap_sig_allocacmp_z_load = z_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        average_pooling1d_1_V_ce0 = 1'b1;
    end else begin
        average_pooling1d_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        average_pooling1d_1_V_we0 = 1'b1;
    end else begin
        average_pooling1d_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_normalization_1_V_ce0 = 1'b1;
    end else begin
        batch_normalization_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_normalization_1_V_ce1 = 1'b1;
    end else begin
        batch_normalization_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1_fu_184_p4 = {{{select_ln32_1_fu_160_p3}, {empty_459_fu_180_p1}}, {1'd0}};

assign add_ln32_1_fu_154_p2 = (ap_sig_allocacmp_z_load + 6'd1);

assign add_ln32_fu_128_p2 = (ap_sig_allocacmp_indvar_flatten162_load + 11'd1);

assign add_ln44_fu_210_p2 = (index_1_cast_fu_176_p1 + p_mid7_fu_168_p3);

assign add_ln46_fu_216_p2 = (select_ln32_fu_146_p3 + 6'd1);

assign add_ln813_15_fu_237_p2 = (batch_normalization_1_V_q0 + batch_normalization_1_V_q1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign average_pooling1d_1_V_address0 = zext_ln45_fu_300_p1;

assign average_pooling1d_1_V_d0 = ((tmp_fu_243_p3[0:0] == 1'b1) ? sub_ln1303_2_fu_271_p2 : zext_ln1303_2_fu_287_p1);

assign batch_normalization_1_V_address0 = zext_ln813_9_fu_205_p1;

assign batch_normalization_1_V_address1 = zext_ln813_fu_194_p1;

assign empty_459_fu_180_p1 = select_ln32_fu_146_p3[4:0];

assign icmp_ln32_fu_122_p2 = ((ap_sig_allocacmp_indvar_flatten162_load == 11'd1536) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_140_p2 = ((ap_sig_allocacmp_y_load == 6'd32) ? 1'b1 : 1'b0);

assign index_1_cast_fu_176_p1 = select_ln32_fu_146_p3;

assign lshr_ln1303_4_fu_257_p4 = {{sub_ln1303_fu_251_p2[31:1]}};

assign lshr_ln1303_5_fu_277_p4 = {{add_ln813_15_fu_237_p2[31:1]}};

assign or_ln40_fu_199_p2 = (12'd1 | add_ln1_fu_184_p4);

assign p_mid7_fu_168_p3 = {{select_ln32_1_fu_160_p3}, {5'd0}};

assign select_ln32_1_fu_160_p3 = ((icmp_ln35_fu_140_p2[0:0] == 1'b1) ? add_ln32_1_fu_154_p2 : ap_sig_allocacmp_z_load);

assign select_ln32_fu_146_p3 = ((icmp_ln35_fu_140_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_y_load);

assign sub_ln1303_2_fu_271_p2 = (32'd0 - zext_ln1303_fu_267_p1);

assign sub_ln1303_fu_251_p2 = (32'd0 - add_ln813_15_fu_237_p2);

assign tmp_fu_243_p3 = add_ln813_15_fu_237_p2[32'd31];

assign zext_ln1303_2_fu_287_p1 = lshr_ln1303_5_fu_277_p4;

assign zext_ln1303_fu_267_p1 = lshr_ln1303_4_fu_257_p4;

assign zext_ln45_fu_300_p1 = add_ln44_reg_338;

assign zext_ln813_9_fu_205_p1 = or_ln40_fu_199_p2;

assign zext_ln813_fu_194_p1 = add_ln1_fu_184_p4;

endmodule //CNN_CNN_Pipeline_loop_for_channel_pool_1_loop_for_weight_pool_1
