// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OutPadConv2_V_address0,
        OutPadConv2_V_ce0,
        OutPadConv2_V_we0,
        OutPadConv2_V_d0,
        average_pooling1d_1_V_address0,
        average_pooling1d_1_V_ce0,
        average_pooling1d_1_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] OutPadConv2_V_address0;
output   OutPadConv2_V_ce0;
output   OutPadConv2_V_we0;
output  [31:0] OutPadConv2_V_d0;
output  [10:0] average_pooling1d_1_V_address0;
output   average_pooling1d_1_V_ce0;
input  [31:0] average_pooling1d_1_V_q0;

reg ap_idle;
reg OutPadConv2_V_ce0;
reg OutPadConv2_V_we0;
reg average_pooling1d_1_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln105_fu_114_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln108_fu_194_p2;
reg   [0:0] icmp_ln108_reg_305;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln108_1_fu_200_p2;
reg   [0:0] icmp_ln108_1_reg_310;
wire   [10:0] add_ln108_fu_216_p2;
reg   [10:0] add_ln108_reg_315;
wire   [63:0] zext_ln108_2_fu_238_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln108_1_fu_268_p1;
reg   [5:0] n_fu_58;
wire   [5:0] add_ln107_fu_243_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_n_load;
reg   [5:0] c_fu_62;
wire   [5:0] select_ln105_1_fu_152_p3;
reg   [5:0] ap_sig_allocacmp_c_load;
reg   [10:0] indvar_flatten172_fu_66;
wire   [10:0] add_ln105_fu_120_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten172_load;
wire   [0:0] icmp_ln107_fu_132_p2;
wire   [5:0] add_ln105_1_fu_146_p2;
wire   [5:0] select_ln105_fu_138_p3;
wire   [3:0] tmp_fu_184_p4;
wire   [8:0] p_shl33_mid2_fu_168_p3;
wire   [8:0] n_5_cast61_fu_176_p1;
wire   [8:0] add_ln108_1_fu_206_p2;
wire   [10:0] zext_ln108_fu_212_p1;
wire   [10:0] p_mid8_fu_160_p3;
wire   [6:0] n_5_cast_fu_180_p1;
wire   [6:0] add_ln108_3_fu_222_p2;
wire  signed [10:0] sext_ln108_fu_228_p1;
wire   [10:0] add_ln108_2_fu_232_p2;
wire   [0:0] or_ln108_fu_264_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_62 <= select_ln105_1_fu_152_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_62 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten172_fu_66 <= add_ln105_fu_120_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten172_fu_66 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln105_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_58 <= add_ln107_fu_243_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_58 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln105_fu_114_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln108_reg_315 <= add_ln108_fu_216_p2;
        icmp_ln108_1_reg_310 <= icmp_ln108_1_fu_200_p2;
        icmp_ln108_reg_305 <= icmp_ln108_fu_194_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPadConv2_V_ce0 = 1'b1;
    end else begin
        OutPadConv2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPadConv2_V_we0 = 1'b1;
    end else begin
        OutPadConv2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln105_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 6'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_62;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten172_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten172_load = indvar_flatten172_fu_66;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_load = 6'd0;
    end else begin
        ap_sig_allocacmp_n_load = n_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        average_pooling1d_1_V_ce0 = 1'b1;
    end else begin
        average_pooling1d_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutPadConv2_V_address0 = zext_ln108_1_fu_268_p1;

assign OutPadConv2_V_d0 = ((or_ln108_fu_264_p2[0:0] == 1'b1) ? 32'd0 : average_pooling1d_1_V_q0);

assign add_ln105_1_fu_146_p2 = (ap_sig_allocacmp_c_load + 6'd1);

assign add_ln105_fu_120_p2 = (ap_sig_allocacmp_indvar_flatten172_load + 11'd1);

assign add_ln107_fu_243_p2 = (select_ln105_fu_138_p3 + 6'd1);

assign add_ln108_1_fu_206_p2 = (p_shl33_mid2_fu_168_p3 + n_5_cast61_fu_176_p1);

assign add_ln108_2_fu_232_p2 = ($signed(sext_ln108_fu_228_p1) + $signed(p_mid8_fu_160_p3));

assign add_ln108_3_fu_222_p2 = ($signed(n_5_cast_fu_180_p1) + $signed(7'd124));

assign add_ln108_fu_216_p2 = (zext_ln108_fu_212_p1 + p_mid8_fu_160_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign average_pooling1d_1_V_address0 = zext_ln108_2_fu_238_p1;

assign icmp_ln105_fu_114_p2 = ((ap_sig_allocacmp_indvar_flatten172_load == 11'd1920) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_132_p2 = ((ap_sig_allocacmp_n_load == 6'd40) ? 1'b1 : 1'b0);

assign icmp_ln108_1_fu_200_p2 = ((select_ln105_fu_138_p3 > 6'd35) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_194_p2 = ((tmp_fu_184_p4 == 4'd0) ? 1'b1 : 1'b0);

assign n_5_cast61_fu_176_p1 = select_ln105_fu_138_p3;

assign n_5_cast_fu_180_p1 = select_ln105_fu_138_p3;

assign or_ln108_fu_264_p2 = (icmp_ln108_reg_305 | icmp_ln108_1_reg_310);

assign p_mid8_fu_160_p3 = {{select_ln105_1_fu_152_p3}, {5'd0}};

assign p_shl33_mid2_fu_168_p3 = {{select_ln105_1_fu_152_p3}, {3'd0}};

assign select_ln105_1_fu_152_p3 = ((icmp_ln107_fu_132_p2[0:0] == 1'b1) ? add_ln105_1_fu_146_p2 : ap_sig_allocacmp_c_load);

assign select_ln105_fu_138_p3 = ((icmp_ln107_fu_132_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_n_load);

assign sext_ln108_fu_228_p1 = $signed(add_ln108_3_fu_222_p2);

assign tmp_fu_184_p4 = {{select_ln105_fu_138_p3[5:2]}};

assign zext_ln108_1_fu_268_p1 = add_ln108_reg_315;

assign zext_ln108_2_fu_238_p1 = add_ln108_2_fu_232_p2;

assign zext_ln108_fu_212_p1 = add_ln108_1_fu_206_p2;

endmodule //CNN_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2
