// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_channel_pool_0_loop_for_weight_pool_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        batch_normalization_V_address0,
        batch_normalization_V_ce0,
        batch_normalization_V_q0,
        batch_normalization_V_address1,
        batch_normalization_V_ce1,
        batch_normalization_V_q1,
        batch_normalization_V_address2,
        batch_normalization_V_ce2,
        batch_normalization_V_q2,
        batch_normalization_V_address3,
        batch_normalization_V_ce3,
        batch_normalization_V_q3,
        average_pooling1d_V_address0,
        average_pooling1d_V_ce0,
        average_pooling1d_V_we0,
        average_pooling1d_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] batch_normalization_V_address0;
output   batch_normalization_V_ce0;
input  [31:0] batch_normalization_V_q0;
output  [12:0] batch_normalization_V_address1;
output   batch_normalization_V_ce1;
input  [31:0] batch_normalization_V_q1;
output  [12:0] batch_normalization_V_address2;
output   batch_normalization_V_ce2;
input  [31:0] batch_normalization_V_q2;
output  [12:0] batch_normalization_V_address3;
output   batch_normalization_V_ce3;
input  [31:0] batch_normalization_V_q3;
output  [10:0] average_pooling1d_V_address0;
output   average_pooling1d_V_ce0;
output   average_pooling1d_V_we0;
output  [30:0] average_pooling1d_V_d0;

reg ap_idle;
reg batch_normalization_V_ce0;
reg batch_normalization_V_ce1;
reg batch_normalization_V_ce2;
reg batch_normalization_V_ce3;
reg average_pooling1d_V_ce0;
reg average_pooling1d_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln9_fu_156_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] add_ln21_fu_270_p2;
reg   [10:0] add_ln21_reg_420;
wire   [63:0] zext_ln813_9_fu_232_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln813_fu_243_p1;
wire   [63:0] zext_ln813_10_fu_254_p1;
wire   [63:0] zext_ln813_11_fu_265_p1;
wire   [63:0] zext_ln22_fu_372_p1;
reg   [6:0] y_fu_64;
wire   [6:0] add_ln23_fu_276_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_y_load;
reg   [5:0] z_fu_68;
wire   [5:0] select_ln9_1_fu_194_p3;
reg   [5:0] ap_sig_allocacmp_z_load;
reg   [11:0] indvar_flatten92_fu_72;
wire   [11:0] add_ln9_fu_162_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten92_load;
wire   [0:0] icmp_ln12_fu_174_p2;
wire   [5:0] add_ln9_1_fu_188_p2;
wire   [4:0] trunc_ln9_fu_202_p1;
wire   [6:0] select_ln9_fu_180_p3;
wire   [5:0] empty_460_fu_218_p1;
wire   [12:0] add_ln_fu_222_p4;
wire   [12:0] or_ln17_fu_237_p2;
wire   [12:0] or_ln17_1_fu_248_p2;
wire   [12:0] or_ln17_2_fu_259_p2;
wire   [10:0] index_cast45_fu_214_p1;
wire   [10:0] p_mid3_fu_206_p3;
wire   [31:0] add_ln813_21_fu_303_p2;
wire   [31:0] add_ln813_fu_297_p2;
wire   [31:0] add_ln813_14_fu_309_p2;
wire   [31:0] sub_ln1303_fu_323_p2;
wire   [29:0] trunc_ln1303_s_fu_329_p4;
wire   [30:0] zext_ln1303_1_fu_339_p1;
wire   [29:0] trunc_ln1303_1_fu_349_p4;
wire   [0:0] tmp_fu_315_p3;
wire   [30:0] sub_ln1303_1_fu_343_p2;
wire   [30:0] zext_ln1303_2_fu_359_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln9_fu_156_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten92_fu_72 <= add_ln9_fu_162_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten92_fu_72 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln9_fu_156_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_64 <= add_ln23_fu_276_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_64 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln9_fu_156_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            z_fu_68 <= select_ln9_1_fu_194_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            z_fu_68 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln9_fu_156_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln21_reg_420 <= add_ln21_fu_270_p2;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_156_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten92_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten92_load = indvar_flatten92_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_load = 7'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_z_load = 6'd0;
    end else begin
        ap_sig_allocacmp_z_load = z_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        average_pooling1d_V_ce0 = 1'b1;
    end else begin
        average_pooling1d_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        average_pooling1d_V_we0 = 1'b1;
    end else begin
        average_pooling1d_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_normalization_V_ce0 = 1'b1;
    end else begin
        batch_normalization_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_normalization_V_ce1 = 1'b1;
    end else begin
        batch_normalization_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_normalization_V_ce2 = 1'b1;
    end else begin
        batch_normalization_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_normalization_V_ce3 = 1'b1;
    end else begin
        batch_normalization_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_270_p2 = (index_cast45_fu_214_p1 + p_mid3_fu_206_p3);

assign add_ln23_fu_276_p2 = (select_ln9_fu_180_p3 + 7'd1);

assign add_ln813_14_fu_309_p2 = (add_ln813_21_fu_303_p2 + add_ln813_fu_297_p2);

assign add_ln813_21_fu_303_p2 = (batch_normalization_V_q2 + batch_normalization_V_q0);

assign add_ln813_fu_297_p2 = (batch_normalization_V_q3 + batch_normalization_V_q1);

assign add_ln9_1_fu_188_p2 = (ap_sig_allocacmp_z_load + 6'd1);

assign add_ln9_fu_162_p2 = (ap_sig_allocacmp_indvar_flatten92_load + 12'd1);

assign add_ln_fu_222_p4 = {{{trunc_ln9_fu_202_p1}, {empty_460_fu_218_p1}}, {2'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign average_pooling1d_V_address0 = zext_ln22_fu_372_p1;

assign average_pooling1d_V_d0 = ((tmp_fu_315_p3[0:0] == 1'b1) ? sub_ln1303_1_fu_343_p2 : zext_ln1303_2_fu_359_p1);

assign batch_normalization_V_address0 = zext_ln813_11_fu_265_p1;

assign batch_normalization_V_address1 = zext_ln813_10_fu_254_p1;

assign batch_normalization_V_address2 = zext_ln813_fu_243_p1;

assign batch_normalization_V_address3 = zext_ln813_9_fu_232_p1;

assign empty_460_fu_218_p1 = select_ln9_fu_180_p3[5:0];

assign icmp_ln12_fu_174_p2 = ((ap_sig_allocacmp_y_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_156_p2 = ((ap_sig_allocacmp_indvar_flatten92_load == 12'd2048) ? 1'b1 : 1'b0);

assign index_cast45_fu_214_p1 = select_ln9_fu_180_p3;

assign or_ln17_1_fu_248_p2 = (13'd2 | add_ln_fu_222_p4);

assign or_ln17_2_fu_259_p2 = (13'd3 | add_ln_fu_222_p4);

assign or_ln17_fu_237_p2 = (13'd1 | add_ln_fu_222_p4);

assign p_mid3_fu_206_p3 = {{trunc_ln9_fu_202_p1}, {6'd0}};

assign select_ln9_1_fu_194_p3 = ((icmp_ln12_fu_174_p2[0:0] == 1'b1) ? add_ln9_1_fu_188_p2 : ap_sig_allocacmp_z_load);

assign select_ln9_fu_180_p3 = ((icmp_ln12_fu_174_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_y_load);

assign sub_ln1303_1_fu_343_p2 = (31'd0 - zext_ln1303_1_fu_339_p1);

assign sub_ln1303_fu_323_p2 = (32'd0 - add_ln813_14_fu_309_p2);

assign tmp_fu_315_p3 = add_ln813_14_fu_309_p2[32'd31];

assign trunc_ln1303_1_fu_349_p4 = {{add_ln813_14_fu_309_p2[31:2]}};

assign trunc_ln1303_s_fu_329_p4 = {{sub_ln1303_fu_323_p2[31:2]}};

assign trunc_ln9_fu_202_p1 = select_ln9_1_fu_194_p3[4:0];

assign zext_ln1303_1_fu_339_p1 = trunc_ln1303_s_fu_329_p4;

assign zext_ln1303_2_fu_359_p1 = trunc_ln1303_1_fu_349_p4;

assign zext_ln22_fu_372_p1 = add_ln21_reg_420;

assign zext_ln813_10_fu_254_p1 = or_ln17_1_fu_248_p2;

assign zext_ln813_11_fu_265_p1 = or_ln17_2_fu_259_p2;

assign zext_ln813_9_fu_232_p1 = add_ln_fu_222_p4;

assign zext_ln813_fu_243_p1 = or_ln17_fu_237_p2;

endmodule //CNN_CNN_Pipeline_loop_for_channel_pool_0_loop_for_weight_pool_0
