// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_fc_1_loop_for_fa_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        select_ln67,
        sext_ln67_2,
        OutPadConv1_V_address0,
        OutPadConv1_V_ce0,
        OutPadConv1_V_q0,
        s_V_6_out,
        s_V_6_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [6:0] select_ln67;
input  [61:0] sext_ln67_2;
output  [11:0] OutPadConv1_V_address0;
output   OutPadConv1_V_ce0;
input  [30:0] OutPadConv1_V_q0;
output  [31:0] s_V_6_out;
output   s_V_6_out_ap_vld;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg OutPadConv1_V_ce0;
reg s_V_6_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln72_fu_226_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_R;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln72_reg_486;
reg   [0:0] icmp_ln72_reg_486_pp0_iter1_reg;
reg   [0:0] icmp_ln72_reg_486_pp0_iter2_reg;
reg   [0:0] icmp_ln72_reg_486_pp0_iter3_reg;
reg   [0:0] icmp_ln72_reg_486_pp0_iter4_reg;
reg   [0:0] icmp_ln72_reg_486_pp0_iter5_reg;
reg   [0:0] icmp_ln72_reg_486_pp0_iter6_reg;
reg   [0:0] icmp_ln72_reg_486_pp0_iter7_reg;
wire   [11:0] add_ln75_1_fu_355_p2;
reg   [11:0] add_ln75_1_reg_490;
reg   [11:0] add_ln75_1_reg_490_pp0_iter1_reg;
reg   [11:0] add_ln75_1_reg_490_pp0_iter2_reg;
reg   [11:0] add_ln75_1_reg_490_pp0_iter3_reg;
reg   [11:0] add_ln75_1_reg_490_pp0_iter4_reg;
reg   [11:0] add_ln75_1_reg_490_pp0_iter5_reg;
reg   [11:0] add_ln75_1_reg_490_pp0_iter6_reg;
reg   [11:0] add_ln75_1_reg_490_pp0_iter7_reg;
reg   [63:0] gmem1_addr_reg_495;
reg  signed [31:0] r_V_reg_501;
wire   [63:0] zext_ln1271_fu_404_p1;
wire  signed [63:0] sext_ln1271_fu_373_p1;
reg   [31:0] lhs_fu_88;
wire    ap_loop_init;
reg   [3:0] j_fu_92;
wire   [3:0] add_ln74_fu_383_p2;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [5:0] k_fu_96;
wire   [5:0] select_ln72_3_fu_329_p3;
reg   [5:0] ap_sig_allocacmp_k_2;
reg   [8:0] indvar_flatten109_fu_100;
wire   [8:0] add_ln72_fu_232_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten109_load;
reg    ap_block_pp0_stage0_01001;
wire   [4:0] empty_fu_182_p1;
wire   [7:0] p_shl4_fu_186_p3;
wire   [10:0] p_shl5_fu_202_p3;
wire   [11:0] zext_ln74_fu_210_p1;
wire   [11:0] p_shl25_cast_fu_198_p1;
wire   [8:0] p_shl25_cast56_fu_194_p1;
wire   [8:0] zext_ln72_fu_178_p1;
wire   [0:0] icmp_ln74_fu_241_p2;
wire   [5:0] add_ln72_1_fu_255_p2;
wire   [4:0] empty_457_fu_265_p1;
wire   [7:0] p_shl25_mid1_fu_269_p3;
wire   [10:0] p_shl23_mid1_fu_285_p3;
wire   [11:0] zext_ln74_1_fu_293_p1;
wire   [11:0] p_shl25_cast_mid1_fu_281_p1;
wire   [11:0] add_ln75_3_fu_297_p2;
wire   [11:0] add_ln75_fu_214_p2;
wire   [8:0] p_shl25_cast56_mid1_fu_277_p1;
wire   [8:0] zext_ln72_1_fu_261_p1;
wire   [8:0] add_ln1271_3_fu_311_p2;
wire   [8:0] add_ln1271_fu_220_p2;
wire   [8:0] select_ln72_2_fu_317_p3;
wire   [3:0] select_ln72_fu_247_p3;
wire   [6:0] j_2_cast_fu_341_p1;
wire   [6:0] add_ln75_2_fu_345_p2;
wire   [11:0] zext_ln75_fu_351_p1;
wire   [11:0] select_ln72_1_fu_303_p3;
wire   [62:0] j_2_cast58_fu_337_p1;
wire  signed [62:0] sext_ln67_2_cast_fu_148_p1;
wire   [62:0] add_ln1271_4_fu_361_p2;
wire   [62:0] zext_ln72_2_fu_325_p1;
wire   [62:0] add_ln1271_1_fu_367_p2;
wire   [47:0] lhs_2_fu_424_p3;
wire   [47:0] r_V_2_fu_418_p2;
wire   [47:0] ret_V_fu_432_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_mul_31s_32s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_31s_32s_48_1_1_U82(
    .din0(OutPadConv1_V_q0),
    .din1(r_V_reg_501),
    .dout(r_V_2_fu_418_p2)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln72_fu_226_p2 == 1'd0))) begin
            indvar_flatten109_fu_100 <= add_ln72_fu_232_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten109_fu_100 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln72_fu_226_p2 == 1'd0))) begin
            j_fu_92 <= add_ln74_fu_383_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_92 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln72_fu_226_p2 == 1'd0))) begin
            k_fu_96 <= select_ln72_3_fu_329_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_96 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            lhs_fu_88 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter9 == 1'b1)) begin
            lhs_fu_88 <= {{ret_V_fu_432_p2[47:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln72_fu_226_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln75_1_reg_490 <= add_ln75_1_fu_355_p2;
        gmem1_addr_reg_495 <= sext_ln1271_fu_373_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln75_1_reg_490_pp0_iter1_reg <= add_ln75_1_reg_490;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln72_reg_486 <= icmp_ln72_fu_226_p2;
        icmp_ln72_reg_486_pp0_iter1_reg <= icmp_ln72_reg_486;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln75_1_reg_490_pp0_iter2_reg <= add_ln75_1_reg_490_pp0_iter1_reg;
        add_ln75_1_reg_490_pp0_iter3_reg <= add_ln75_1_reg_490_pp0_iter2_reg;
        add_ln75_1_reg_490_pp0_iter4_reg <= add_ln75_1_reg_490_pp0_iter3_reg;
        add_ln75_1_reg_490_pp0_iter5_reg <= add_ln75_1_reg_490_pp0_iter4_reg;
        add_ln75_1_reg_490_pp0_iter6_reg <= add_ln75_1_reg_490_pp0_iter5_reg;
        add_ln75_1_reg_490_pp0_iter7_reg <= add_ln75_1_reg_490_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln72_reg_486_pp0_iter2_reg <= icmp_ln72_reg_486_pp0_iter1_reg;
        icmp_ln72_reg_486_pp0_iter3_reg <= icmp_ln72_reg_486_pp0_iter2_reg;
        icmp_ln72_reg_486_pp0_iter4_reg <= icmp_ln72_reg_486_pp0_iter3_reg;
        icmp_ln72_reg_486_pp0_iter5_reg <= icmp_ln72_reg_486_pp0_iter4_reg;
        icmp_ln72_reg_486_pp0_iter6_reg <= icmp_ln72_reg_486_pp0_iter5_reg;
        icmp_ln72_reg_486_pp0_iter7_reg <= icmp_ln72_reg_486_pp0_iter6_reg;
        r_V_reg_501 <= m_axi_gmem1_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        OutPadConv1_V_ce0 = 1'b1;
    end else begin
        OutPadConv1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln72_fu_226_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten109_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten109_load = indvar_flatten109_fu_100;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_92;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_k_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_k_2 = k_fu_96;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln72_reg_486_pp0_iter7_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        s_V_6_out_ap_vld = 1'b1;
    end else begin
        s_V_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutPadConv1_V_address0 = zext_ln1271_fu_404_p1;

assign add_ln1271_1_fu_367_p2 = (add_ln1271_4_fu_361_p2 + zext_ln72_2_fu_325_p1);

assign add_ln1271_3_fu_311_p2 = (p_shl25_cast56_mid1_fu_277_p1 + zext_ln72_1_fu_261_p1);

assign add_ln1271_4_fu_361_p2 = ($signed(j_2_cast58_fu_337_p1) + $signed(sext_ln67_2_cast_fu_148_p1));

assign add_ln1271_fu_220_p2 = (p_shl25_cast56_fu_194_p1 + zext_ln72_fu_178_p1);

assign add_ln72_1_fu_255_p2 = (ap_sig_allocacmp_k_2 + 6'd1);

assign add_ln72_fu_232_p2 = (ap_sig_allocacmp_indvar_flatten109_load + 9'd1);

assign add_ln74_fu_383_p2 = (select_ln72_fu_247_p3 + 4'd1);

assign add_ln75_1_fu_355_p2 = (zext_ln75_fu_351_p1 + select_ln72_1_fu_303_p3);

assign add_ln75_2_fu_345_p2 = (select_ln67 + j_2_cast_fu_341_p1);

assign add_ln75_3_fu_297_p2 = (zext_ln74_1_fu_293_p1 + p_shl25_cast_mid1_fu_281_p1);

assign add_ln75_fu_214_p2 = (zext_ln74_fu_210_p1 + p_shl25_cast_fu_198_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((m_axi_gmem1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((m_axi_gmem1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_457_fu_265_p1 = add_ln72_1_fu_255_p2[4:0];

assign empty_fu_182_p1 = ap_sig_allocacmp_k_2[4:0];

assign icmp_ln72_fu_226_p2 = ((ap_sig_allocacmp_indvar_flatten109_load == 9'd288) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_241_p2 = ((ap_sig_allocacmp_j_load == 4'd9) ? 1'b1 : 1'b0);

assign j_2_cast58_fu_337_p1 = select_ln72_fu_247_p3;

assign j_2_cast_fu_341_p1 = select_ln72_fu_247_p3;

assign lhs_2_fu_424_p3 = {{lhs_fu_88}, {16'd0}};

assign m_axi_gmem1_ARADDR = gmem1_addr_reg_495;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd1;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign p_shl23_mid1_fu_285_p3 = {{empty_457_fu_265_p1}, {6'd0}};

assign p_shl25_cast56_fu_194_p1 = p_shl4_fu_186_p3;

assign p_shl25_cast56_mid1_fu_277_p1 = p_shl25_mid1_fu_269_p3;

assign p_shl25_cast_fu_198_p1 = p_shl4_fu_186_p3;

assign p_shl25_cast_mid1_fu_281_p1 = p_shl25_mid1_fu_269_p3;

assign p_shl25_mid1_fu_269_p3 = {{empty_457_fu_265_p1}, {3'd0}};

assign p_shl4_fu_186_p3 = {{empty_fu_182_p1}, {3'd0}};

assign p_shl5_fu_202_p3 = {{empty_fu_182_p1}, {6'd0}};

assign ret_V_fu_432_p2 = (lhs_2_fu_424_p3 + r_V_2_fu_418_p2);

assign s_V_6_out = lhs_fu_88;

assign select_ln72_1_fu_303_p3 = ((icmp_ln74_fu_241_p2[0:0] == 1'b1) ? add_ln75_3_fu_297_p2 : add_ln75_fu_214_p2);

assign select_ln72_2_fu_317_p3 = ((icmp_ln74_fu_241_p2[0:0] == 1'b1) ? add_ln1271_3_fu_311_p2 : add_ln1271_fu_220_p2);

assign select_ln72_3_fu_329_p3 = ((icmp_ln74_fu_241_p2[0:0] == 1'b1) ? add_ln72_1_fu_255_p2 : ap_sig_allocacmp_k_2);

assign select_ln72_fu_247_p3 = ((icmp_ln74_fu_241_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign sext_ln1271_fu_373_p1 = $signed(add_ln1271_1_fu_367_p2);

assign sext_ln67_2_cast_fu_148_p1 = $signed(sext_ln67_2);

assign zext_ln1271_fu_404_p1 = add_ln75_1_reg_490_pp0_iter7_reg;

assign zext_ln72_1_fu_261_p1 = add_ln72_1_fu_255_p2;

assign zext_ln72_2_fu_325_p1 = select_ln72_2_fu_317_p3;

assign zext_ln72_fu_178_p1 = ap_sig_allocacmp_k_2;

assign zext_ln74_1_fu_293_p1 = p_shl23_mid1_fu_285_p3;

assign zext_ln74_fu_210_p1 = p_shl5_fu_202_p3;

assign zext_ln75_fu_351_p1 = add_ln75_2_fu_345_p2;

endmodule //CNN_CNN_Pipeline_loop_for_fc_1_loop_for_fa_1
