// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_VITIS_LOOP_75_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        straight_attention_V_address0,
        straight_attention_V_ce0,
        straight_attention_V_q0,
        straight_attention_V_address1,
        straight_attention_V_ce1,
        straight_attention_V_q1,
        straight_attention_V_address2,
        straight_attention_V_ce2,
        straight_attention_V_q2,
        straight_attention_V_address3,
        straight_attention_V_ce3,
        straight_attention_V_q3,
        straight_attention_V_address4,
        straight_attention_V_ce4,
        straight_attention_V_q4,
        straight_attention_V_address5,
        straight_attention_V_ce5,
        straight_attention_V_q5,
        straight_attention_V_address6,
        straight_attention_V_ce6,
        straight_attention_V_q6,
        straight_attention_V_address7,
        straight_attention_V_ce7,
        straight_attention_V_q7,
        straight_attention_V_address8,
        straight_attention_V_ce8,
        straight_attention_V_q8,
        straight_attention_V_address9,
        straight_attention_V_ce9,
        straight_attention_V_q9,
        straight_attention_V_address10,
        straight_attention_V_ce10,
        straight_attention_V_q10,
        straight_attention_V_address11,
        straight_attention_V_ce11,
        straight_attention_V_q11,
        straight_attention_V_address12,
        straight_attention_V_ce12,
        straight_attention_V_q12,
        straight_attention_V_address13,
        straight_attention_V_ce13,
        straight_attention_V_q13,
        straight_attention_V_address14,
        straight_attention_V_ce14,
        straight_attention_V_q14,
        straight_attention_V_address15,
        straight_attention_V_ce15,
        straight_attention_V_q15,
        global_average_pooling1d_V_address0,
        global_average_pooling1d_V_ce0,
        global_average_pooling1d_V_we0,
        global_average_pooling1d_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] straight_attention_V_address0;
output   straight_attention_V_ce0;
input  [31:0] straight_attention_V_q0;
output  [9:0] straight_attention_V_address1;
output   straight_attention_V_ce1;
input  [31:0] straight_attention_V_q1;
output  [9:0] straight_attention_V_address2;
output   straight_attention_V_ce2;
input  [31:0] straight_attention_V_q2;
output  [9:0] straight_attention_V_address3;
output   straight_attention_V_ce3;
input  [31:0] straight_attention_V_q3;
output  [9:0] straight_attention_V_address4;
output   straight_attention_V_ce4;
input  [31:0] straight_attention_V_q4;
output  [9:0] straight_attention_V_address5;
output   straight_attention_V_ce5;
input  [31:0] straight_attention_V_q5;
output  [9:0] straight_attention_V_address6;
output   straight_attention_V_ce6;
input  [31:0] straight_attention_V_q6;
output  [9:0] straight_attention_V_address7;
output   straight_attention_V_ce7;
input  [31:0] straight_attention_V_q7;
output  [9:0] straight_attention_V_address8;
output   straight_attention_V_ce8;
input  [31:0] straight_attention_V_q8;
output  [9:0] straight_attention_V_address9;
output   straight_attention_V_ce9;
input  [31:0] straight_attention_V_q9;
output  [9:0] straight_attention_V_address10;
output   straight_attention_V_ce10;
input  [31:0] straight_attention_V_q10;
output  [9:0] straight_attention_V_address11;
output   straight_attention_V_ce11;
input  [31:0] straight_attention_V_q11;
output  [9:0] straight_attention_V_address12;
output   straight_attention_V_ce12;
input  [31:0] straight_attention_V_q12;
output  [9:0] straight_attention_V_address13;
output   straight_attention_V_ce13;
input  [31:0] straight_attention_V_q13;
output  [9:0] straight_attention_V_address14;
output   straight_attention_V_ce14;
input  [31:0] straight_attention_V_q14;
output  [9:0] straight_attention_V_address15;
output   straight_attention_V_ce15;
input  [31:0] straight_attention_V_q15;
output  [5:0] global_average_pooling1d_V_address0;
output   global_average_pooling1d_V_ce0;
output   global_average_pooling1d_V_we0;
output  [31:0] global_average_pooling1d_V_d0;

reg ap_idle;
reg straight_attention_V_ce0;
reg straight_attention_V_ce1;
reg straight_attention_V_ce2;
reg straight_attention_V_ce3;
reg straight_attention_V_ce4;
reg straight_attention_V_ce5;
reg straight_attention_V_ce6;
reg straight_attention_V_ce7;
reg straight_attention_V_ce8;
reg straight_attention_V_ce9;
reg straight_attention_V_ce10;
reg straight_attention_V_ce11;
reg straight_attention_V_ce12;
reg straight_attention_V_ce13;
reg straight_attention_V_ce14;
reg straight_attention_V_ce15;
reg global_average_pooling1d_V_ce0;
reg global_average_pooling1d_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln75_fu_292_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] i_reg_1600;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] i_reg_1600_pp0_iter1_reg;
wire   [31:0] add_ln813_30_fu_1583_p2;
reg   [31:0] add_ln813_30_reg_1689;
wire   [63:0] zext_ln78_fu_316_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln78_1_fu_327_p1;
wire   [63:0] zext_ln78_2_fu_338_p1;
wire   [63:0] zext_ln78_3_fu_349_p1;
wire   [63:0] zext_ln78_4_fu_360_p1;
wire   [63:0] zext_ln78_5_fu_371_p1;
wire   [63:0] zext_ln78_6_fu_382_p1;
wire   [63:0] zext_ln78_7_fu_393_p1;
wire   [63:0] zext_ln78_8_fu_404_p1;
wire   [63:0] zext_ln78_9_fu_415_p1;
wire   [63:0] zext_ln78_10_fu_426_p1;
wire   [63:0] zext_ln78_11_fu_437_p1;
wire   [63:0] zext_ln78_12_fu_448_p1;
wire   [63:0] zext_ln78_13_fu_459_p1;
wire   [63:0] zext_ln78_14_fu_470_p1;
wire   [63:0] zext_ln78_15_fu_481_p1;
wire   [63:0] i_9_cast116_fu_1589_p1;
reg   [6:0] hs_fu_74;
wire   [6:0] add_ln75_3_fu_298_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i;
wire   [5:0] empty_461_fu_304_p1;
wire   [9:0] tmp_s_fu_308_p3;
wire   [9:0] or_ln78_fu_321_p2;
wire   [9:0] or_ln78_1_fu_332_p2;
wire   [9:0] or_ln78_2_fu_343_p2;
wire   [9:0] or_ln78_3_fu_354_p2;
wire   [9:0] or_ln78_4_fu_365_p2;
wire   [9:0] or_ln78_5_fu_376_p2;
wire   [9:0] or_ln78_6_fu_387_p2;
wire   [9:0] or_ln78_7_fu_398_p2;
wire   [9:0] or_ln78_8_fu_409_p2;
wire   [9:0] or_ln78_9_fu_420_p2;
wire   [9:0] or_ln78_10_fu_431_p2;
wire   [9:0] or_ln78_11_fu_442_p2;
wire   [9:0] or_ln78_12_fu_453_p2;
wire   [9:0] or_ln78_13_fu_464_p2;
wire   [9:0] or_ln78_14_fu_475_p2;
wire   [31:0] sub_ln1303_fu_499_p2;
wire   [27:0] trunc_ln1303_s_fu_505_p4;
wire   [28:0] zext_ln1303_fu_515_p1;
wire   [27:0] trunc_ln1303_2_fu_525_p4;
wire   [0:0] tmp_fu_491_p3;
wire   [28:0] sub_ln1303_3_fu_519_p2;
wire   [28:0] zext_ln1303_3_fu_535_p1;
wire   [28:0] select_ln1303_fu_539_p3;
wire   [31:0] sub_ln1303_4_fu_559_p2;
wire   [27:0] trunc_ln1303_3_fu_565_p4;
wire   [28:0] zext_ln1303_4_fu_575_p1;
wire   [27:0] trunc_ln1303_4_fu_585_p4;
wire   [0:0] tmp_61_fu_551_p3;
wire   [28:0] sub_ln1303_5_fu_579_p2;
wire   [28:0] zext_ln1303_5_fu_595_p1;
wire   [28:0] select_ln1303_1_fu_599_p3;
wire   [31:0] sub_ln1303_6_fu_619_p2;
wire   [27:0] trunc_ln1303_5_fu_625_p4;
wire   [28:0] zext_ln1303_6_fu_635_p1;
wire   [27:0] trunc_ln1303_6_fu_645_p4;
wire   [0:0] tmp_62_fu_611_p3;
wire   [28:0] sub_ln1303_7_fu_639_p2;
wire   [28:0] zext_ln1303_7_fu_655_p1;
wire   [28:0] select_ln1303_2_fu_659_p3;
wire   [31:0] sub_ln1303_8_fu_679_p2;
wire   [27:0] trunc_ln1303_7_fu_685_p4;
wire   [28:0] zext_ln1303_8_fu_695_p1;
wire   [27:0] trunc_ln1303_8_fu_705_p4;
wire   [0:0] tmp_63_fu_671_p3;
wire   [28:0] sub_ln1303_9_fu_699_p2;
wire   [28:0] zext_ln1303_9_fu_715_p1;
wire   [28:0] select_ln1303_3_fu_719_p3;
wire   [31:0] sub_ln1303_10_fu_739_p2;
wire   [27:0] trunc_ln1303_9_fu_745_p4;
wire   [28:0] zext_ln1303_10_fu_755_p1;
wire   [27:0] trunc_ln1303_10_fu_765_p4;
wire   [0:0] tmp_64_fu_731_p3;
wire   [28:0] sub_ln1303_11_fu_759_p2;
wire   [28:0] zext_ln1303_11_fu_775_p1;
wire   [28:0] select_ln1303_4_fu_779_p3;
wire   [31:0] sub_ln1303_12_fu_799_p2;
wire   [27:0] trunc_ln1303_11_fu_805_p4;
wire   [28:0] zext_ln1303_12_fu_815_p1;
wire   [27:0] trunc_ln1303_12_fu_825_p4;
wire   [0:0] tmp_65_fu_791_p3;
wire   [28:0] sub_ln1303_13_fu_819_p2;
wire   [28:0] zext_ln1303_13_fu_835_p1;
wire   [28:0] select_ln1303_5_fu_839_p3;
wire   [31:0] sub_ln1303_14_fu_859_p2;
wire   [27:0] trunc_ln1303_13_fu_865_p4;
wire   [28:0] zext_ln1303_14_fu_875_p1;
wire   [27:0] trunc_ln1303_14_fu_885_p4;
wire   [0:0] tmp_66_fu_851_p3;
wire   [28:0] sub_ln1303_15_fu_879_p2;
wire   [28:0] zext_ln1303_15_fu_895_p1;
wire   [28:0] select_ln1303_6_fu_899_p3;
wire   [31:0] sub_ln1303_16_fu_919_p2;
wire   [27:0] trunc_ln1303_15_fu_925_p4;
wire   [28:0] zext_ln1303_16_fu_935_p1;
wire   [27:0] trunc_ln1303_16_fu_945_p4;
wire   [0:0] tmp_67_fu_911_p3;
wire   [28:0] sub_ln1303_17_fu_939_p2;
wire   [28:0] zext_ln1303_17_fu_955_p1;
wire   [28:0] select_ln1303_7_fu_959_p3;
wire   [31:0] sub_ln1303_18_fu_979_p2;
wire   [27:0] trunc_ln1303_17_fu_985_p4;
wire   [28:0] zext_ln1303_18_fu_995_p1;
wire   [27:0] trunc_ln1303_18_fu_1005_p4;
wire   [0:0] tmp_68_fu_971_p3;
wire   [28:0] sub_ln1303_19_fu_999_p2;
wire   [28:0] zext_ln1303_19_fu_1015_p1;
wire   [28:0] select_ln1303_8_fu_1019_p3;
wire   [31:0] sub_ln1303_20_fu_1039_p2;
wire   [27:0] trunc_ln1303_19_fu_1045_p4;
wire   [28:0] zext_ln1303_20_fu_1055_p1;
wire   [27:0] trunc_ln1303_20_fu_1065_p4;
wire   [0:0] tmp_69_fu_1031_p3;
wire   [28:0] sub_ln1303_21_fu_1059_p2;
wire   [28:0] zext_ln1303_21_fu_1075_p1;
wire   [28:0] select_ln1303_9_fu_1079_p3;
wire   [31:0] sub_ln1303_22_fu_1099_p2;
wire   [27:0] trunc_ln1303_21_fu_1105_p4;
wire   [28:0] zext_ln1303_22_fu_1115_p1;
wire   [27:0] trunc_ln1303_22_fu_1125_p4;
wire   [0:0] tmp_70_fu_1091_p3;
wire   [28:0] sub_ln1303_23_fu_1119_p2;
wire   [28:0] zext_ln1303_23_fu_1135_p1;
wire   [28:0] select_ln1303_10_fu_1139_p3;
wire   [31:0] sub_ln1303_24_fu_1159_p2;
wire   [27:0] trunc_ln1303_23_fu_1165_p4;
wire   [28:0] zext_ln1303_24_fu_1175_p1;
wire   [27:0] trunc_ln1303_24_fu_1185_p4;
wire   [0:0] tmp_71_fu_1151_p3;
wire   [28:0] sub_ln1303_25_fu_1179_p2;
wire   [28:0] zext_ln1303_25_fu_1195_p1;
wire   [28:0] select_ln1303_11_fu_1199_p3;
wire   [31:0] sub_ln1303_26_fu_1219_p2;
wire   [27:0] trunc_ln1303_25_fu_1225_p4;
wire   [28:0] zext_ln1303_26_fu_1235_p1;
wire   [27:0] trunc_ln1303_26_fu_1245_p4;
wire   [0:0] tmp_72_fu_1211_p3;
wire   [28:0] sub_ln1303_27_fu_1239_p2;
wire   [28:0] zext_ln1303_27_fu_1255_p1;
wire   [28:0] select_ln1303_12_fu_1259_p3;
wire   [31:0] sub_ln1303_28_fu_1279_p2;
wire   [27:0] trunc_ln1303_27_fu_1285_p4;
wire   [28:0] zext_ln1303_28_fu_1295_p1;
wire   [27:0] trunc_ln1303_28_fu_1305_p4;
wire   [0:0] tmp_73_fu_1271_p3;
wire   [28:0] sub_ln1303_29_fu_1299_p2;
wire   [28:0] zext_ln1303_29_fu_1315_p1;
wire   [28:0] select_ln1303_13_fu_1319_p3;
wire   [31:0] sub_ln1303_30_fu_1339_p2;
wire   [27:0] trunc_ln1303_29_fu_1345_p4;
wire   [28:0] zext_ln1303_30_fu_1355_p1;
wire   [27:0] trunc_ln1303_30_fu_1365_p4;
wire   [0:0] tmp_74_fu_1331_p3;
wire   [28:0] sub_ln1303_31_fu_1359_p2;
wire   [28:0] zext_ln1303_31_fu_1375_p1;
wire   [28:0] select_ln1303_14_fu_1379_p3;
wire   [31:0] sub_ln1303_32_fu_1399_p2;
wire   [27:0] trunc_ln1303_31_fu_1405_p4;
wire   [28:0] zext_ln1303_32_fu_1415_p1;
wire   [27:0] trunc_ln1303_32_fu_1425_p4;
wire   [0:0] tmp_75_fu_1391_p3;
wire   [28:0] sub_ln1303_33_fu_1419_p2;
wire   [28:0] zext_ln1303_33_fu_1435_p1;
wire   [28:0] select_ln1303_15_fu_1439_p3;
wire  signed [29:0] sext_ln78_1_fu_607_p1;
wire  signed [29:0] sext_ln78_fu_547_p1;
wire   [29:0] add_ln813_fu_1451_p2;
wire  signed [29:0] sext_ln78_2_fu_667_p1;
wire  signed [29:0] sext_ln78_3_fu_727_p1;
wire   [29:0] add_ln813_22_fu_1461_p2;
wire  signed [30:0] sext_ln813_2_fu_1467_p1;
wire  signed [30:0] sext_ln813_1_fu_1457_p1;
wire   [30:0] add_ln813_23_fu_1471_p2;
wire  signed [29:0] sext_ln78_4_fu_787_p1;
wire  signed [29:0] sext_ln78_5_fu_847_p1;
wire   [29:0] add_ln813_24_fu_1481_p2;
wire  signed [29:0] sext_ln78_6_fu_907_p1;
wire  signed [29:0] sext_ln78_7_fu_967_p1;
wire   [29:0] add_ln813_25_fu_1491_p2;
wire  signed [30:0] sext_ln813_5_fu_1497_p1;
wire  signed [30:0] sext_ln813_4_fu_1487_p1;
wire   [30:0] add_ln813_26_fu_1501_p2;
wire  signed [31:0] sext_ln813_6_fu_1507_p1;
wire  signed [31:0] sext_ln813_3_fu_1477_p1;
wire  signed [29:0] sext_ln78_8_fu_1027_p1;
wire  signed [29:0] sext_ln78_9_fu_1087_p1;
wire   [29:0] add_ln813_28_fu_1517_p2;
wire  signed [29:0] sext_ln78_10_fu_1147_p1;
wire  signed [29:0] sext_ln78_11_fu_1207_p1;
wire   [29:0] add_ln813_29_fu_1527_p2;
wire  signed [30:0] sext_ln813_8_fu_1533_p1;
wire  signed [30:0] sext_ln813_7_fu_1523_p1;
wire   [30:0] add_ln813_31_fu_1537_p2;
wire  signed [29:0] sext_ln78_12_fu_1267_p1;
wire  signed [29:0] sext_ln78_13_fu_1327_p1;
wire   [29:0] add_ln813_32_fu_1547_p2;
wire  signed [29:0] sext_ln78_14_fu_1387_p1;
wire  signed [29:0] sext_ln813_fu_1447_p1;
wire   [29:0] add_ln813_33_fu_1557_p2;
wire  signed [30:0] sext_ln813_11_fu_1563_p1;
wire  signed [30:0] sext_ln813_10_fu_1553_p1;
wire   [30:0] add_ln813_34_fu_1567_p2;
wire  signed [31:0] sext_ln813_12_fu_1573_p1;
wire  signed [31:0] sext_ln813_9_fu_1543_p1;
wire   [31:0] add_ln813_35_fu_1577_p2;
wire   [31:0] add_ln813_27_fu_1511_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln75_fu_292_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            hs_fu_74 <= add_ln75_3_fu_298_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            hs_fu_74 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln813_30_reg_1689 <= add_ln813_30_fu_1583_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_reg_1600 <= ap_sig_allocacmp_i;
        i_reg_1600_pp0_iter1_reg <= i_reg_1600;
    end
end

always @ (*) begin
    if (((icmp_ln75_fu_292_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 7'd0;
    end else begin
        ap_sig_allocacmp_i = hs_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        global_average_pooling1d_V_ce0 = 1'b1;
    end else begin
        global_average_pooling1d_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        global_average_pooling1d_V_we0 = 1'b1;
    end else begin
        global_average_pooling1d_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce0 = 1'b1;
    end else begin
        straight_attention_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce1 = 1'b1;
    end else begin
        straight_attention_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce10 = 1'b1;
    end else begin
        straight_attention_V_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce11 = 1'b1;
    end else begin
        straight_attention_V_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce12 = 1'b1;
    end else begin
        straight_attention_V_ce12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce13 = 1'b1;
    end else begin
        straight_attention_V_ce13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce14 = 1'b1;
    end else begin
        straight_attention_V_ce14 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce15 = 1'b1;
    end else begin
        straight_attention_V_ce15 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce2 = 1'b1;
    end else begin
        straight_attention_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce3 = 1'b1;
    end else begin
        straight_attention_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce4 = 1'b1;
    end else begin
        straight_attention_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce5 = 1'b1;
    end else begin
        straight_attention_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce6 = 1'b1;
    end else begin
        straight_attention_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce7 = 1'b1;
    end else begin
        straight_attention_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce8 = 1'b1;
    end else begin
        straight_attention_V_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        straight_attention_V_ce9 = 1'b1;
    end else begin
        straight_attention_V_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln75_3_fu_298_p2 = (ap_sig_allocacmp_i + 7'd1);

assign add_ln813_22_fu_1461_p2 = ($signed(sext_ln78_2_fu_667_p1) + $signed(sext_ln78_3_fu_727_p1));

assign add_ln813_23_fu_1471_p2 = ($signed(sext_ln813_2_fu_1467_p1) + $signed(sext_ln813_1_fu_1457_p1));

assign add_ln813_24_fu_1481_p2 = ($signed(sext_ln78_4_fu_787_p1) + $signed(sext_ln78_5_fu_847_p1));

assign add_ln813_25_fu_1491_p2 = ($signed(sext_ln78_6_fu_907_p1) + $signed(sext_ln78_7_fu_967_p1));

assign add_ln813_26_fu_1501_p2 = ($signed(sext_ln813_5_fu_1497_p1) + $signed(sext_ln813_4_fu_1487_p1));

assign add_ln813_27_fu_1511_p2 = ($signed(sext_ln813_6_fu_1507_p1) + $signed(sext_ln813_3_fu_1477_p1));

assign add_ln813_28_fu_1517_p2 = ($signed(sext_ln78_8_fu_1027_p1) + $signed(sext_ln78_9_fu_1087_p1));

assign add_ln813_29_fu_1527_p2 = ($signed(sext_ln78_10_fu_1147_p1) + $signed(sext_ln78_11_fu_1207_p1));

assign add_ln813_30_fu_1583_p2 = (add_ln813_35_fu_1577_p2 + add_ln813_27_fu_1511_p2);

assign add_ln813_31_fu_1537_p2 = ($signed(sext_ln813_8_fu_1533_p1) + $signed(sext_ln813_7_fu_1523_p1));

assign add_ln813_32_fu_1547_p2 = ($signed(sext_ln78_12_fu_1267_p1) + $signed(sext_ln78_13_fu_1327_p1));

assign add_ln813_33_fu_1557_p2 = ($signed(sext_ln78_14_fu_1387_p1) + $signed(sext_ln813_fu_1447_p1));

assign add_ln813_34_fu_1567_p2 = ($signed(sext_ln813_11_fu_1563_p1) + $signed(sext_ln813_10_fu_1553_p1));

assign add_ln813_35_fu_1577_p2 = ($signed(sext_ln813_12_fu_1573_p1) + $signed(sext_ln813_9_fu_1543_p1));

assign add_ln813_fu_1451_p2 = ($signed(sext_ln78_1_fu_607_p1) + $signed(sext_ln78_fu_547_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_461_fu_304_p1 = ap_sig_allocacmp_i[5:0];

assign global_average_pooling1d_V_address0 = i_9_cast116_fu_1589_p1;

assign global_average_pooling1d_V_d0 = add_ln813_30_reg_1689;

assign i_9_cast116_fu_1589_p1 = i_reg_1600_pp0_iter1_reg;

assign icmp_ln75_fu_292_p2 = ((ap_sig_allocacmp_i == 7'd64) ? 1'b1 : 1'b0);

assign or_ln78_10_fu_431_p2 = (tmp_s_fu_308_p3 | 10'd11);

assign or_ln78_11_fu_442_p2 = (tmp_s_fu_308_p3 | 10'd12);

assign or_ln78_12_fu_453_p2 = (tmp_s_fu_308_p3 | 10'd13);

assign or_ln78_13_fu_464_p2 = (tmp_s_fu_308_p3 | 10'd14);

assign or_ln78_14_fu_475_p2 = (tmp_s_fu_308_p3 | 10'd15);

assign or_ln78_1_fu_332_p2 = (tmp_s_fu_308_p3 | 10'd2);

assign or_ln78_2_fu_343_p2 = (tmp_s_fu_308_p3 | 10'd3);

assign or_ln78_3_fu_354_p2 = (tmp_s_fu_308_p3 | 10'd4);

assign or_ln78_4_fu_365_p2 = (tmp_s_fu_308_p3 | 10'd5);

assign or_ln78_5_fu_376_p2 = (tmp_s_fu_308_p3 | 10'd6);

assign or_ln78_6_fu_387_p2 = (tmp_s_fu_308_p3 | 10'd7);

assign or_ln78_7_fu_398_p2 = (tmp_s_fu_308_p3 | 10'd8);

assign or_ln78_8_fu_409_p2 = (tmp_s_fu_308_p3 | 10'd9);

assign or_ln78_9_fu_420_p2 = (tmp_s_fu_308_p3 | 10'd10);

assign or_ln78_fu_321_p2 = (tmp_s_fu_308_p3 | 10'd1);

assign select_ln1303_10_fu_1139_p3 = ((tmp_70_fu_1091_p3[0:0] == 1'b1) ? sub_ln1303_23_fu_1119_p2 : zext_ln1303_23_fu_1135_p1);

assign select_ln1303_11_fu_1199_p3 = ((tmp_71_fu_1151_p3[0:0] == 1'b1) ? sub_ln1303_25_fu_1179_p2 : zext_ln1303_25_fu_1195_p1);

assign select_ln1303_12_fu_1259_p3 = ((tmp_72_fu_1211_p3[0:0] == 1'b1) ? sub_ln1303_27_fu_1239_p2 : zext_ln1303_27_fu_1255_p1);

assign select_ln1303_13_fu_1319_p3 = ((tmp_73_fu_1271_p3[0:0] == 1'b1) ? sub_ln1303_29_fu_1299_p2 : zext_ln1303_29_fu_1315_p1);

assign select_ln1303_14_fu_1379_p3 = ((tmp_74_fu_1331_p3[0:0] == 1'b1) ? sub_ln1303_31_fu_1359_p2 : zext_ln1303_31_fu_1375_p1);

assign select_ln1303_15_fu_1439_p3 = ((tmp_75_fu_1391_p3[0:0] == 1'b1) ? sub_ln1303_33_fu_1419_p2 : zext_ln1303_33_fu_1435_p1);

assign select_ln1303_1_fu_599_p3 = ((tmp_61_fu_551_p3[0:0] == 1'b1) ? sub_ln1303_5_fu_579_p2 : zext_ln1303_5_fu_595_p1);

assign select_ln1303_2_fu_659_p3 = ((tmp_62_fu_611_p3[0:0] == 1'b1) ? sub_ln1303_7_fu_639_p2 : zext_ln1303_7_fu_655_p1);

assign select_ln1303_3_fu_719_p3 = ((tmp_63_fu_671_p3[0:0] == 1'b1) ? sub_ln1303_9_fu_699_p2 : zext_ln1303_9_fu_715_p1);

assign select_ln1303_4_fu_779_p3 = ((tmp_64_fu_731_p3[0:0] == 1'b1) ? sub_ln1303_11_fu_759_p2 : zext_ln1303_11_fu_775_p1);

assign select_ln1303_5_fu_839_p3 = ((tmp_65_fu_791_p3[0:0] == 1'b1) ? sub_ln1303_13_fu_819_p2 : zext_ln1303_13_fu_835_p1);

assign select_ln1303_6_fu_899_p3 = ((tmp_66_fu_851_p3[0:0] == 1'b1) ? sub_ln1303_15_fu_879_p2 : zext_ln1303_15_fu_895_p1);

assign select_ln1303_7_fu_959_p3 = ((tmp_67_fu_911_p3[0:0] == 1'b1) ? sub_ln1303_17_fu_939_p2 : zext_ln1303_17_fu_955_p1);

assign select_ln1303_8_fu_1019_p3 = ((tmp_68_fu_971_p3[0:0] == 1'b1) ? sub_ln1303_19_fu_999_p2 : zext_ln1303_19_fu_1015_p1);

assign select_ln1303_9_fu_1079_p3 = ((tmp_69_fu_1031_p3[0:0] == 1'b1) ? sub_ln1303_21_fu_1059_p2 : zext_ln1303_21_fu_1075_p1);

assign select_ln1303_fu_539_p3 = ((tmp_fu_491_p3[0:0] == 1'b1) ? sub_ln1303_3_fu_519_p2 : zext_ln1303_3_fu_535_p1);

assign sext_ln78_10_fu_1147_p1 = $signed(select_ln1303_10_fu_1139_p3);

assign sext_ln78_11_fu_1207_p1 = $signed(select_ln1303_11_fu_1199_p3);

assign sext_ln78_12_fu_1267_p1 = $signed(select_ln1303_12_fu_1259_p3);

assign sext_ln78_13_fu_1327_p1 = $signed(select_ln1303_13_fu_1319_p3);

assign sext_ln78_14_fu_1387_p1 = $signed(select_ln1303_14_fu_1379_p3);

assign sext_ln78_1_fu_607_p1 = $signed(select_ln1303_1_fu_599_p3);

assign sext_ln78_2_fu_667_p1 = $signed(select_ln1303_2_fu_659_p3);

assign sext_ln78_3_fu_727_p1 = $signed(select_ln1303_3_fu_719_p3);

assign sext_ln78_4_fu_787_p1 = $signed(select_ln1303_4_fu_779_p3);

assign sext_ln78_5_fu_847_p1 = $signed(select_ln1303_5_fu_839_p3);

assign sext_ln78_6_fu_907_p1 = $signed(select_ln1303_6_fu_899_p3);

assign sext_ln78_7_fu_967_p1 = $signed(select_ln1303_7_fu_959_p3);

assign sext_ln78_8_fu_1027_p1 = $signed(select_ln1303_8_fu_1019_p3);

assign sext_ln78_9_fu_1087_p1 = $signed(select_ln1303_9_fu_1079_p3);

assign sext_ln78_fu_547_p1 = $signed(select_ln1303_fu_539_p3);

assign sext_ln813_10_fu_1553_p1 = $signed(add_ln813_32_fu_1547_p2);

assign sext_ln813_11_fu_1563_p1 = $signed(add_ln813_33_fu_1557_p2);

assign sext_ln813_12_fu_1573_p1 = $signed(add_ln813_34_fu_1567_p2);

assign sext_ln813_1_fu_1457_p1 = $signed(add_ln813_fu_1451_p2);

assign sext_ln813_2_fu_1467_p1 = $signed(add_ln813_22_fu_1461_p2);

assign sext_ln813_3_fu_1477_p1 = $signed(add_ln813_23_fu_1471_p2);

assign sext_ln813_4_fu_1487_p1 = $signed(add_ln813_24_fu_1481_p2);

assign sext_ln813_5_fu_1497_p1 = $signed(add_ln813_25_fu_1491_p2);

assign sext_ln813_6_fu_1507_p1 = $signed(add_ln813_26_fu_1501_p2);

assign sext_ln813_7_fu_1523_p1 = $signed(add_ln813_28_fu_1517_p2);

assign sext_ln813_8_fu_1533_p1 = $signed(add_ln813_29_fu_1527_p2);

assign sext_ln813_9_fu_1543_p1 = $signed(add_ln813_31_fu_1537_p2);

assign sext_ln813_fu_1447_p1 = $signed(select_ln1303_15_fu_1439_p3);

assign straight_attention_V_address0 = zext_ln78_15_fu_481_p1;

assign straight_attention_V_address1 = zext_ln78_14_fu_470_p1;

assign straight_attention_V_address10 = zext_ln78_5_fu_371_p1;

assign straight_attention_V_address11 = zext_ln78_4_fu_360_p1;

assign straight_attention_V_address12 = zext_ln78_3_fu_349_p1;

assign straight_attention_V_address13 = zext_ln78_2_fu_338_p1;

assign straight_attention_V_address14 = zext_ln78_1_fu_327_p1;

assign straight_attention_V_address15 = zext_ln78_fu_316_p1;

assign straight_attention_V_address2 = zext_ln78_13_fu_459_p1;

assign straight_attention_V_address3 = zext_ln78_12_fu_448_p1;

assign straight_attention_V_address4 = zext_ln78_11_fu_437_p1;

assign straight_attention_V_address5 = zext_ln78_10_fu_426_p1;

assign straight_attention_V_address6 = zext_ln78_9_fu_415_p1;

assign straight_attention_V_address7 = zext_ln78_8_fu_404_p1;

assign straight_attention_V_address8 = zext_ln78_7_fu_393_p1;

assign straight_attention_V_address9 = zext_ln78_6_fu_382_p1;

assign sub_ln1303_10_fu_739_p2 = (32'd0 - straight_attention_V_q11);

assign sub_ln1303_11_fu_759_p2 = (29'd0 - zext_ln1303_10_fu_755_p1);

assign sub_ln1303_12_fu_799_p2 = (32'd0 - straight_attention_V_q10);

assign sub_ln1303_13_fu_819_p2 = (29'd0 - zext_ln1303_12_fu_815_p1);

assign sub_ln1303_14_fu_859_p2 = (32'd0 - straight_attention_V_q9);

assign sub_ln1303_15_fu_879_p2 = (29'd0 - zext_ln1303_14_fu_875_p1);

assign sub_ln1303_16_fu_919_p2 = (32'd0 - straight_attention_V_q8);

assign sub_ln1303_17_fu_939_p2 = (29'd0 - zext_ln1303_16_fu_935_p1);

assign sub_ln1303_18_fu_979_p2 = (32'd0 - straight_attention_V_q7);

assign sub_ln1303_19_fu_999_p2 = (29'd0 - zext_ln1303_18_fu_995_p1);

assign sub_ln1303_20_fu_1039_p2 = (32'd0 - straight_attention_V_q6);

assign sub_ln1303_21_fu_1059_p2 = (29'd0 - zext_ln1303_20_fu_1055_p1);

assign sub_ln1303_22_fu_1099_p2 = (32'd0 - straight_attention_V_q5);

assign sub_ln1303_23_fu_1119_p2 = (29'd0 - zext_ln1303_22_fu_1115_p1);

assign sub_ln1303_24_fu_1159_p2 = (32'd0 - straight_attention_V_q4);

assign sub_ln1303_25_fu_1179_p2 = (29'd0 - zext_ln1303_24_fu_1175_p1);

assign sub_ln1303_26_fu_1219_p2 = (32'd0 - straight_attention_V_q3);

assign sub_ln1303_27_fu_1239_p2 = (29'd0 - zext_ln1303_26_fu_1235_p1);

assign sub_ln1303_28_fu_1279_p2 = (32'd0 - straight_attention_V_q2);

assign sub_ln1303_29_fu_1299_p2 = (29'd0 - zext_ln1303_28_fu_1295_p1);

assign sub_ln1303_30_fu_1339_p2 = (32'd0 - straight_attention_V_q1);

assign sub_ln1303_31_fu_1359_p2 = (29'd0 - zext_ln1303_30_fu_1355_p1);

assign sub_ln1303_32_fu_1399_p2 = (32'd0 - straight_attention_V_q0);

assign sub_ln1303_33_fu_1419_p2 = (29'd0 - zext_ln1303_32_fu_1415_p1);

assign sub_ln1303_3_fu_519_p2 = (29'd0 - zext_ln1303_fu_515_p1);

assign sub_ln1303_4_fu_559_p2 = (32'd0 - straight_attention_V_q14);

assign sub_ln1303_5_fu_579_p2 = (29'd0 - zext_ln1303_4_fu_575_p1);

assign sub_ln1303_6_fu_619_p2 = (32'd0 - straight_attention_V_q13);

assign sub_ln1303_7_fu_639_p2 = (29'd0 - zext_ln1303_6_fu_635_p1);

assign sub_ln1303_8_fu_679_p2 = (32'd0 - straight_attention_V_q12);

assign sub_ln1303_9_fu_699_p2 = (29'd0 - zext_ln1303_8_fu_695_p1);

assign sub_ln1303_fu_499_p2 = (32'd0 - straight_attention_V_q15);

assign tmp_61_fu_551_p3 = straight_attention_V_q14[32'd31];

assign tmp_62_fu_611_p3 = straight_attention_V_q13[32'd31];

assign tmp_63_fu_671_p3 = straight_attention_V_q12[32'd31];

assign tmp_64_fu_731_p3 = straight_attention_V_q11[32'd31];

assign tmp_65_fu_791_p3 = straight_attention_V_q10[32'd31];

assign tmp_66_fu_851_p3 = straight_attention_V_q9[32'd31];

assign tmp_67_fu_911_p3 = straight_attention_V_q8[32'd31];

assign tmp_68_fu_971_p3 = straight_attention_V_q7[32'd31];

assign tmp_69_fu_1031_p3 = straight_attention_V_q6[32'd31];

assign tmp_70_fu_1091_p3 = straight_attention_V_q5[32'd31];

assign tmp_71_fu_1151_p3 = straight_attention_V_q4[32'd31];

assign tmp_72_fu_1211_p3 = straight_attention_V_q3[32'd31];

assign tmp_73_fu_1271_p3 = straight_attention_V_q2[32'd31];

assign tmp_74_fu_1331_p3 = straight_attention_V_q1[32'd31];

assign tmp_75_fu_1391_p3 = straight_attention_V_q0[32'd31];

assign tmp_fu_491_p3 = straight_attention_V_q15[32'd31];

assign tmp_s_fu_308_p3 = {{empty_461_fu_304_p1}, {4'd0}};

assign trunc_ln1303_10_fu_765_p4 = {{straight_attention_V_q11[31:4]}};

assign trunc_ln1303_11_fu_805_p4 = {{sub_ln1303_12_fu_799_p2[31:4]}};

assign trunc_ln1303_12_fu_825_p4 = {{straight_attention_V_q10[31:4]}};

assign trunc_ln1303_13_fu_865_p4 = {{sub_ln1303_14_fu_859_p2[31:4]}};

assign trunc_ln1303_14_fu_885_p4 = {{straight_attention_V_q9[31:4]}};

assign trunc_ln1303_15_fu_925_p4 = {{sub_ln1303_16_fu_919_p2[31:4]}};

assign trunc_ln1303_16_fu_945_p4 = {{straight_attention_V_q8[31:4]}};

assign trunc_ln1303_17_fu_985_p4 = {{sub_ln1303_18_fu_979_p2[31:4]}};

assign trunc_ln1303_18_fu_1005_p4 = {{straight_attention_V_q7[31:4]}};

assign trunc_ln1303_19_fu_1045_p4 = {{sub_ln1303_20_fu_1039_p2[31:4]}};

assign trunc_ln1303_20_fu_1065_p4 = {{straight_attention_V_q6[31:4]}};

assign trunc_ln1303_21_fu_1105_p4 = {{sub_ln1303_22_fu_1099_p2[31:4]}};

assign trunc_ln1303_22_fu_1125_p4 = {{straight_attention_V_q5[31:4]}};

assign trunc_ln1303_23_fu_1165_p4 = {{sub_ln1303_24_fu_1159_p2[31:4]}};

assign trunc_ln1303_24_fu_1185_p4 = {{straight_attention_V_q4[31:4]}};

assign trunc_ln1303_25_fu_1225_p4 = {{sub_ln1303_26_fu_1219_p2[31:4]}};

assign trunc_ln1303_26_fu_1245_p4 = {{straight_attention_V_q3[31:4]}};

assign trunc_ln1303_27_fu_1285_p4 = {{sub_ln1303_28_fu_1279_p2[31:4]}};

assign trunc_ln1303_28_fu_1305_p4 = {{straight_attention_V_q2[31:4]}};

assign trunc_ln1303_29_fu_1345_p4 = {{sub_ln1303_30_fu_1339_p2[31:4]}};

assign trunc_ln1303_2_fu_525_p4 = {{straight_attention_V_q15[31:4]}};

assign trunc_ln1303_30_fu_1365_p4 = {{straight_attention_V_q1[31:4]}};

assign trunc_ln1303_31_fu_1405_p4 = {{sub_ln1303_32_fu_1399_p2[31:4]}};

assign trunc_ln1303_32_fu_1425_p4 = {{straight_attention_V_q0[31:4]}};

assign trunc_ln1303_3_fu_565_p4 = {{sub_ln1303_4_fu_559_p2[31:4]}};

assign trunc_ln1303_4_fu_585_p4 = {{straight_attention_V_q14[31:4]}};

assign trunc_ln1303_5_fu_625_p4 = {{sub_ln1303_6_fu_619_p2[31:4]}};

assign trunc_ln1303_6_fu_645_p4 = {{straight_attention_V_q13[31:4]}};

assign trunc_ln1303_7_fu_685_p4 = {{sub_ln1303_8_fu_679_p2[31:4]}};

assign trunc_ln1303_8_fu_705_p4 = {{straight_attention_V_q12[31:4]}};

assign trunc_ln1303_9_fu_745_p4 = {{sub_ln1303_10_fu_739_p2[31:4]}};

assign trunc_ln1303_s_fu_505_p4 = {{sub_ln1303_fu_499_p2[31:4]}};

assign zext_ln1303_10_fu_755_p1 = trunc_ln1303_9_fu_745_p4;

assign zext_ln1303_11_fu_775_p1 = trunc_ln1303_10_fu_765_p4;

assign zext_ln1303_12_fu_815_p1 = trunc_ln1303_11_fu_805_p4;

assign zext_ln1303_13_fu_835_p1 = trunc_ln1303_12_fu_825_p4;

assign zext_ln1303_14_fu_875_p1 = trunc_ln1303_13_fu_865_p4;

assign zext_ln1303_15_fu_895_p1 = trunc_ln1303_14_fu_885_p4;

assign zext_ln1303_16_fu_935_p1 = trunc_ln1303_15_fu_925_p4;

assign zext_ln1303_17_fu_955_p1 = trunc_ln1303_16_fu_945_p4;

assign zext_ln1303_18_fu_995_p1 = trunc_ln1303_17_fu_985_p4;

assign zext_ln1303_19_fu_1015_p1 = trunc_ln1303_18_fu_1005_p4;

assign zext_ln1303_20_fu_1055_p1 = trunc_ln1303_19_fu_1045_p4;

assign zext_ln1303_21_fu_1075_p1 = trunc_ln1303_20_fu_1065_p4;

assign zext_ln1303_22_fu_1115_p1 = trunc_ln1303_21_fu_1105_p4;

assign zext_ln1303_23_fu_1135_p1 = trunc_ln1303_22_fu_1125_p4;

assign zext_ln1303_24_fu_1175_p1 = trunc_ln1303_23_fu_1165_p4;

assign zext_ln1303_25_fu_1195_p1 = trunc_ln1303_24_fu_1185_p4;

assign zext_ln1303_26_fu_1235_p1 = trunc_ln1303_25_fu_1225_p4;

assign zext_ln1303_27_fu_1255_p1 = trunc_ln1303_26_fu_1245_p4;

assign zext_ln1303_28_fu_1295_p1 = trunc_ln1303_27_fu_1285_p4;

assign zext_ln1303_29_fu_1315_p1 = trunc_ln1303_28_fu_1305_p4;

assign zext_ln1303_30_fu_1355_p1 = trunc_ln1303_29_fu_1345_p4;

assign zext_ln1303_31_fu_1375_p1 = trunc_ln1303_30_fu_1365_p4;

assign zext_ln1303_32_fu_1415_p1 = trunc_ln1303_31_fu_1405_p4;

assign zext_ln1303_33_fu_1435_p1 = trunc_ln1303_32_fu_1425_p4;

assign zext_ln1303_3_fu_535_p1 = trunc_ln1303_2_fu_525_p4;

assign zext_ln1303_4_fu_575_p1 = trunc_ln1303_3_fu_565_p4;

assign zext_ln1303_5_fu_595_p1 = trunc_ln1303_4_fu_585_p4;

assign zext_ln1303_6_fu_635_p1 = trunc_ln1303_5_fu_625_p4;

assign zext_ln1303_7_fu_655_p1 = trunc_ln1303_6_fu_645_p4;

assign zext_ln1303_8_fu_695_p1 = trunc_ln1303_7_fu_685_p4;

assign zext_ln1303_9_fu_715_p1 = trunc_ln1303_8_fu_705_p4;

assign zext_ln1303_fu_515_p1 = trunc_ln1303_s_fu_505_p4;

assign zext_ln78_10_fu_426_p1 = or_ln78_9_fu_420_p2;

assign zext_ln78_11_fu_437_p1 = or_ln78_10_fu_431_p2;

assign zext_ln78_12_fu_448_p1 = or_ln78_11_fu_442_p2;

assign zext_ln78_13_fu_459_p1 = or_ln78_12_fu_453_p2;

assign zext_ln78_14_fu_470_p1 = or_ln78_13_fu_464_p2;

assign zext_ln78_15_fu_481_p1 = or_ln78_14_fu_475_p2;

assign zext_ln78_1_fu_327_p1 = or_ln78_fu_321_p2;

assign zext_ln78_2_fu_338_p1 = or_ln78_1_fu_332_p2;

assign zext_ln78_3_fu_349_p1 = or_ln78_2_fu_343_p2;

assign zext_ln78_4_fu_360_p1 = or_ln78_3_fu_354_p2;

assign zext_ln78_5_fu_371_p1 = or_ln78_4_fu_365_p2;

assign zext_ln78_6_fu_382_p1 = or_ln78_5_fu_376_p2;

assign zext_ln78_7_fu_393_p1 = or_ln78_6_fu_387_p2;

assign zext_ln78_8_fu_404_p1 = or_ln78_7_fu_398_p2;

assign zext_ln78_9_fu_415_p1 = or_ln78_8_fu_409_p2;

assign zext_ln78_fu_316_p1 = tmp_s_fu_308_p3;

endmodule //CNN_CNN_Pipeline_VITIS_LOOP_75_1
