// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_sqrt_fixed_33_17_s (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [32:0] x;
output  [24:0] ap_return;
input   ap_ce;

reg[24:0] ap_return;

reg   [32:0] x_read_reg_3690;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_11001;
reg   [32:0] x_read_reg_3690_pp0_iter1_reg;
reg   [32:0] x_read_reg_3690_pp0_iter2_reg;
reg   [32:0] x_read_reg_3690_pp0_iter3_reg;
reg   [32:0] x_read_reg_3690_pp0_iter4_reg;
reg   [32:0] x_read_reg_3690_pp0_iter5_reg;
wire   [15:0] trunc_ln841_fu_296_p1;
reg   [15:0] trunc_ln841_reg_3695;
wire   [19:0] x_l_I_V_79_fu_730_p3;
reg   [19:0] x_l_I_V_79_reg_3700;
wire   [8:0] res_I_V_23_fu_738_p3;
reg   [8:0] res_I_V_23_reg_3706;
wire   [0:0] icmp_ln443_5_fu_778_p2;
reg   [0:0] icmp_ln443_5_reg_3712;
wire   [8:0] sub_ln277_5_fu_784_p2;
reg   [8:0] sub_ln277_5_reg_3718;
wire   [0:0] icmp_ln318_fu_800_p2;
reg   [0:0] icmp_ln318_reg_3723;
wire   [0:0] icmp_ln1650_fu_816_p2;
reg   [0:0] icmp_ln1650_reg_3728;
wire   [8:0] res_I_V_25_fu_1000_p3;
reg   [8:0] res_I_V_25_reg_3733;
reg   [8:0] res_I_V_25_reg_3733_pp0_iter2_reg;
reg   [8:0] res_I_V_25_reg_3733_pp0_iter3_reg;
reg   [8:0] res_I_V_25_reg_3733_pp0_iter4_reg;
reg   [8:0] res_I_V_25_reg_3733_pp0_iter5_reg;
wire   [19:0] x_l_I_V_84_fu_1068_p3;
reg   [19:0] x_l_I_V_84_reg_3747;
wire   [16:0] res_FH_V_33_fu_1084_p3;
reg   [16:0] res_FH_V_33_reg_3752;
wire   [19:0] x_l_I_V_85_fu_1194_p2;
reg   [19:0] x_l_I_V_85_reg_3758;
wire   [0:0] or_ln318_1_fu_1200_p2;
reg   [0:0] or_ln318_1_reg_3763;
wire   [16:0] x_l_FH_V_33_fu_1206_p3;
reg   [16:0] x_l_FH_V_33_reg_3769;
wire   [1:0] trunc_ln58_1_fu_1214_p1;
reg   [1:0] trunc_ln58_1_reg_3777;
reg   [6:0] tmp_27_reg_3782;
wire   [2:0] trunc_ln58_2_fu_1228_p1;
reg   [2:0] trunc_ln58_2_reg_3787;
reg   [5:0] tmp_29_reg_3792;
wire   [3:0] trunc_ln58_3_fu_1242_p1;
reg   [3:0] trunc_ln58_3_reg_3797;
reg   [4:0] tmp_31_reg_3802;
wire   [4:0] trunc_ln58_4_fu_1256_p1;
reg   [4:0] trunc_ln58_4_reg_3807;
reg   [4:0] trunc_ln58_4_reg_3807_pp0_iter2_reg;
reg   [3:0] tmp_34_reg_3812;
reg   [3:0] tmp_34_reg_3812_pp0_iter2_reg;
wire   [5:0] trunc_ln58_5_fu_1270_p1;
reg   [5:0] trunc_ln58_5_reg_3817;
reg   [5:0] trunc_ln58_5_reg_3817_pp0_iter2_reg;
reg   [2:0] tmp_36_reg_3822;
reg   [2:0] tmp_36_reg_3822_pp0_iter2_reg;
wire   [6:0] trunc_ln58_6_fu_1284_p1;
reg   [6:0] trunc_ln58_6_reg_3827;
reg   [6:0] trunc_ln58_6_reg_3827_pp0_iter2_reg;
reg   [1:0] tmp_44_reg_3832;
reg   [1:0] tmp_44_reg_3832_pp0_iter2_reg;
wire   [7:0] trunc_ln58_7_fu_1298_p1;
reg   [7:0] trunc_ln58_7_reg_3837;
reg   [7:0] trunc_ln58_7_reg_3837_pp0_iter2_reg;
reg   [7:0] trunc_ln58_7_reg_3837_pp0_iter3_reg;
reg   [0:0] tmp_46_reg_3842;
reg   [0:0] tmp_46_reg_3842_pp0_iter2_reg;
reg   [0:0] tmp_46_reg_3842_pp0_iter3_reg;
wire   [16:0] res_FH_V_36_fu_1582_p3;
reg   [16:0] res_FH_V_36_reg_3847;
wire   [0:0] or_ln318_4_fu_1682_p2;
reg   [0:0] or_ln318_4_reg_3853;
wire   [19:0] x_l_I_V_92_fu_1688_p3;
reg   [19:0] x_l_I_V_92_reg_3858;
wire   [16:0] x_l_FH_V_39_fu_1696_p3;
reg   [16:0] x_l_FH_V_39_reg_3867;
wire   [16:0] res_FH_V_39_fu_1966_p3;
reg   [16:0] res_FH_V_39_reg_3875;
wire   [0:0] or_ln318_7_fu_2066_p2;
reg   [0:0] or_ln318_7_reg_3881;
wire   [19:0] x_l_I_V_98_fu_2072_p3;
reg   [19:0] x_l_I_V_98_reg_3886;
wire   [16:0] x_l_FH_V_45_fu_2080_p3;
reg   [16:0] x_l_FH_V_45_reg_3895;
wire   [16:0] res_FH_V_41_fu_2404_p3;
reg   [16:0] res_FH_V_41_reg_3902;
wire   [0:0] or_ln318_12_fu_2551_p2;
reg   [0:0] or_ln318_12_reg_3908;
wire   [19:0] x_l_I_V_104_fu_2557_p3;
reg   [19:0] x_l_I_V_104_reg_3913;
wire   [16:0] x_l_FH_V_51_fu_2565_p3;
reg   [16:0] x_l_FH_V_51_reg_3920;
wire   [16:0] x_l_FL_V_17_fu_2573_p3;
reg   [16:0] x_l_FL_V_17_reg_3929;
wire   [16:0] res_FH_V_44_fu_2958_p3;
reg   [16:0] res_FH_V_44_reg_3937;
wire   [0:0] or_ln318_18_fu_3109_p2;
reg   [0:0] or_ln318_18_reg_3943;
wire   [19:0] x_l_I_V_110_fu_3115_p3;
reg   [19:0] x_l_I_V_110_reg_3948;
wire   [16:0] x_l_FH_V_57_fu_3123_p3;
reg   [16:0] x_l_FH_V_57_reg_3955;
wire   [16:0] x_l_FL_V_20_fu_3131_p3;
reg   [16:0] x_l_FL_V_20_reg_3964;
wire    ap_block_pp0_stage0;
wire   [16:0] trunc_ln_fu_282_p4;
wire   [19:0] zext_ln818_fu_292_p1;
wire   [0:0] tmp_fu_300_p3;
wire   [19:0] p_Result_47_fu_308_p5;
wire   [8:0] res_I_V_18_fu_328_p3;
wire   [1:0] tmp_s_fu_336_p4;
wire   [19:0] x_l_I_V_74_fu_320_p3;
wire   [2:0] tmp_1_fu_346_p3;
wire   [3:0] tmp_2_fu_354_p4;
wire   [3:0] zext_ln443_fu_364_p1;
wire   [3:0] sub_ln277_fu_374_p2;
wire   [0:0] icmp_ln443_fu_368_p2;
wire   [19:0] p_Result_48_fu_380_p5;
wire   [8:0] p_Result_49_fu_392_p4;
wire   [8:0] res_I_V_19_fu_410_p3;
wire   [2:0] tmp_3_fu_418_p4;
wire   [19:0] x_l_I_V_75_fu_402_p3;
wire   [3:0] tmp_6_fu_428_p3;
wire   [4:0] tmp_4_fu_436_p4;
wire   [4:0] zext_ln443_1_fu_446_p1;
wire   [4:0] sub_ln277_1_fu_456_p2;
wire   [0:0] icmp_ln443_1_fu_450_p2;
wire   [19:0] p_Result_50_fu_462_p5;
wire   [8:0] p_Result_51_fu_474_p4;
wire   [8:0] res_I_V_20_fu_492_p3;
wire   [3:0] tmp_5_fu_500_p4;
wire   [19:0] x_l_I_V_76_fu_484_p3;
wire   [4:0] tmp_7_fu_510_p3;
wire   [5:0] tmp_8_fu_518_p4;
wire   [5:0] zext_ln443_2_fu_528_p1;
wire   [5:0] sub_ln277_2_fu_538_p2;
wire   [0:0] icmp_ln443_2_fu_532_p2;
wire   [19:0] p_Result_52_fu_544_p5;
wire   [8:0] p_Result_53_fu_556_p4;
wire   [8:0] res_I_V_21_fu_574_p3;
wire   [4:0] tmp_9_fu_582_p4;
wire   [19:0] x_l_I_V_77_fu_566_p3;
wire   [5:0] tmp_10_fu_592_p3;
wire   [6:0] tmp_11_fu_600_p4;
wire   [6:0] zext_ln443_3_fu_610_p1;
wire   [6:0] sub_ln277_3_fu_620_p2;
wire   [0:0] icmp_ln443_3_fu_614_p2;
wire   [19:0] p_Result_54_fu_626_p5;
wire   [8:0] p_Result_55_fu_638_p4;
wire   [8:0] res_I_V_22_fu_656_p3;
wire   [5:0] tmp_12_fu_664_p4;
wire   [19:0] x_l_I_V_78_fu_648_p3;
wire   [6:0] tmp_13_fu_674_p3;
wire   [7:0] tmp_14_fu_682_p4;
wire   [7:0] zext_ln443_4_fu_692_p1;
wire   [7:0] sub_ln277_4_fu_702_p2;
wire   [0:0] icmp_ln443_4_fu_696_p2;
wire   [19:0] p_Result_56_fu_708_p5;
wire   [8:0] p_Result_57_fu_720_p4;
wire   [6:0] tmp_15_fu_746_p4;
wire   [7:0] tmp_16_fu_756_p3;
wire   [8:0] tmp_17_fu_764_p4;
wire   [8:0] zext_ln443_5_fu_774_p1;
wire   [1:0] tmp_25_fu_790_p4;
wire   [1:0] tmp_26_fu_806_p4;
wire   [19:0] p_Result_58_fu_829_p5;
wire   [8:0] p_Result_59_fu_839_p4;
wire   [8:0] res_I_V_24_fu_854_p3;
wire   [7:0] tmp_18_fu_860_p4;
wire   [19:0] x_l_I_V_80_fu_848_p3;
wire   [8:0] tmp_19_fu_870_p3;
wire   [9:0] tmp_20_fu_878_p4;
wire   [9:0] zext_ln443_6_fu_888_p1;
wire   [9:0] sub_ln277_6_fu_898_p2;
wire   [0:0] icmp_ln443_6_fu_892_p2;
wire   [19:0] p_Result_60_fu_904_p5;
wire   [8:0] p_Result_61_fu_916_p4;
wire   [8:0] res_I_V_fu_934_p3;
wire   [19:0] x_l_I_V_81_fu_926_p3;
wire   [9:0] tmp_21_fu_942_p3;
wire   [10:0] trunc_ln594_fu_950_p1;
wire   [10:0] zext_ln443_7_fu_954_p1;
wire   [10:0] sub_ln277_7_fu_964_p2;
wire   [0:0] icmp_ln443_7_fu_958_p2;
wire   [19:0] p_Result_62_fu_970_p5;
wire   [8:0] p_Result_63_fu_982_p4;
wire   [9:0] trunc_ln2_fu_1008_p3;
wire   [19:0] x_l_I_V_82_fu_992_p3;
wire   [19:0] zext_ln1649_fu_1016_p1;
wire   [0:0] icmp_ln1653_fu_1026_p2;
wire   [19:0] x_l_I_V_fu_1037_p2;
wire   [16:0] x_l_FH_V_31_fu_822_p3;
wire   [19:0] x_l_I_V_19_fu_1043_p3;
wire   [0:0] icmp_ln1649_fu_1020_p2;
wire   [0:0] and_ln318_fu_1032_p2;
wire   [0:0] or_ln318_fu_1062_p2;
wire   [19:0] x_l_I_V_83_fu_1056_p2;
wire   [16:0] x_l_FH_V_32_fu_1050_p2;
wire   [0:0] trunc_ln58_fu_1102_p1;
wire   [1:0] tmp_22_fu_1092_p4;
wire   [7:0] tmp_23_fu_1116_p4;
wire   [8:0] trunc_ln1649_1_fu_1126_p3;
wire   [19:0] zext_ln1649_1_fu_1134_p1;
wire   [16:0] p_Val2_109_fu_1076_p3;
wire   [16:0] mul_FH_V_fu_1106_p4;
wire   [0:0] icmp_ln318_1_fu_1150_p2;
wire   [0:0] icmp_ln1653_1_fu_1144_p2;
wire   [0:0] xor_ln318_fu_1156_p2;
wire   [0:0] icmp_ln1650_1_fu_1168_p2;
wire   [19:0] x_l_I_V_22_fu_1174_p2;
wire   [19:0] x_l_I_V_23_fu_1180_p3;
wire   [0:0] icmp_ln1649_1_fu_1138_p2;
wire   [0:0] and_ln318_1_fu_1162_p2;
wire   [16:0] x_l_FH_V_fu_1188_p2;
wire   [16:0] p_Result_64_fu_1310_p4;
wire   [16:0] res_FH_V_34_fu_1324_p3;
wire   [2:0] tmp_24_fu_1330_p4;
wire   [7:0] trunc_ln1649_2_fu_1349_p3;
wire   [19:0] x_l_I_V_86_fu_1319_p3;
wire   [19:0] zext_ln1649_2_fu_1356_p1;
wire   [16:0] mul_FH_V_1_fu_1340_p4;
wire   [0:0] icmp_ln318_2_fu_1372_p2;
wire   [0:0] icmp_ln1653_2_fu_1366_p2;
wire   [0:0] xor_ln318_1_fu_1377_p2;
wire   [0:0] icmp_ln1650_2_fu_1389_p2;
wire   [19:0] x_l_I_V_26_fu_1394_p2;
wire   [19:0] x_l_I_V_27_fu_1400_p3;
wire   [0:0] icmp_ln1649_2_fu_1360_p2;
wire   [0:0] and_ln318_2_fu_1383_p2;
wire   [0:0] or_ln318_2_fu_1429_p2;
wire   [19:0] x_l_I_V_87_fu_1413_p2;
wire   [16:0] x_l_FH_V_34_fu_1408_p2;
wire   [16:0] p_Result_65_fu_1419_p4;
wire   [16:0] res_FH_V_35_fu_1450_p3;
wire   [3:0] tmp_28_fu_1458_p4;
wire   [6:0] trunc_ln1649_3_fu_1477_p3;
wire   [19:0] x_l_I_V_88_fu_1435_p3;
wire   [19:0] zext_ln1649_3_fu_1484_p1;
wire   [16:0] x_l_FH_V_35_fu_1443_p3;
wire   [16:0] mul_FH_V_2_fu_1468_p4;
wire   [0:0] icmp_ln318_3_fu_1500_p2;
wire   [0:0] icmp_ln1653_3_fu_1494_p2;
wire   [0:0] xor_ln318_2_fu_1506_p2;
wire   [0:0] icmp_ln1650_3_fu_1518_p2;
wire   [19:0] x_l_I_V_30_fu_1524_p2;
wire   [19:0] x_l_I_V_31_fu_1530_p3;
wire   [0:0] icmp_ln1649_3_fu_1488_p2;
wire   [0:0] and_ln318_3_fu_1512_p2;
wire   [0:0] or_ln318_3_fu_1560_p2;
wire   [19:0] x_l_I_V_89_fu_1544_p2;
wire   [16:0] x_l_FH_V_36_fu_1538_p2;
wire   [16:0] p_Result_66_fu_1550_p4;
wire   [4:0] tmp_30_fu_1590_p4;
wire   [5:0] trunc_ln1649_4_fu_1609_p3;
wire   [19:0] x_l_I_V_90_fu_1566_p3;
wire   [19:0] zext_ln1649_4_fu_1616_p1;
wire   [16:0] x_l_FH_V_37_fu_1574_p3;
wire   [16:0] mul_FH_V_3_fu_1600_p4;
wire   [0:0] icmp_ln318_4_fu_1632_p2;
wire   [0:0] icmp_ln1653_4_fu_1626_p2;
wire   [0:0] xor_ln318_3_fu_1638_p2;
wire   [0:0] icmp_ln1650_4_fu_1650_p2;
wire   [19:0] x_l_I_V_34_fu_1656_p2;
wire   [19:0] x_l_I_V_35_fu_1662_p3;
wire   [0:0] icmp_ln1649_4_fu_1620_p2;
wire   [0:0] and_ln318_4_fu_1644_p2;
wire   [19:0] x_l_I_V_91_fu_1676_p2;
wire   [16:0] x_l_FH_V_38_fu_1670_p2;
wire   [16:0] p_Result_67_fu_1704_p4;
wire   [16:0] res_FH_V_37_fu_1713_p3;
wire   [5:0] tmp_33_fu_1719_p4;
wire   [4:0] trunc_ln1649_5_fu_1738_p3;
wire   [19:0] zext_ln1649_5_fu_1745_p1;
wire   [16:0] mul_FH_V_4_fu_1729_p4;
wire   [0:0] icmp_ln318_5_fu_1759_p2;
wire   [0:0] icmp_ln1653_5_fu_1754_p2;
wire   [0:0] xor_ln318_4_fu_1764_p2;
wire   [0:0] icmp_ln1650_5_fu_1776_p2;
wire   [19:0] x_l_I_V_38_fu_1781_p2;
wire   [19:0] x_l_I_V_39_fu_1786_p3;
wire   [0:0] icmp_ln1649_5_fu_1749_p2;
wire   [0:0] and_ln318_5_fu_1770_p2;
wire   [0:0] or_ln318_5_fu_1814_p2;
wire   [19:0] x_l_I_V_93_fu_1798_p2;
wire   [16:0] x_l_FH_V_40_fu_1793_p2;
wire   [16:0] p_Result_68_fu_1804_p4;
wire   [16:0] res_FH_V_38_fu_1834_p3;
wire   [6:0] tmp_35_fu_1842_p4;
wire   [3:0] trunc_ln1649_6_fu_1861_p3;
wire   [19:0] x_l_I_V_94_fu_1820_p3;
wire   [19:0] zext_ln1649_6_fu_1868_p1;
wire   [16:0] x_l_FH_V_41_fu_1827_p3;
wire   [16:0] mul_FH_V_5_fu_1852_p4;
wire   [0:0] icmp_ln318_6_fu_1884_p2;
wire   [0:0] icmp_ln1653_6_fu_1878_p2;
wire   [0:0] xor_ln318_5_fu_1890_p2;
wire   [0:0] icmp_ln1650_6_fu_1902_p2;
wire   [19:0] x_l_I_V_42_fu_1908_p2;
wire   [19:0] x_l_I_V_43_fu_1914_p3;
wire   [0:0] icmp_ln1649_6_fu_1872_p2;
wire   [0:0] and_ln318_6_fu_1896_p2;
wire   [0:0] or_ln318_6_fu_1944_p2;
wire   [19:0] x_l_I_V_95_fu_1928_p2;
wire   [16:0] x_l_FH_V_42_fu_1922_p2;
wire   [16:0] p_Result_69_fu_1934_p4;
wire   [7:0] tmp_37_fu_1974_p4;
wire   [2:0] trunc_ln1649_7_fu_1993_p3;
wire   [19:0] x_l_I_V_96_fu_1950_p3;
wire   [19:0] zext_ln1649_7_fu_2000_p1;
wire   [16:0] x_l_FH_V_43_fu_1958_p3;
wire   [16:0] mul_FH_V_6_fu_1984_p4;
wire   [0:0] icmp_ln318_7_fu_2016_p2;
wire   [0:0] icmp_ln1653_7_fu_2010_p2;
wire   [0:0] xor_ln318_6_fu_2022_p2;
wire   [0:0] icmp_ln1650_7_fu_2034_p2;
wire   [19:0] x_l_I_V_46_fu_2040_p2;
wire   [19:0] x_l_I_V_47_fu_2046_p3;
wire   [0:0] icmp_ln1649_7_fu_2004_p2;
wire   [0:0] and_ln318_7_fu_2028_p2;
wire   [19:0] x_l_I_V_97_fu_2060_p2;
wire   [16:0] x_l_FH_V_44_fu_2054_p2;
wire   [16:0] p_Result_70_fu_2088_p4;
wire   [16:0] res_FH_V_fu_2097_p3;
wire   [8:0] tmp_45_fu_2103_p4;
wire   [1:0] trunc_ln1649_8_fu_2120_p3;
wire   [19:0] zext_ln1649_8_fu_2127_p1;
wire   [16:0] mul_FH_V_7_fu_2113_p3;
wire   [0:0] icmp_ln1653_8_fu_2136_p2;
wire   [0:0] icmp_ln1649_9_fu_2141_p2;
wire   [19:0] x_l_I_V_50_fu_2157_p2;
wire   [16:0] add_ln813_fu_2152_p2;
wire   [19:0] p_Val2_110_fu_2162_p3;
wire   [0:0] icmp_ln1649_8_fu_2131_p2;
wire   [0:0] and_ln318_8_fu_2146_p2;
wire   [0:0] or_ln318_8_fu_2191_p2;
wire   [19:0] x_l_I_V_99_fu_2175_p2;
wire   [16:0] x_l_FH_V_46_fu_2169_p2;
wire   [16:0] p_Result_71_fu_2181_p4;
wire   [16:0] res_FH_V_40_fu_2219_p3;
wire   [7:0] tmp_47_fu_2237_p4;
wire   [1:0] tmp_32_fu_2227_p4;
wire   [19:0] x_l_I_V_100_fu_2197_p3;
wire   [16:0] x_l_FH_V_47_fu_2204_p3;
wire   [16:0] mul_FH_V_8_fu_2247_p3;
wire   [16:0] x_l_FL_V_15_fu_2211_p3;
wire   [16:0] mul_FL_V_fu_2254_p3;
wire   [0:0] icmp_ln1651_fu_2280_p2;
wire   [0:0] icmp_ln1653_9_fu_2274_p2;
wire   [0:0] xor_ln1651_fu_2286_p2;
wire   [0:0] signbit_fu_2298_p2;
wire   [0:0] icmp_ln1650_9_fu_2304_p2;
wire   [0:0] and_ln331_fu_2310_p2;
wire   [16:0] zext_ln813_fu_2322_p1;
wire   [0:0] or_ln331_fu_2316_p2;
wire   [19:0] x_l_I_V_54_fu_2332_p2;
wire   [16:0] sub_ln813_fu_2326_p2;
wire   [0:0] icmp_ln1649_10_fu_2268_p2;
wire   [0:0] and_ln318_9_fu_2292_p2;
wire   [0:0] or_ln318_9_fu_2368_p2;
wire   [0:0] icmp_ln318_8_fu_2262_p2;
wire   [0:0] or_ln318_10_fu_2374_p2;
wire   [19:0] x_l_I_V_101_fu_2338_p3;
wire   [16:0] x_l_FH_V_48_fu_2346_p2;
wire   [16:0] x_l_FL_V_fu_2352_p2;
wire   [16:0] p_Result_72_fu_2358_p4;
wire   [6:0] tmp_48_fu_2422_p4;
wire   [3:0] tmp_38_fu_2412_p4;
wire   [19:0] x_l_I_V_102_fu_2380_p3;
wire   [16:0] x_l_FH_V_49_fu_2388_p3;
wire   [16:0] mul_FH_V_9_fu_2432_p4;
wire   [16:0] x_l_FL_V_16_fu_2396_p3;
wire   [16:0] mul_FL_V_1_fu_2441_p3;
wire   [0:0] icmp_ln1651_1_fu_2467_p2;
wire   [0:0] icmp_ln1653_10_fu_2461_p2;
wire   [0:0] xor_ln1651_1_fu_2473_p2;
wire   [0:0] signbit_1_fu_2485_p2;
wire   [0:0] icmp_ln1650_11_fu_2491_p2;
wire   [0:0] and_ln331_1_fu_2497_p2;
wire   [16:0] zext_ln813_1_fu_2509_p1;
wire   [0:0] or_ln331_1_fu_2503_p2;
wire   [19:0] x_l_I_V_57_fu_2519_p2;
wire   [16:0] sub_ln813_11_fu_2513_p2;
wire   [0:0] icmp_ln1649_11_fu_2455_p2;
wire   [0:0] and_ln318_10_fu_2479_p2;
wire   [0:0] or_ln318_11_fu_2545_p2;
wire   [0:0] icmp_ln318_9_fu_2449_p2;
wire   [19:0] x_l_I_V_103_fu_2525_p3;
wire   [16:0] x_l_FH_V_50_fu_2533_p2;
wire   [16:0] x_l_FL_V_3_fu_2539_p2;
wire   [16:0] p_Result_73_fu_2581_p4;
wire   [16:0] res_FH_V_42_fu_2590_p3;
wire   [5:0] tmp_49_fu_2606_p4;
wire   [15:0] mul_FH_V_s_fu_2616_p4;
wire   [5:0] tmp_39_fu_2596_p4;
wire   [16:0] zext_ln818_1_fu_2625_p1;
wire   [16:0] mul_FL_V_2_fu_2629_p3;
wire   [0:0] icmp_ln1651_2_fu_2652_p2;
wire   [0:0] icmp_ln1653_11_fu_2647_p2;
wire   [0:0] xor_ln1651_2_fu_2657_p2;
wire   [0:0] signbit_2_fu_2669_p2;
wire   [0:0] icmp_ln1650_12_fu_2674_p2;
wire   [0:0] and_ln331_2_fu_2679_p2;
wire   [16:0] zext_ln813_2_fu_2691_p1;
wire   [0:0] or_ln331_2_fu_2685_p2;
wire   [19:0] x_l_I_V_60_fu_2700_p2;
wire   [16:0] sub_ln813_14_fu_2695_p2;
wire   [0:0] icmp_ln1649_12_fu_2642_p2;
wire   [0:0] and_ln318_11_fu_2663_p2;
wire   [0:0] or_ln318_13_fu_2733_p2;
wire   [0:0] icmp_ln318_10_fu_2637_p2;
wire   [0:0] or_ln318_14_fu_2739_p2;
wire   [19:0] x_l_I_V_105_fu_2705_p3;
wire   [16:0] x_l_FH_V_52_fu_2712_p2;
wire   [16:0] x_l_FL_V_5_fu_2718_p2;
wire   [16:0] p_Result_74_fu_2723_p4;
wire   [16:0] res_FH_V_43_fu_2767_p3;
wire   [4:0] tmp_50_fu_2785_p4;
wire   [14:0] mul_FH_V_10_fu_2795_p4;
wire   [7:0] tmp_40_fu_2775_p4;
wire   [19:0] x_l_I_V_106_fu_2745_p3;
wire   [16:0] x_l_FH_V_53_fu_2753_p3;
wire   [16:0] zext_ln818_2_fu_2804_p1;
wire   [16:0] x_l_FL_V_18_fu_2760_p3;
wire   [16:0] mul_FL_V_3_fu_2808_p3;
wire   [0:0] icmp_ln1651_3_fu_2834_p2;
wire   [0:0] icmp_ln1653_12_fu_2828_p2;
wire   [0:0] xor_ln1651_3_fu_2840_p2;
wire   [0:0] signbit_3_fu_2852_p2;
wire   [0:0] icmp_ln1650_13_fu_2858_p2;
wire   [0:0] and_ln331_3_fu_2864_p2;
wire   [16:0] zext_ln813_3_fu_2876_p1;
wire   [0:0] or_ln331_3_fu_2870_p2;
wire   [19:0] x_l_I_V_63_fu_2886_p2;
wire   [16:0] sub_ln813_17_fu_2880_p2;
wire   [0:0] icmp_ln1649_13_fu_2822_p2;
wire   [0:0] and_ln318_12_fu_2846_p2;
wire   [0:0] or_ln318_15_fu_2922_p2;
wire   [0:0] icmp_ln318_11_fu_2816_p2;
wire   [0:0] or_ln318_16_fu_2928_p2;
wire   [19:0] x_l_I_V_107_fu_2892_p3;
wire   [16:0] x_l_FH_V_54_fu_2900_p2;
wire   [16:0] x_l_FL_V_7_fu_2906_p2;
wire   [16:0] p_Result_75_fu_2912_p4;
wire   [3:0] tmp_51_fu_2976_p4;
wire   [13:0] mul_FH_V_11_fu_2986_p4;
wire   [9:0] tmp_41_fu_2966_p4;
wire   [19:0] x_l_I_V_108_fu_2934_p3;
wire   [16:0] x_l_FH_V_55_fu_2942_p3;
wire   [16:0] zext_ln818_3_fu_2995_p1;
wire   [16:0] x_l_FL_V_19_fu_2950_p3;
wire   [16:0] mul_FL_V_4_fu_2999_p3;
wire   [0:0] icmp_ln1651_4_fu_3025_p2;
wire   [0:0] icmp_ln1653_13_fu_3019_p2;
wire   [0:0] xor_ln1651_4_fu_3031_p2;
wire   [0:0] signbit_4_fu_3043_p2;
wire   [0:0] icmp_ln1650_14_fu_3049_p2;
wire   [0:0] and_ln331_4_fu_3055_p2;
wire   [16:0] zext_ln813_4_fu_3067_p1;
wire   [0:0] or_ln331_4_fu_3061_p2;
wire   [19:0] x_l_I_V_66_fu_3077_p2;
wire   [16:0] sub_ln813_20_fu_3071_p2;
wire   [0:0] icmp_ln1649_14_fu_3013_p2;
wire   [0:0] and_ln318_13_fu_3037_p2;
wire   [0:0] or_ln318_17_fu_3103_p2;
wire   [0:0] icmp_ln318_12_fu_3007_p2;
wire   [19:0] x_l_I_V_109_fu_3083_p3;
wire   [16:0] x_l_FH_V_56_fu_3091_p2;
wire   [16:0] x_l_FL_V_9_fu_3097_p2;
wire   [16:0] p_Result_76_fu_3146_p4;
wire   [16:0] res_FH_V_45_fu_3155_p3;
wire   [2:0] tmp_52_fu_3171_p4;
wire   [12:0] mul_FH_V_12_fu_3181_p4;
wire   [11:0] tmp_42_fu_3161_p4;
wire   [16:0] zext_ln818_4_fu_3190_p1;
wire   [16:0] mul_FL_V_5_fu_3194_p3;
wire   [0:0] icmp_ln1651_5_fu_3217_p2;
wire   [0:0] icmp_ln1653_14_fu_3212_p2;
wire   [0:0] xor_ln1651_5_fu_3222_p2;
wire   [0:0] signbit_5_fu_3234_p2;
wire   [0:0] icmp_ln1650_15_fu_3239_p2;
wire   [0:0] and_ln331_5_fu_3244_p2;
wire   [16:0] zext_ln813_5_fu_3256_p1;
wire   [0:0] or_ln331_5_fu_3250_p2;
wire   [19:0] x_l_I_V_69_fu_3265_p2;
wire   [16:0] sub_ln813_23_fu_3260_p2;
wire   [0:0] icmp_ln1649_15_fu_3207_p2;
wire   [0:0] and_ln318_14_fu_3228_p2;
wire   [0:0] or_ln318_19_fu_3298_p2;
wire   [0:0] icmp_ln318_13_fu_3202_p2;
wire   [0:0] or_ln318_20_fu_3304_p2;
wire   [19:0] x_l_I_V_111_fu_3270_p3;
wire   [16:0] x_l_FH_V_58_fu_3277_p2;
wire   [16:0] x_l_FL_V_11_fu_3283_p2;
wire   [16:0] p_Result_77_fu_3288_p4;
wire   [16:0] res_FH_V_46_fu_3332_p3;
wire   [1:0] tmp_53_fu_3350_p4;
wire   [11:0] mul_FH_V_13_fu_3360_p4;
wire   [13:0] tmp_43_fu_3340_p4;
wire   [19:0] x_l_I_V_112_fu_3310_p3;
wire   [16:0] x_l_FH_V_59_fu_3318_p3;
wire   [16:0] zext_ln818_5_fu_3369_p1;
wire   [16:0] x_l_FL_V_21_fu_3325_p3;
wire   [16:0] mul_FL_V_6_fu_3373_p3;
wire   [0:0] icmp_ln1651_6_fu_3399_p2;
wire   [0:0] icmp_ln1653_15_fu_3393_p2;
wire   [0:0] xor_ln1651_6_fu_3405_p2;
wire   [0:0] signbit_6_fu_3417_p2;
wire   [0:0] icmp_ln1650_16_fu_3423_p2;
wire   [0:0] and_ln331_6_fu_3429_p2;
wire   [16:0] zext_ln813_6_fu_3441_p1;
wire   [0:0] or_ln331_6_fu_3435_p2;
wire   [19:0] x_l_I_V_72_fu_3451_p2;
wire   [16:0] sub_ln813_26_fu_3445_p2;
wire   [19:0] x_l_I_V_113_fu_3457_p3;
wire   [0:0] icmp_ln1649_16_fu_3387_p2;
wire   [0:0] and_ln318_15_fu_3411_p2;
wire   [0:0] or_ln318_21_fu_3493_p2;
wire   [0:0] icmp_ln318_14_fu_3381_p2;
wire   [0:0] or_ln318_22_fu_3499_p2;
wire   [0:0] icmp_ln353_fu_3487_p2;
wire   [16:0] x_l_FH_V_60_fu_3465_p2;
wire   [16:0] x_l_FL_V_13_fu_3471_p2;
wire   [16:0] p_Result_78_fu_3477_p4;
wire   [16:0] res_FH_V_47_fu_3527_p3;
wire   [15:0] trunc_ln58_8_fu_3535_p1;
wire   [0:0] tmp_56_fu_3547_p3;
wire   [10:0] mul_FH_V_14_fu_3555_p4;
wire   [16:0] x_l_FH_V_61_fu_3511_p3;
wire   [16:0] zext_ln818_6_fu_3564_p1;
wire   [16:0] x_l_FL_V_14_fu_3519_p3;
wire   [16:0] mul_FL_V_7_fu_3539_p3;
wire   [0:0] icmp_ln1651_7_fu_3580_p2;
wire   [0:0] icmp_ln1653_16_fu_3574_p2;
wire   [0:0] xor_ln1651_7_fu_3586_p2;
wire   [0:0] icmp_ln1649_17_fu_3568_p2;
wire   [0:0] and_ln318_16_fu_3592_p2;
wire   [0:0] or_ln318_23_fu_3608_p2;
wire   [0:0] and_ln318_17_fu_3505_p2;
wire   [0:0] or_ln318_24_fu_3614_p2;
wire   [16:0] p_Result_79_fu_3598_p4;
wire   [16:0] res_FH_V_31_fu_3620_p3;
wire   [17:0] zext_ln813_7_fu_3628_p1;
wire   [17:0] res_FH_l_V_fu_3632_p2;
wire   [0:0] p_Result_44_fu_3644_p3;
wire   [8:0] res_I_V_16_fu_3652_p2;
wire   [16:0] res_FH_V_48_fu_3638_p2;
wire   [8:0] res_I_V_26_fu_3657_p3;
wire   [15:0] tmp_54_fu_3664_p4;
wire   [0:0] p_Result_s_fu_3139_p3;
wire   [24:0] trunc_ln4_fu_3674_p3;
wire   [24:0] select_ln53_fu_3682_p3;
reg    ap_ce_reg;
reg   [32:0] x_int_reg;
reg   [24:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln53_fu_3682_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        icmp_ln1650_reg_3728 <= icmp_ln1650_fu_816_p2;
        icmp_ln318_reg_3723 <= icmp_ln318_fu_800_p2;
        icmp_ln443_5_reg_3712 <= icmp_ln443_5_fu_778_p2;
        or_ln318_12_reg_3908 <= or_ln318_12_fu_2551_p2;
        or_ln318_18_reg_3943 <= or_ln318_18_fu_3109_p2;
        or_ln318_1_reg_3763 <= or_ln318_1_fu_1200_p2;
        or_ln318_4_reg_3853 <= or_ln318_4_fu_1682_p2;
        or_ln318_7_reg_3881 <= or_ln318_7_fu_2066_p2;
        res_FH_V_33_reg_3752[16] <= res_FH_V_33_fu_1084_p3[16];
        res_FH_V_36_reg_3847 <= res_FH_V_36_fu_1582_p3;
        res_FH_V_39_reg_3875 <= res_FH_V_39_fu_1966_p3;
        res_FH_V_41_reg_3902 <= res_FH_V_41_fu_2404_p3;
        res_FH_V_44_reg_3937 <= res_FH_V_44_fu_2958_p3;
        res_I_V_23_reg_3706 <= res_I_V_23_fu_738_p3;
        res_I_V_25_reg_3733 <= res_I_V_25_fu_1000_p3;
        res_I_V_25_reg_3733_pp0_iter2_reg <= res_I_V_25_reg_3733;
        res_I_V_25_reg_3733_pp0_iter3_reg <= res_I_V_25_reg_3733_pp0_iter2_reg;
        res_I_V_25_reg_3733_pp0_iter4_reg <= res_I_V_25_reg_3733_pp0_iter3_reg;
        res_I_V_25_reg_3733_pp0_iter5_reg <= res_I_V_25_reg_3733_pp0_iter4_reg;
        sub_ln277_5_reg_3718 <= sub_ln277_5_fu_784_p2;
        tmp_27_reg_3782 <= {{res_I_V_25_fu_1000_p3[8:2]}};
        tmp_29_reg_3792 <= {{res_I_V_25_fu_1000_p3[8:3]}};
        tmp_31_reg_3802 <= {{res_I_V_25_fu_1000_p3[8:4]}};
        tmp_34_reg_3812 <= {{res_I_V_25_fu_1000_p3[8:5]}};
        tmp_34_reg_3812_pp0_iter2_reg <= tmp_34_reg_3812;
        tmp_36_reg_3822 <= {{res_I_V_25_fu_1000_p3[8:6]}};
        tmp_36_reg_3822_pp0_iter2_reg <= tmp_36_reg_3822;
        tmp_44_reg_3832 <= {{res_I_V_25_fu_1000_p3[8:7]}};
        tmp_44_reg_3832_pp0_iter2_reg <= tmp_44_reg_3832;
        tmp_46_reg_3842 <= res_I_V_25_fu_1000_p3[32'd8];
        tmp_46_reg_3842_pp0_iter2_reg <= tmp_46_reg_3842;
        tmp_46_reg_3842_pp0_iter3_reg <= tmp_46_reg_3842_pp0_iter2_reg;
        trunc_ln58_1_reg_3777 <= trunc_ln58_1_fu_1214_p1;
        trunc_ln58_2_reg_3787 <= trunc_ln58_2_fu_1228_p1;
        trunc_ln58_3_reg_3797 <= trunc_ln58_3_fu_1242_p1;
        trunc_ln58_4_reg_3807 <= trunc_ln58_4_fu_1256_p1;
        trunc_ln58_4_reg_3807_pp0_iter2_reg <= trunc_ln58_4_reg_3807;
        trunc_ln58_5_reg_3817 <= trunc_ln58_5_fu_1270_p1;
        trunc_ln58_5_reg_3817_pp0_iter2_reg <= trunc_ln58_5_reg_3817;
        trunc_ln58_6_reg_3827 <= trunc_ln58_6_fu_1284_p1;
        trunc_ln58_6_reg_3827_pp0_iter2_reg <= trunc_ln58_6_reg_3827;
        trunc_ln58_7_reg_3837 <= trunc_ln58_7_fu_1298_p1;
        trunc_ln58_7_reg_3837_pp0_iter2_reg <= trunc_ln58_7_reg_3837;
        trunc_ln58_7_reg_3837_pp0_iter3_reg <= trunc_ln58_7_reg_3837_pp0_iter2_reg;
        trunc_ln841_reg_3695 <= trunc_ln841_fu_296_p1;
        x_l_FH_V_33_reg_3769[16 : 1] <= x_l_FH_V_33_fu_1206_p3[16 : 1];
        x_l_FH_V_39_reg_3867[16 : 1] <= x_l_FH_V_39_fu_1696_p3[16 : 1];
        x_l_FH_V_45_reg_3895[16 : 1] <= x_l_FH_V_45_fu_2080_p3[16 : 1];
        x_l_FH_V_51_reg_3920 <= x_l_FH_V_51_fu_2565_p3;
        x_l_FH_V_57_reg_3955 <= x_l_FH_V_57_fu_3123_p3;
        x_l_FL_V_17_reg_3929[16 : 12] <= x_l_FL_V_17_fu_2573_p3[16 : 12];
        x_l_FL_V_20_reg_3964[16 : 6] <= x_l_FL_V_20_fu_3131_p3[16 : 6];
        x_l_I_V_104_reg_3913 <= x_l_I_V_104_fu_2557_p3;
        x_l_I_V_110_reg_3948 <= x_l_I_V_110_fu_3115_p3;
        x_l_I_V_79_reg_3700 <= x_l_I_V_79_fu_730_p3;
        x_l_I_V_84_reg_3747 <= x_l_I_V_84_fu_1068_p3;
        x_l_I_V_85_reg_3758 <= x_l_I_V_85_fu_1194_p2;
        x_l_I_V_92_reg_3858 <= x_l_I_V_92_fu_1688_p3;
        x_l_I_V_98_reg_3886 <= x_l_I_V_98_fu_2072_p3;
        x_read_reg_3690 <= x_int_reg;
        x_read_reg_3690_pp0_iter1_reg <= x_read_reg_3690;
        x_read_reg_3690_pp0_iter2_reg <= x_read_reg_3690_pp0_iter1_reg;
        x_read_reg_3690_pp0_iter3_reg <= x_read_reg_3690_pp0_iter2_reg;
        x_read_reg_3690_pp0_iter4_reg <= x_read_reg_3690_pp0_iter3_reg;
        x_read_reg_3690_pp0_iter5_reg <= x_read_reg_3690_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln53_fu_3682_p3;
    end else begin
        ap_return = 'bx;
    end
end

assign add_ln813_fu_2152_p2 = ($signed(x_l_FH_V_45_reg_3895) + $signed(17'd131071));

assign and_ln318_10_fu_2479_p2 = (xor_ln1651_1_fu_2473_p2 & icmp_ln1653_10_fu_2461_p2);

assign and_ln318_11_fu_2663_p2 = (xor_ln1651_2_fu_2657_p2 & icmp_ln1653_11_fu_2647_p2);

assign and_ln318_12_fu_2846_p2 = (xor_ln1651_3_fu_2840_p2 & icmp_ln1653_12_fu_2828_p2);

assign and_ln318_13_fu_3037_p2 = (xor_ln1651_4_fu_3031_p2 & icmp_ln1653_13_fu_3019_p2);

assign and_ln318_14_fu_3228_p2 = (xor_ln1651_5_fu_3222_p2 & icmp_ln1653_14_fu_3212_p2);

assign and_ln318_15_fu_3411_p2 = (xor_ln1651_6_fu_3405_p2 & icmp_ln1653_15_fu_3393_p2);

assign and_ln318_16_fu_3592_p2 = (xor_ln1651_7_fu_3586_p2 & icmp_ln1653_16_fu_3574_p2);

assign and_ln318_17_fu_3505_p2 = (or_ln318_22_fu_3499_p2 & icmp_ln353_fu_3487_p2);

assign and_ln318_1_fu_1162_p2 = (xor_ln318_fu_1156_p2 & icmp_ln1653_1_fu_1144_p2);

assign and_ln318_2_fu_1383_p2 = (xor_ln318_1_fu_1377_p2 & icmp_ln1653_2_fu_1366_p2);

assign and_ln318_3_fu_1512_p2 = (xor_ln318_2_fu_1506_p2 & icmp_ln1653_3_fu_1494_p2);

assign and_ln318_4_fu_1644_p2 = (xor_ln318_3_fu_1638_p2 & icmp_ln1653_4_fu_1626_p2);

assign and_ln318_5_fu_1770_p2 = (xor_ln318_4_fu_1764_p2 & icmp_ln1653_5_fu_1754_p2);

assign and_ln318_6_fu_1896_p2 = (xor_ln318_5_fu_1890_p2 & icmp_ln1653_6_fu_1878_p2);

assign and_ln318_7_fu_2028_p2 = (xor_ln318_6_fu_2022_p2 & icmp_ln1653_7_fu_2010_p2);

assign and_ln318_8_fu_2146_p2 = (icmp_ln1653_8_fu_2136_p2 & icmp_ln1649_9_fu_2141_p2);

assign and_ln318_9_fu_2292_p2 = (xor_ln1651_fu_2286_p2 & icmp_ln1653_9_fu_2274_p2);

assign and_ln318_fu_1032_p2 = (icmp_ln318_reg_3723 & icmp_ln1653_fu_1026_p2);

assign and_ln331_1_fu_2497_p2 = (signbit_1_fu_2485_p2 & icmp_ln1653_10_fu_2461_p2);

assign and_ln331_2_fu_2679_p2 = (signbit_2_fu_2669_p2 & icmp_ln1653_11_fu_2647_p2);

assign and_ln331_3_fu_2864_p2 = (signbit_3_fu_2852_p2 & icmp_ln1653_12_fu_2828_p2);

assign and_ln331_4_fu_3055_p2 = (signbit_4_fu_3043_p2 & icmp_ln1653_13_fu_3019_p2);

assign and_ln331_5_fu_3244_p2 = (signbit_5_fu_3234_p2 & icmp_ln1653_14_fu_3212_p2);

assign and_ln331_6_fu_3429_p2 = (signbit_6_fu_3417_p2 & icmp_ln1653_15_fu_3393_p2);

assign and_ln331_fu_2310_p2 = (signbit_fu_2298_p2 & icmp_ln1653_9_fu_2274_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign icmp_ln1649_10_fu_2268_p2 = ((x_l_FH_V_47_fu_2204_p3 > mul_FH_V_8_fu_2247_p3) ? 1'b1 : 1'b0);

assign icmp_ln1649_11_fu_2455_p2 = ((x_l_FH_V_49_fu_2388_p3 > mul_FH_V_9_fu_2432_p4) ? 1'b1 : 1'b0);

assign icmp_ln1649_12_fu_2642_p2 = ((x_l_FH_V_51_reg_3920 > zext_ln818_1_fu_2625_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_13_fu_2822_p2 = ((x_l_FH_V_53_fu_2753_p3 > zext_ln818_2_fu_2804_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_14_fu_3013_p2 = ((x_l_FH_V_55_fu_2942_p3 > zext_ln818_3_fu_2995_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_15_fu_3207_p2 = ((x_l_FH_V_57_reg_3955 > zext_ln818_4_fu_3190_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_16_fu_3387_p2 = ((x_l_FH_V_59_fu_3318_p3 > zext_ln818_5_fu_3369_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_17_fu_3568_p2 = ((x_l_FH_V_61_fu_3511_p3 > zext_ln818_6_fu_3564_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_1_fu_1138_p2 = ((x_l_I_V_84_fu_1068_p3 > zext_ln1649_1_fu_1134_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_2_fu_1360_p2 = ((x_l_I_V_86_fu_1319_p3 > zext_ln1649_2_fu_1356_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_3_fu_1488_p2 = ((x_l_I_V_88_fu_1435_p3 > zext_ln1649_3_fu_1484_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_4_fu_1620_p2 = ((x_l_I_V_90_fu_1566_p3 > zext_ln1649_4_fu_1616_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_5_fu_1749_p2 = ((x_l_I_V_92_reg_3858 > zext_ln1649_5_fu_1745_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_6_fu_1872_p2 = ((x_l_I_V_94_fu_1820_p3 > zext_ln1649_6_fu_1868_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_7_fu_2004_p2 = ((x_l_I_V_96_fu_1950_p3 > zext_ln1649_7_fu_2000_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_8_fu_2131_p2 = ((x_l_I_V_98_reg_3886 > zext_ln1649_8_fu_2127_p1) ? 1'b1 : 1'b0);

assign icmp_ln1649_9_fu_2141_p2 = ((x_l_FH_V_45_reg_3895 > mul_FH_V_7_fu_2113_p3) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_1020_p2 = ((x_l_I_V_82_fu_992_p3 > zext_ln1649_fu_1016_p1) ? 1'b1 : 1'b0);

assign icmp_ln1650_11_fu_2491_p2 = ((x_l_FH_V_49_fu_2388_p3 < mul_FH_V_9_fu_2432_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_12_fu_2674_p2 = ((x_l_FH_V_51_reg_3920 < zext_ln818_1_fu_2625_p1) ? 1'b1 : 1'b0);

assign icmp_ln1650_13_fu_2858_p2 = ((x_l_FH_V_53_fu_2753_p3 < zext_ln818_2_fu_2804_p1) ? 1'b1 : 1'b0);

assign icmp_ln1650_14_fu_3049_p2 = ((x_l_FH_V_55_fu_2942_p3 < zext_ln818_3_fu_2995_p1) ? 1'b1 : 1'b0);

assign icmp_ln1650_15_fu_3239_p2 = ((x_l_FH_V_57_reg_3955 < zext_ln818_4_fu_3190_p1) ? 1'b1 : 1'b0);

assign icmp_ln1650_16_fu_3423_p2 = ((x_l_FH_V_59_fu_3318_p3 < zext_ln818_5_fu_3369_p1) ? 1'b1 : 1'b0);

assign icmp_ln1650_1_fu_1168_p2 = ((p_Val2_109_fu_1076_p3 < mul_FH_V_fu_1106_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_2_fu_1389_p2 = ((x_l_FH_V_33_reg_3769 < mul_FH_V_1_fu_1340_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_3_fu_1518_p2 = ((x_l_FH_V_35_fu_1443_p3 < mul_FH_V_2_fu_1468_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_4_fu_1650_p2 = ((x_l_FH_V_37_fu_1574_p3 < mul_FH_V_3_fu_1600_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_5_fu_1776_p2 = ((x_l_FH_V_39_reg_3867 < mul_FH_V_4_fu_1729_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_6_fu_1902_p2 = ((x_l_FH_V_41_fu_1827_p3 < mul_FH_V_5_fu_1852_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_7_fu_2034_p2 = ((x_l_FH_V_43_fu_1958_p3 < mul_FH_V_6_fu_1984_p4) ? 1'b1 : 1'b0);

assign icmp_ln1650_9_fu_2304_p2 = ((x_l_FH_V_47_fu_2204_p3 < mul_FH_V_8_fu_2247_p3) ? 1'b1 : 1'b0);

assign icmp_ln1650_fu_816_p2 = ((tmp_26_fu_806_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1651_1_fu_2467_p2 = ((x_l_FL_V_16_fu_2396_p3 < mul_FL_V_1_fu_2441_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_2_fu_2652_p2 = ((x_l_FL_V_17_reg_3929 < mul_FL_V_2_fu_2629_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_3_fu_2834_p2 = ((x_l_FL_V_18_fu_2760_p3 < mul_FL_V_3_fu_2808_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_4_fu_3025_p2 = ((x_l_FL_V_19_fu_2950_p3 < mul_FL_V_4_fu_2999_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_5_fu_3217_p2 = ((x_l_FL_V_20_reg_3964 < mul_FL_V_5_fu_3194_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_6_fu_3399_p2 = ((x_l_FL_V_21_fu_3325_p3 < mul_FL_V_6_fu_3373_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_7_fu_3580_p2 = ((x_l_FL_V_14_fu_3519_p3 < mul_FL_V_7_fu_3539_p3) ? 1'b1 : 1'b0);

assign icmp_ln1651_fu_2280_p2 = ((x_l_FL_V_15_fu_2211_p3 < mul_FL_V_fu_2254_p3) ? 1'b1 : 1'b0);

assign icmp_ln1653_10_fu_2461_p2 = ((x_l_FH_V_49_fu_2388_p3 == mul_FH_V_9_fu_2432_p4) ? 1'b1 : 1'b0);

assign icmp_ln1653_11_fu_2647_p2 = ((x_l_FH_V_51_reg_3920 == zext_ln818_1_fu_2625_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_12_fu_2828_p2 = ((x_l_FH_V_53_fu_2753_p3 == zext_ln818_2_fu_2804_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_13_fu_3019_p2 = ((x_l_FH_V_55_fu_2942_p3 == zext_ln818_3_fu_2995_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_14_fu_3212_p2 = ((x_l_FH_V_57_reg_3955 == zext_ln818_4_fu_3190_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_15_fu_3393_p2 = ((x_l_FH_V_59_fu_3318_p3 == zext_ln818_5_fu_3369_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_16_fu_3574_p2 = ((x_l_FH_V_61_fu_3511_p3 == zext_ln818_6_fu_3564_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_1_fu_1144_p2 = ((x_l_I_V_84_fu_1068_p3 == zext_ln1649_1_fu_1134_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_2_fu_1366_p2 = ((x_l_I_V_86_fu_1319_p3 == zext_ln1649_2_fu_1356_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_3_fu_1494_p2 = ((x_l_I_V_88_fu_1435_p3 == zext_ln1649_3_fu_1484_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_4_fu_1626_p2 = ((x_l_I_V_90_fu_1566_p3 == zext_ln1649_4_fu_1616_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_5_fu_1754_p2 = ((x_l_I_V_92_reg_3858 == zext_ln1649_5_fu_1745_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_6_fu_1878_p2 = ((x_l_I_V_94_fu_1820_p3 == zext_ln1649_6_fu_1868_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_7_fu_2010_p2 = ((x_l_I_V_96_fu_1950_p3 == zext_ln1649_7_fu_2000_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_8_fu_2136_p2 = ((x_l_I_V_98_reg_3886 == zext_ln1649_8_fu_2127_p1) ? 1'b1 : 1'b0);

assign icmp_ln1653_9_fu_2274_p2 = ((x_l_FH_V_47_fu_2204_p3 == mul_FH_V_8_fu_2247_p3) ? 1'b1 : 1'b0);

assign icmp_ln1653_fu_1026_p2 = ((x_l_I_V_82_fu_992_p3 == zext_ln1649_fu_1016_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_10_fu_2637_p2 = ((x_l_I_V_104_reg_3913 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_11_fu_2816_p2 = ((x_l_I_V_106_fu_2745_p3 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_12_fu_3007_p2 = ((x_l_I_V_108_fu_2934_p3 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_13_fu_3202_p2 = ((x_l_I_V_110_reg_3948 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_14_fu_3381_p2 = ((x_l_I_V_112_fu_3310_p3 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_1_fu_1150_p2 = ((p_Val2_109_fu_1076_p3 < mul_FH_V_fu_1106_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_2_fu_1372_p2 = ((x_l_FH_V_33_reg_3769 < mul_FH_V_1_fu_1340_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_3_fu_1500_p2 = ((x_l_FH_V_35_fu_1443_p3 < mul_FH_V_2_fu_1468_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_4_fu_1632_p2 = ((x_l_FH_V_37_fu_1574_p3 < mul_FH_V_3_fu_1600_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_5_fu_1759_p2 = ((x_l_FH_V_39_reg_3867 < mul_FH_V_4_fu_1729_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_6_fu_1884_p2 = ((x_l_FH_V_41_fu_1827_p3 < mul_FH_V_5_fu_1852_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_7_fu_2016_p2 = ((x_l_FH_V_43_fu_1958_p3 < mul_FH_V_6_fu_1984_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_8_fu_2262_p2 = ((x_l_I_V_100_fu_2197_p3 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_9_fu_2449_p2 = ((x_l_I_V_102_fu_2380_p3 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_800_p2 = ((tmp_25_fu_790_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln353_fu_3487_p2 = ((x_l_I_V_113_fu_3457_p3 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln443_1_fu_450_p2 = ((tmp_4_fu_436_p4 < zext_ln443_1_fu_446_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_2_fu_532_p2 = ((tmp_8_fu_518_p4 < zext_ln443_2_fu_528_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_3_fu_614_p2 = ((tmp_11_fu_600_p4 < zext_ln443_3_fu_610_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_4_fu_696_p2 = ((tmp_14_fu_682_p4 < zext_ln443_4_fu_692_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_5_fu_778_p2 = ((tmp_17_fu_764_p4 < zext_ln443_5_fu_774_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_6_fu_892_p2 = ((tmp_20_fu_878_p4 < zext_ln443_6_fu_888_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_7_fu_958_p2 = ((trunc_ln594_fu_950_p1 < zext_ln443_7_fu_954_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_fu_368_p2 = ((tmp_2_fu_354_p4 < zext_ln443_fu_364_p1) ? 1'b1 : 1'b0);

assign mul_FH_V_10_fu_2795_p4 = {{{{1'd0}, {res_I_V_25_reg_3733_pp0_iter4_reg}}}, {tmp_50_fu_2785_p4}};

assign mul_FH_V_11_fu_2986_p4 = {{{{1'd0}, {res_I_V_25_reg_3733_pp0_iter4_reg}}}, {tmp_51_fu_2976_p4}};

assign mul_FH_V_12_fu_3181_p4 = {{{{1'd0}, {res_I_V_25_reg_3733_pp0_iter5_reg}}}, {tmp_52_fu_3171_p4}};

assign mul_FH_V_13_fu_3360_p4 = {{{{1'd0}, {res_I_V_25_reg_3733_pp0_iter5_reg}}}, {tmp_53_fu_3350_p4}};

assign mul_FH_V_14_fu_3555_p4 = {{{{1'd0}, {res_I_V_25_reg_3733_pp0_iter5_reg}}}, {tmp_56_fu_3547_p3}};

assign mul_FH_V_1_fu_1340_p4 = {{{trunc_ln58_1_reg_3777}, {tmp_24_fu_1330_p4}}, {12'd2048}};

assign mul_FH_V_2_fu_1468_p4 = {{{trunc_ln58_2_reg_3787}, {tmp_28_fu_1458_p4}}, {10'd512}};

assign mul_FH_V_3_fu_1600_p4 = {{{trunc_ln58_3_reg_3797}, {tmp_30_fu_1590_p4}}, {8'd128}};

assign mul_FH_V_4_fu_1729_p4 = {{{trunc_ln58_4_reg_3807_pp0_iter2_reg}, {tmp_33_fu_1719_p4}}, {6'd32}};

assign mul_FH_V_5_fu_1852_p4 = {{{trunc_ln58_5_reg_3817_pp0_iter2_reg}, {tmp_35_fu_1842_p4}}, {4'd8}};

assign mul_FH_V_6_fu_1984_p4 = {{{trunc_ln58_6_reg_3827_pp0_iter2_reg}, {tmp_37_fu_1974_p4}}, {2'd2}};

assign mul_FH_V_7_fu_2113_p3 = {{trunc_ln58_7_reg_3837_pp0_iter3_reg}, {tmp_45_fu_2103_p4}};

assign mul_FH_V_8_fu_2247_p3 = {{res_I_V_25_reg_3733_pp0_iter3_reg}, {tmp_47_fu_2237_p4}};

assign mul_FH_V_9_fu_2432_p4 = {{{{1'd0}, {res_I_V_25_reg_3733_pp0_iter3_reg}}}, {tmp_48_fu_2422_p4}};

assign mul_FH_V_fu_1106_p4 = {{{trunc_ln58_fu_1102_p1}, {tmp_22_fu_1092_p4}}, {14'd8192}};

assign mul_FH_V_s_fu_2616_p4 = {{{{1'd0}, {res_I_V_25_reg_3733_pp0_iter4_reg}}}, {tmp_49_fu_2606_p4}};

assign mul_FL_V_1_fu_2441_p3 = {{tmp_38_fu_2412_p4}, {13'd4096}};

assign mul_FL_V_2_fu_2629_p3 = {{tmp_39_fu_2596_p4}, {11'd1024}};

assign mul_FL_V_3_fu_2808_p3 = {{tmp_40_fu_2775_p4}, {9'd256}};

assign mul_FL_V_4_fu_2999_p3 = {{tmp_41_fu_2966_p4}, {7'd64}};

assign mul_FL_V_5_fu_3194_p3 = {{tmp_42_fu_3161_p4}, {5'd16}};

assign mul_FL_V_6_fu_3373_p3 = {{tmp_43_fu_3340_p4}, {3'd4}};

assign mul_FL_V_7_fu_3539_p3 = {{trunc_ln58_8_fu_3535_p1}, {1'd1}};

assign mul_FL_V_fu_2254_p3 = {{tmp_32_fu_2227_p4}, {15'd16384}};

assign or_ln318_10_fu_2374_p2 = (or_ln318_9_fu_2368_p2 | icmp_ln318_8_fu_2262_p2);

assign or_ln318_11_fu_2545_p2 = (icmp_ln1649_11_fu_2455_p2 | and_ln318_10_fu_2479_p2);

assign or_ln318_12_fu_2551_p2 = (or_ln318_11_fu_2545_p2 | icmp_ln318_9_fu_2449_p2);

assign or_ln318_13_fu_2733_p2 = (icmp_ln1649_12_fu_2642_p2 | and_ln318_11_fu_2663_p2);

assign or_ln318_14_fu_2739_p2 = (or_ln318_13_fu_2733_p2 | icmp_ln318_10_fu_2637_p2);

assign or_ln318_15_fu_2922_p2 = (icmp_ln1649_13_fu_2822_p2 | and_ln318_12_fu_2846_p2);

assign or_ln318_16_fu_2928_p2 = (or_ln318_15_fu_2922_p2 | icmp_ln318_11_fu_2816_p2);

assign or_ln318_17_fu_3103_p2 = (icmp_ln1649_14_fu_3013_p2 | and_ln318_13_fu_3037_p2);

assign or_ln318_18_fu_3109_p2 = (or_ln318_17_fu_3103_p2 | icmp_ln318_12_fu_3007_p2);

assign or_ln318_19_fu_3298_p2 = (icmp_ln1649_15_fu_3207_p2 | and_ln318_14_fu_3228_p2);

assign or_ln318_1_fu_1200_p2 = (icmp_ln1649_1_fu_1138_p2 | and_ln318_1_fu_1162_p2);

assign or_ln318_20_fu_3304_p2 = (or_ln318_19_fu_3298_p2 | icmp_ln318_13_fu_3202_p2);

assign or_ln318_21_fu_3493_p2 = (icmp_ln1649_16_fu_3387_p2 | and_ln318_15_fu_3411_p2);

assign or_ln318_22_fu_3499_p2 = (or_ln318_21_fu_3493_p2 | icmp_ln318_14_fu_3381_p2);

assign or_ln318_23_fu_3608_p2 = (icmp_ln1649_17_fu_3568_p2 | and_ln318_16_fu_3592_p2);

assign or_ln318_24_fu_3614_p2 = (or_ln318_23_fu_3608_p2 | and_ln318_17_fu_3505_p2);

assign or_ln318_2_fu_1429_p2 = (icmp_ln1649_2_fu_1360_p2 | and_ln318_2_fu_1383_p2);

assign or_ln318_3_fu_1560_p2 = (icmp_ln1649_3_fu_1488_p2 | and_ln318_3_fu_1512_p2);

assign or_ln318_4_fu_1682_p2 = (icmp_ln1649_4_fu_1620_p2 | and_ln318_4_fu_1644_p2);

assign or_ln318_5_fu_1814_p2 = (icmp_ln1649_5_fu_1749_p2 | and_ln318_5_fu_1770_p2);

assign or_ln318_6_fu_1944_p2 = (icmp_ln1649_6_fu_1872_p2 | and_ln318_6_fu_1896_p2);

assign or_ln318_7_fu_2066_p2 = (icmp_ln1649_7_fu_2004_p2 | and_ln318_7_fu_2028_p2);

assign or_ln318_8_fu_2191_p2 = (icmp_ln1649_8_fu_2131_p2 | and_ln318_8_fu_2146_p2);

assign or_ln318_9_fu_2368_p2 = (icmp_ln1649_10_fu_2268_p2 | and_ln318_9_fu_2292_p2);

assign or_ln318_fu_1062_p2 = (icmp_ln1649_fu_1020_p2 | and_ln318_fu_1032_p2);

assign or_ln331_1_fu_2503_p2 = (icmp_ln1650_11_fu_2491_p2 | and_ln331_1_fu_2497_p2);

assign or_ln331_2_fu_2685_p2 = (icmp_ln1650_12_fu_2674_p2 | and_ln331_2_fu_2679_p2);

assign or_ln331_3_fu_2870_p2 = (icmp_ln1650_13_fu_2858_p2 | and_ln331_3_fu_2864_p2);

assign or_ln331_4_fu_3061_p2 = (icmp_ln1650_14_fu_3049_p2 | and_ln331_4_fu_3055_p2);

assign or_ln331_5_fu_3250_p2 = (icmp_ln1650_15_fu_3239_p2 | and_ln331_5_fu_3244_p2);

assign or_ln331_6_fu_3435_p2 = (icmp_ln1650_16_fu_3423_p2 | and_ln331_6_fu_3429_p2);

assign or_ln331_fu_2316_p2 = (icmp_ln1650_9_fu_2304_p2 | and_ln331_fu_2310_p2);

assign p_Result_44_fu_3644_p3 = res_FH_l_V_fu_3632_p2[32'd17];

assign p_Result_47_fu_308_p5 = {{zext_ln818_fu_292_p1[19:19]}, {3'd6}, {zext_ln818_fu_292_p1[15:0]}};

assign p_Result_48_fu_380_p5 = {{x_l_I_V_74_fu_320_p3[19:18]}, {sub_ln277_fu_374_p2}, {x_l_I_V_74_fu_320_p3[13:0]}};

assign p_Result_49_fu_392_p4 = {res_I_V_18_fu_328_p3[9 - 1:8], |(1'd1), res_I_V_18_fu_328_p3[6:0]};

assign p_Result_50_fu_462_p5 = {{x_l_I_V_75_fu_402_p3[19:17]}, {sub_ln277_1_fu_456_p2}, {x_l_I_V_75_fu_402_p3[11:0]}};

assign p_Result_51_fu_474_p4 = {res_I_V_19_fu_410_p3[9 - 1:7], |(1'd1), res_I_V_19_fu_410_p3[5:0]};

assign p_Result_52_fu_544_p5 = {{x_l_I_V_76_fu_484_p3[19:16]}, {sub_ln277_2_fu_538_p2}, {x_l_I_V_76_fu_484_p3[9:0]}};

assign p_Result_53_fu_556_p4 = {res_I_V_20_fu_492_p3[9 - 1:6], |(1'd1), res_I_V_20_fu_492_p3[4:0]};

assign p_Result_54_fu_626_p5 = {{x_l_I_V_77_fu_566_p3[19:15]}, {sub_ln277_3_fu_620_p2}, {x_l_I_V_77_fu_566_p3[7:0]}};

assign p_Result_55_fu_638_p4 = {res_I_V_21_fu_574_p3[9 - 1:5], |(1'd1), res_I_V_21_fu_574_p3[3:0]};

assign p_Result_56_fu_708_p5 = {{x_l_I_V_78_fu_648_p3[19:14]}, {sub_ln277_4_fu_702_p2}, {x_l_I_V_78_fu_648_p3[5:0]}};

assign p_Result_57_fu_720_p4 = {res_I_V_22_fu_656_p3[9 - 1:4], |(1'd1), res_I_V_22_fu_656_p3[2:0]};

assign p_Result_58_fu_829_p5 = {{x_l_I_V_79_reg_3700[19:13]}, {sub_ln277_5_reg_3718}, {x_l_I_V_79_reg_3700[3:0]}};

assign p_Result_59_fu_839_p4 = {res_I_V_23_reg_3706[9 - 1:3], |(1'd1), res_I_V_23_reg_3706[1:0]};

assign p_Result_60_fu_904_p5 = {{x_l_I_V_80_fu_848_p3[19:12]}, {sub_ln277_6_fu_898_p2}, {x_l_I_V_80_fu_848_p3[1:0]}};

assign p_Result_61_fu_916_p4 = {res_I_V_24_fu_854_p3[9 - 1:2], |(1'd1), res_I_V_24_fu_854_p3[0:0]};

assign p_Result_62_fu_970_p5 = {{x_l_I_V_81_fu_926_p3[19:11]}, {sub_ln277_7_fu_964_p2}};

assign p_Result_63_fu_982_p4 = {res_I_V_fu_934_p3[9-1:1], |(1'd1)};

assign p_Result_64_fu_1310_p4 = {res_FH_V_33_reg_3752[17 - 1:16], |(1'd1), res_FH_V_33_reg_3752[14:0]};

assign p_Result_65_fu_1419_p4 = {res_FH_V_34_fu_1324_p3[17 - 1:15], |(1'd1), res_FH_V_34_fu_1324_p3[13:0]};

assign p_Result_66_fu_1550_p4 = {res_FH_V_35_fu_1450_p3[17 - 1:14], |(1'd1), res_FH_V_35_fu_1450_p3[12:0]};

assign p_Result_67_fu_1704_p4 = {res_FH_V_36_reg_3847[17 - 1:13], |(1'd1), res_FH_V_36_reg_3847[11:0]};

assign p_Result_68_fu_1804_p4 = {res_FH_V_37_fu_1713_p3[17 - 1:12], |(1'd1), res_FH_V_37_fu_1713_p3[10:0]};

assign p_Result_69_fu_1934_p4 = {res_FH_V_38_fu_1834_p3[17 - 1:11], |(1'd1), res_FH_V_38_fu_1834_p3[9:0]};

assign p_Result_70_fu_2088_p4 = {res_FH_V_39_reg_3875[17 - 1:10], |(1'd1), res_FH_V_39_reg_3875[8:0]};

assign p_Result_71_fu_2181_p4 = {res_FH_V_fu_2097_p3[17 - 1:9], |(1'd1), res_FH_V_fu_2097_p3[7:0]};

assign p_Result_72_fu_2358_p4 = {res_FH_V_40_fu_2219_p3[17 - 1:8], |(1'd1), res_FH_V_40_fu_2219_p3[6:0]};

assign p_Result_73_fu_2581_p4 = {res_FH_V_41_reg_3902[17 - 1:7], |(1'd1), res_FH_V_41_reg_3902[5:0]};

assign p_Result_74_fu_2723_p4 = {res_FH_V_42_fu_2590_p3[17 - 1:6], |(1'd1), res_FH_V_42_fu_2590_p3[4:0]};

assign p_Result_75_fu_2912_p4 = {res_FH_V_43_fu_2767_p3[17 - 1:5], |(1'd1), res_FH_V_43_fu_2767_p3[3:0]};

assign p_Result_76_fu_3146_p4 = {res_FH_V_44_reg_3937[17 - 1:4], |(1'd1), res_FH_V_44_reg_3937[2:0]};

assign p_Result_77_fu_3288_p4 = {res_FH_V_45_fu_3155_p3[17 - 1:3], |(1'd1), res_FH_V_45_fu_3155_p3[1:0]};

assign p_Result_78_fu_3477_p4 = {res_FH_V_46_fu_3332_p3[17 - 1:2], |(1'd1), res_FH_V_46_fu_3332_p3[0:0]};

assign p_Result_79_fu_3598_p4 = {res_FH_V_47_fu_3527_p3[17-1:1], |(1'd1)};

assign p_Result_s_fu_3139_p3 = x_read_reg_3690_pp0_iter5_reg[32'd32];

assign p_Val2_109_fu_1076_p3 = ((or_ln318_fu_1062_p2[0:0] == 1'b1) ? x_l_FH_V_32_fu_1050_p2 : x_l_FH_V_31_fu_822_p3);

assign p_Val2_110_fu_2162_p3 = ((icmp_ln1649_9_fu_2141_p2[0:0] == 1'b1) ? x_l_I_V_98_reg_3886 : x_l_I_V_50_fu_2157_p2);

assign res_FH_V_31_fu_3620_p3 = ((or_ln318_24_fu_3614_p2[0:0] == 1'b1) ? p_Result_79_fu_3598_p4 : res_FH_V_47_fu_3527_p3);

assign res_FH_V_33_fu_1084_p3 = ((or_ln318_fu_1062_p2[0:0] == 1'b1) ? 17'd65536 : 17'd0);

assign res_FH_V_34_fu_1324_p3 = ((or_ln318_1_reg_3763[0:0] == 1'b1) ? p_Result_64_fu_1310_p4 : res_FH_V_33_reg_3752);

assign res_FH_V_35_fu_1450_p3 = ((or_ln318_2_fu_1429_p2[0:0] == 1'b1) ? p_Result_65_fu_1419_p4 : res_FH_V_34_fu_1324_p3);

assign res_FH_V_36_fu_1582_p3 = ((or_ln318_3_fu_1560_p2[0:0] == 1'b1) ? p_Result_66_fu_1550_p4 : res_FH_V_35_fu_1450_p3);

assign res_FH_V_37_fu_1713_p3 = ((or_ln318_4_reg_3853[0:0] == 1'b1) ? p_Result_67_fu_1704_p4 : res_FH_V_36_reg_3847);

assign res_FH_V_38_fu_1834_p3 = ((or_ln318_5_fu_1814_p2[0:0] == 1'b1) ? p_Result_68_fu_1804_p4 : res_FH_V_37_fu_1713_p3);

assign res_FH_V_39_fu_1966_p3 = ((or_ln318_6_fu_1944_p2[0:0] == 1'b1) ? p_Result_69_fu_1934_p4 : res_FH_V_38_fu_1834_p3);

assign res_FH_V_40_fu_2219_p3 = ((or_ln318_8_fu_2191_p2[0:0] == 1'b1) ? p_Result_71_fu_2181_p4 : res_FH_V_fu_2097_p3);

assign res_FH_V_41_fu_2404_p3 = ((or_ln318_10_fu_2374_p2[0:0] == 1'b1) ? p_Result_72_fu_2358_p4 : res_FH_V_40_fu_2219_p3);

assign res_FH_V_42_fu_2590_p3 = ((or_ln318_12_reg_3908[0:0] == 1'b1) ? p_Result_73_fu_2581_p4 : res_FH_V_41_reg_3902);

assign res_FH_V_43_fu_2767_p3 = ((or_ln318_14_fu_2739_p2[0:0] == 1'b1) ? p_Result_74_fu_2723_p4 : res_FH_V_42_fu_2590_p3);

assign res_FH_V_44_fu_2958_p3 = ((or_ln318_16_fu_2928_p2[0:0] == 1'b1) ? p_Result_75_fu_2912_p4 : res_FH_V_43_fu_2767_p3);

assign res_FH_V_45_fu_3155_p3 = ((or_ln318_18_reg_3943[0:0] == 1'b1) ? p_Result_76_fu_3146_p4 : res_FH_V_44_reg_3937);

assign res_FH_V_46_fu_3332_p3 = ((or_ln318_20_fu_3304_p2[0:0] == 1'b1) ? p_Result_77_fu_3288_p4 : res_FH_V_45_fu_3155_p3);

assign res_FH_V_47_fu_3527_p3 = ((or_ln318_22_fu_3499_p2[0:0] == 1'b1) ? p_Result_78_fu_3477_p4 : res_FH_V_46_fu_3332_p3);

assign res_FH_V_48_fu_3638_p2 = (res_FH_V_31_fu_3620_p3 + 17'd1);

assign res_FH_V_fu_2097_p3 = ((or_ln318_7_reg_3881[0:0] == 1'b1) ? p_Result_70_fu_2088_p4 : res_FH_V_39_reg_3875);

assign res_FH_l_V_fu_3632_p2 = (zext_ln813_7_fu_3628_p1 + 18'd1);

assign res_I_V_16_fu_3652_p2 = (res_I_V_25_reg_3733_pp0_iter5_reg + 9'd1);

assign res_I_V_18_fu_328_p3 = ((tmp_fu_300_p3[0:0] == 1'b1) ? 9'd256 : 9'd0);

assign res_I_V_19_fu_410_p3 = ((icmp_ln443_fu_368_p2[0:0] == 1'b1) ? res_I_V_18_fu_328_p3 : p_Result_49_fu_392_p4);

assign res_I_V_20_fu_492_p3 = ((icmp_ln443_1_fu_450_p2[0:0] == 1'b1) ? res_I_V_19_fu_410_p3 : p_Result_51_fu_474_p4);

assign res_I_V_21_fu_574_p3 = ((icmp_ln443_2_fu_532_p2[0:0] == 1'b1) ? res_I_V_20_fu_492_p3 : p_Result_53_fu_556_p4);

assign res_I_V_22_fu_656_p3 = ((icmp_ln443_3_fu_614_p2[0:0] == 1'b1) ? res_I_V_21_fu_574_p3 : p_Result_55_fu_638_p4);

assign res_I_V_23_fu_738_p3 = ((icmp_ln443_4_fu_696_p2[0:0] == 1'b1) ? res_I_V_22_fu_656_p3 : p_Result_57_fu_720_p4);

assign res_I_V_24_fu_854_p3 = ((icmp_ln443_5_reg_3712[0:0] == 1'b1) ? res_I_V_23_reg_3706 : p_Result_59_fu_839_p4);

assign res_I_V_25_fu_1000_p3 = ((icmp_ln443_7_fu_958_p2[0:0] == 1'b1) ? res_I_V_fu_934_p3 : p_Result_63_fu_982_p4);

assign res_I_V_26_fu_3657_p3 = ((p_Result_44_fu_3644_p3[0:0] == 1'b1) ? res_I_V_16_fu_3652_p2 : res_I_V_25_reg_3733_pp0_iter5_reg);

assign res_I_V_fu_934_p3 = ((icmp_ln443_6_fu_892_p2[0:0] == 1'b1) ? res_I_V_24_fu_854_p3 : p_Result_61_fu_916_p4);

assign select_ln53_fu_3682_p3 = ((p_Result_s_fu_3139_p3[0:0] == 1'b1) ? 25'd0 : trunc_ln4_fu_3674_p3);

assign signbit_1_fu_2485_p2 = ((x_l_FL_V_16_fu_2396_p3 < mul_FL_V_1_fu_2441_p3) ? 1'b1 : 1'b0);

assign signbit_2_fu_2669_p2 = ((x_l_FL_V_17_reg_3929 < mul_FL_V_2_fu_2629_p3) ? 1'b1 : 1'b0);

assign signbit_3_fu_2852_p2 = ((x_l_FL_V_18_fu_2760_p3 < mul_FL_V_3_fu_2808_p3) ? 1'b1 : 1'b0);

assign signbit_4_fu_3043_p2 = ((x_l_FL_V_19_fu_2950_p3 < mul_FL_V_4_fu_2999_p3) ? 1'b1 : 1'b0);

assign signbit_5_fu_3234_p2 = ((x_l_FL_V_20_reg_3964 < mul_FL_V_5_fu_3194_p3) ? 1'b1 : 1'b0);

assign signbit_6_fu_3417_p2 = ((x_l_FL_V_21_fu_3325_p3 < mul_FL_V_6_fu_3373_p3) ? 1'b1 : 1'b0);

assign signbit_fu_2298_p2 = ((x_l_FL_V_15_fu_2211_p3 < mul_FL_V_fu_2254_p3) ? 1'b1 : 1'b0);

assign sub_ln277_1_fu_456_p2 = (tmp_4_fu_436_p4 - zext_ln443_1_fu_446_p1);

assign sub_ln277_2_fu_538_p2 = (tmp_8_fu_518_p4 - zext_ln443_2_fu_528_p1);

assign sub_ln277_3_fu_620_p2 = (tmp_11_fu_600_p4 - zext_ln443_3_fu_610_p1);

assign sub_ln277_4_fu_702_p2 = (tmp_14_fu_682_p4 - zext_ln443_4_fu_692_p1);

assign sub_ln277_5_fu_784_p2 = (tmp_17_fu_764_p4 - zext_ln443_5_fu_774_p1);

assign sub_ln277_6_fu_898_p2 = (tmp_20_fu_878_p4 - zext_ln443_6_fu_888_p1);

assign sub_ln277_7_fu_964_p2 = (trunc_ln594_fu_950_p1 - zext_ln443_7_fu_954_p1);

assign sub_ln277_fu_374_p2 = (tmp_2_fu_354_p4 - zext_ln443_fu_364_p1);

assign sub_ln813_11_fu_2513_p2 = (x_l_FH_V_49_fu_2388_p3 - zext_ln813_1_fu_2509_p1);

assign sub_ln813_14_fu_2695_p2 = (x_l_FH_V_51_reg_3920 - zext_ln813_2_fu_2691_p1);

assign sub_ln813_17_fu_2880_p2 = (x_l_FH_V_53_fu_2753_p3 - zext_ln813_3_fu_2876_p1);

assign sub_ln813_20_fu_3071_p2 = (x_l_FH_V_55_fu_2942_p3 - zext_ln813_4_fu_3067_p1);

assign sub_ln813_23_fu_3260_p2 = (x_l_FH_V_57_reg_3955 - zext_ln813_5_fu_3256_p1);

assign sub_ln813_26_fu_3445_p2 = (x_l_FH_V_59_fu_3318_p3 - zext_ln813_6_fu_3441_p1);

assign sub_ln813_fu_2326_p2 = (x_l_FH_V_47_fu_2204_p3 - zext_ln813_fu_2322_p1);

assign tmp_10_fu_592_p3 = {{tmp_9_fu_582_p4}, {1'd1}};

assign tmp_11_fu_600_p4 = {{x_l_I_V_77_fu_566_p3[14:8]}};

assign tmp_12_fu_664_p4 = {{res_I_V_22_fu_656_p3[8:3]}};

assign tmp_13_fu_674_p3 = {{tmp_12_fu_664_p4}, {1'd1}};

assign tmp_14_fu_682_p4 = {{x_l_I_V_78_fu_648_p3[13:6]}};

assign tmp_15_fu_746_p4 = {{res_I_V_23_fu_738_p3[8:2]}};

assign tmp_16_fu_756_p3 = {{tmp_15_fu_746_p4}, {1'd1}};

assign tmp_17_fu_764_p4 = {{x_l_I_V_79_fu_730_p3[12:4]}};

assign tmp_18_fu_860_p4 = {{res_I_V_24_fu_854_p3[8:1]}};

assign tmp_19_fu_870_p3 = {{tmp_18_fu_860_p4}, {1'd1}};

assign tmp_1_fu_346_p3 = {{tmp_s_fu_336_p4}, {1'd1}};

assign tmp_20_fu_878_p4 = {{x_l_I_V_80_fu_848_p3[11:2]}};

assign tmp_21_fu_942_p3 = {{res_I_V_fu_934_p3}, {1'd1}};

assign tmp_22_fu_1092_p4 = {{res_FH_V_33_fu_1084_p3[16:15]}};

assign tmp_23_fu_1116_p4 = {{res_I_V_25_fu_1000_p3[8:1]}};

assign tmp_24_fu_1330_p4 = {{res_FH_V_34_fu_1324_p3[16:14]}};

assign tmp_25_fu_790_p4 = {{x_int_reg[15:14]}};

assign tmp_26_fu_806_p4 = {{x_int_reg[15:14]}};

assign tmp_28_fu_1458_p4 = {{res_FH_V_35_fu_1450_p3[16:13]}};

assign tmp_2_fu_354_p4 = {{x_l_I_V_74_fu_320_p3[17:14]}};

assign tmp_30_fu_1590_p4 = {{res_FH_V_36_fu_1582_p3[16:12]}};

assign tmp_32_fu_2227_p4 = {{res_FH_V_40_fu_2219_p3[8:7]}};

assign tmp_33_fu_1719_p4 = {{res_FH_V_37_fu_1713_p3[16:11]}};

assign tmp_35_fu_1842_p4 = {{res_FH_V_38_fu_1834_p3[16:10]}};

assign tmp_37_fu_1974_p4 = {{res_FH_V_39_fu_1966_p3[16:9]}};

assign tmp_38_fu_2412_p4 = {{res_FH_V_41_fu_2404_p3[9:6]}};

assign tmp_39_fu_2596_p4 = {{res_FH_V_42_fu_2590_p3[10:5]}};

assign tmp_3_fu_418_p4 = {{res_I_V_19_fu_410_p3[8:6]}};

assign tmp_40_fu_2775_p4 = {{res_FH_V_43_fu_2767_p3[11:4]}};

assign tmp_41_fu_2966_p4 = {{res_FH_V_44_fu_2958_p3[12:3]}};

assign tmp_42_fu_3161_p4 = {{res_FH_V_45_fu_3155_p3[13:2]}};

assign tmp_43_fu_3340_p4 = {{res_FH_V_46_fu_3332_p3[14:1]}};

assign tmp_45_fu_2103_p4 = {{res_FH_V_fu_2097_p3[16:8]}};

assign tmp_47_fu_2237_p4 = {{res_FH_V_40_fu_2219_p3[16:9]}};

assign tmp_48_fu_2422_p4 = {{res_FH_V_41_fu_2404_p3[16:10]}};

assign tmp_49_fu_2606_p4 = {{res_FH_V_42_fu_2590_p3[16:11]}};

assign tmp_4_fu_436_p4 = {{x_l_I_V_75_fu_402_p3[16:12]}};

assign tmp_50_fu_2785_p4 = {{res_FH_V_43_fu_2767_p3[16:12]}};

assign tmp_51_fu_2976_p4 = {{res_FH_V_44_fu_2958_p3[16:13]}};

assign tmp_52_fu_3171_p4 = {{res_FH_V_45_fu_3155_p3[16:14]}};

assign tmp_53_fu_3350_p4 = {{res_FH_V_46_fu_3332_p3[16:15]}};

assign tmp_54_fu_3664_p4 = {{res_FH_V_48_fu_3638_p2[16:1]}};

assign tmp_56_fu_3547_p3 = res_FH_V_47_fu_3527_p3[32'd16];

assign tmp_5_fu_500_p4 = {{res_I_V_20_fu_492_p3[8:5]}};

assign tmp_6_fu_428_p3 = {{tmp_3_fu_418_p4}, {1'd1}};

assign tmp_7_fu_510_p3 = {{tmp_5_fu_500_p4}, {1'd1}};

assign tmp_8_fu_518_p4 = {{x_l_I_V_76_fu_484_p3[15:10]}};

assign tmp_9_fu_582_p4 = {{res_I_V_21_fu_574_p3[8:4]}};

assign tmp_fu_300_p3 = x_int_reg[32'd32];

assign tmp_s_fu_336_p4 = {{res_I_V_18_fu_328_p3[8:7]}};

assign trunc_ln1649_1_fu_1126_p3 = {{1'd0}, {tmp_23_fu_1116_p4}};

assign trunc_ln1649_2_fu_1349_p3 = {{1'd0}, {tmp_27_reg_3782}};

assign trunc_ln1649_3_fu_1477_p3 = {{1'd0}, {tmp_29_reg_3792}};

assign trunc_ln1649_4_fu_1609_p3 = {{1'd0}, {tmp_31_reg_3802}};

assign trunc_ln1649_5_fu_1738_p3 = {{1'd0}, {tmp_34_reg_3812_pp0_iter2_reg}};

assign trunc_ln1649_6_fu_1861_p3 = {{1'd0}, {tmp_36_reg_3822_pp0_iter2_reg}};

assign trunc_ln1649_7_fu_1993_p3 = {{1'd0}, {tmp_44_reg_3832_pp0_iter2_reg}};

assign trunc_ln1649_8_fu_2120_p3 = {{1'd0}, {tmp_46_reg_3842_pp0_iter3_reg}};

assign trunc_ln2_fu_1008_p3 = {{1'd0}, {res_I_V_25_fu_1000_p3}};

assign trunc_ln4_fu_3674_p3 = {{res_I_V_26_fu_3657_p3}, {tmp_54_fu_3664_p4}};

assign trunc_ln58_1_fu_1214_p1 = res_I_V_25_fu_1000_p3[1:0];

assign trunc_ln58_2_fu_1228_p1 = res_I_V_25_fu_1000_p3[2:0];

assign trunc_ln58_3_fu_1242_p1 = res_I_V_25_fu_1000_p3[3:0];

assign trunc_ln58_4_fu_1256_p1 = res_I_V_25_fu_1000_p3[4:0];

assign trunc_ln58_5_fu_1270_p1 = res_I_V_25_fu_1000_p3[5:0];

assign trunc_ln58_6_fu_1284_p1 = res_I_V_25_fu_1000_p3[6:0];

assign trunc_ln58_7_fu_1298_p1 = res_I_V_25_fu_1000_p3[7:0];

assign trunc_ln58_8_fu_3535_p1 = res_FH_V_47_fu_3527_p3[15:0];

assign trunc_ln58_fu_1102_p1 = res_I_V_25_fu_1000_p3[0:0];

assign trunc_ln594_fu_950_p1 = x_l_I_V_81_fu_926_p3[10:0];

assign trunc_ln841_fu_296_p1 = x_int_reg[15:0];

assign trunc_ln_fu_282_p4 = {{x_int_reg[32:16]}};

assign x_l_FH_V_31_fu_822_p3 = {{trunc_ln841_reg_3695}, {1'd0}};

assign x_l_FH_V_32_fu_1050_p2 = ($signed(x_l_FH_V_31_fu_822_p3) + $signed(17'd98304));

assign x_l_FH_V_33_fu_1206_p3 = ((or_ln318_1_fu_1200_p2[0:0] == 1'b1) ? x_l_FH_V_fu_1188_p2 : p_Val2_109_fu_1076_p3);

assign x_l_FH_V_34_fu_1408_p2 = (x_l_FH_V_33_reg_3769 - mul_FH_V_1_fu_1340_p4);

assign x_l_FH_V_35_fu_1443_p3 = ((or_ln318_2_fu_1429_p2[0:0] == 1'b1) ? x_l_FH_V_34_fu_1408_p2 : x_l_FH_V_33_reg_3769);

assign x_l_FH_V_36_fu_1538_p2 = (x_l_FH_V_35_fu_1443_p3 - mul_FH_V_2_fu_1468_p4);

assign x_l_FH_V_37_fu_1574_p3 = ((or_ln318_3_fu_1560_p2[0:0] == 1'b1) ? x_l_FH_V_36_fu_1538_p2 : x_l_FH_V_35_fu_1443_p3);

assign x_l_FH_V_38_fu_1670_p2 = (x_l_FH_V_37_fu_1574_p3 - mul_FH_V_3_fu_1600_p4);

assign x_l_FH_V_39_fu_1696_p3 = ((or_ln318_4_fu_1682_p2[0:0] == 1'b1) ? x_l_FH_V_38_fu_1670_p2 : x_l_FH_V_37_fu_1574_p3);

assign x_l_FH_V_40_fu_1793_p2 = (x_l_FH_V_39_reg_3867 - mul_FH_V_4_fu_1729_p4);

assign x_l_FH_V_41_fu_1827_p3 = ((or_ln318_5_fu_1814_p2[0:0] == 1'b1) ? x_l_FH_V_40_fu_1793_p2 : x_l_FH_V_39_reg_3867);

assign x_l_FH_V_42_fu_1922_p2 = (x_l_FH_V_41_fu_1827_p3 - mul_FH_V_5_fu_1852_p4);

assign x_l_FH_V_43_fu_1958_p3 = ((or_ln318_6_fu_1944_p2[0:0] == 1'b1) ? x_l_FH_V_42_fu_1922_p2 : x_l_FH_V_41_fu_1827_p3);

assign x_l_FH_V_44_fu_2054_p2 = (x_l_FH_V_43_fu_1958_p3 - mul_FH_V_6_fu_1984_p4);

assign x_l_FH_V_45_fu_2080_p3 = ((or_ln318_7_fu_2066_p2[0:0] == 1'b1) ? x_l_FH_V_44_fu_2054_p2 : x_l_FH_V_43_fu_1958_p3);

assign x_l_FH_V_46_fu_2169_p2 = (add_ln813_fu_2152_p2 - mul_FH_V_7_fu_2113_p3);

assign x_l_FH_V_47_fu_2204_p3 = ((or_ln318_8_fu_2191_p2[0:0] == 1'b1) ? x_l_FH_V_46_fu_2169_p2 : x_l_FH_V_45_reg_3895);

assign x_l_FH_V_48_fu_2346_p2 = (sub_ln813_fu_2326_p2 - mul_FH_V_8_fu_2247_p3);

assign x_l_FH_V_49_fu_2388_p3 = ((or_ln318_10_fu_2374_p2[0:0] == 1'b1) ? x_l_FH_V_48_fu_2346_p2 : x_l_FH_V_47_fu_2204_p3);

assign x_l_FH_V_50_fu_2533_p2 = (sub_ln813_11_fu_2513_p2 - mul_FH_V_9_fu_2432_p4);

assign x_l_FH_V_51_fu_2565_p3 = ((or_ln318_12_fu_2551_p2[0:0] == 1'b1) ? x_l_FH_V_50_fu_2533_p2 : x_l_FH_V_49_fu_2388_p3);

assign x_l_FH_V_52_fu_2712_p2 = (sub_ln813_14_fu_2695_p2 - zext_ln818_1_fu_2625_p1);

assign x_l_FH_V_53_fu_2753_p3 = ((or_ln318_14_fu_2739_p2[0:0] == 1'b1) ? x_l_FH_V_52_fu_2712_p2 : x_l_FH_V_51_reg_3920);

assign x_l_FH_V_54_fu_2900_p2 = (sub_ln813_17_fu_2880_p2 - zext_ln818_2_fu_2804_p1);

assign x_l_FH_V_55_fu_2942_p3 = ((or_ln318_16_fu_2928_p2[0:0] == 1'b1) ? x_l_FH_V_54_fu_2900_p2 : x_l_FH_V_53_fu_2753_p3);

assign x_l_FH_V_56_fu_3091_p2 = (sub_ln813_20_fu_3071_p2 - zext_ln818_3_fu_2995_p1);

assign x_l_FH_V_57_fu_3123_p3 = ((or_ln318_18_fu_3109_p2[0:0] == 1'b1) ? x_l_FH_V_56_fu_3091_p2 : x_l_FH_V_55_fu_2942_p3);

assign x_l_FH_V_58_fu_3277_p2 = (sub_ln813_23_fu_3260_p2 - zext_ln818_4_fu_3190_p1);

assign x_l_FH_V_59_fu_3318_p3 = ((or_ln318_20_fu_3304_p2[0:0] == 1'b1) ? x_l_FH_V_58_fu_3277_p2 : x_l_FH_V_57_reg_3955);

assign x_l_FH_V_60_fu_3465_p2 = (sub_ln813_26_fu_3445_p2 - zext_ln818_5_fu_3369_p1);

assign x_l_FH_V_61_fu_3511_p3 = ((or_ln318_22_fu_3499_p2[0:0] == 1'b1) ? x_l_FH_V_60_fu_3465_p2 : x_l_FH_V_59_fu_3318_p3);

assign x_l_FH_V_fu_1188_p2 = (p_Val2_109_fu_1076_p3 - mul_FH_V_fu_1106_p4);

assign x_l_FL_V_11_fu_3283_p2 = (x_l_FL_V_20_reg_3964 - mul_FL_V_5_fu_3194_p3);

assign x_l_FL_V_13_fu_3471_p2 = (x_l_FL_V_21_fu_3325_p3 - mul_FL_V_6_fu_3373_p3);

assign x_l_FL_V_14_fu_3519_p3 = ((or_ln318_22_fu_3499_p2[0:0] == 1'b1) ? x_l_FL_V_13_fu_3471_p2 : x_l_FL_V_21_fu_3325_p3);

assign x_l_FL_V_15_fu_2211_p3 = ((or_ln318_8_fu_2191_p2[0:0] == 1'b1) ? 17'd65536 : 17'd0);

assign x_l_FL_V_16_fu_2396_p3 = ((or_ln318_10_fu_2374_p2[0:0] == 1'b1) ? x_l_FL_V_fu_2352_p2 : x_l_FL_V_15_fu_2211_p3);

assign x_l_FL_V_17_fu_2573_p3 = ((or_ln318_12_fu_2551_p2[0:0] == 1'b1) ? x_l_FL_V_3_fu_2539_p2 : x_l_FL_V_16_fu_2396_p3);

assign x_l_FL_V_18_fu_2760_p3 = ((or_ln318_14_fu_2739_p2[0:0] == 1'b1) ? x_l_FL_V_5_fu_2718_p2 : x_l_FL_V_17_reg_3929);

assign x_l_FL_V_19_fu_2950_p3 = ((or_ln318_16_fu_2928_p2[0:0] == 1'b1) ? x_l_FL_V_7_fu_2906_p2 : x_l_FL_V_18_fu_2760_p3);

assign x_l_FL_V_20_fu_3131_p3 = ((or_ln318_18_fu_3109_p2[0:0] == 1'b1) ? x_l_FL_V_9_fu_3097_p2 : x_l_FL_V_19_fu_2950_p3);

assign x_l_FL_V_21_fu_3325_p3 = ((or_ln318_20_fu_3304_p2[0:0] == 1'b1) ? x_l_FL_V_11_fu_3283_p2 : x_l_FL_V_20_reg_3964);

assign x_l_FL_V_3_fu_2539_p2 = (x_l_FL_V_16_fu_2396_p3 - mul_FL_V_1_fu_2441_p3);

assign x_l_FL_V_5_fu_2718_p2 = (x_l_FL_V_17_reg_3929 - mul_FL_V_2_fu_2629_p3);

assign x_l_FL_V_7_fu_2906_p2 = (x_l_FL_V_18_fu_2760_p3 - mul_FL_V_3_fu_2808_p3);

assign x_l_FL_V_9_fu_3097_p2 = (x_l_FL_V_19_fu_2950_p3 - mul_FL_V_4_fu_2999_p3);

assign x_l_FL_V_fu_2352_p2 = (x_l_FL_V_15_fu_2211_p3 - mul_FL_V_fu_2254_p3);

assign x_l_I_V_100_fu_2197_p3 = ((or_ln318_8_fu_2191_p2[0:0] == 1'b1) ? x_l_I_V_99_fu_2175_p2 : x_l_I_V_98_reg_3886);

assign x_l_I_V_101_fu_2338_p3 = ((or_ln331_fu_2316_p2[0:0] == 1'b1) ? x_l_I_V_54_fu_2332_p2 : x_l_I_V_100_fu_2197_p3);

assign x_l_I_V_102_fu_2380_p3 = ((or_ln318_10_fu_2374_p2[0:0] == 1'b1) ? x_l_I_V_101_fu_2338_p3 : 20'd0);

assign x_l_I_V_103_fu_2525_p3 = ((or_ln331_1_fu_2503_p2[0:0] == 1'b1) ? x_l_I_V_57_fu_2519_p2 : x_l_I_V_102_fu_2380_p3);

assign x_l_I_V_104_fu_2557_p3 = ((or_ln318_12_fu_2551_p2[0:0] == 1'b1) ? x_l_I_V_103_fu_2525_p3 : 20'd0);

assign x_l_I_V_105_fu_2705_p3 = ((or_ln331_2_fu_2685_p2[0:0] == 1'b1) ? x_l_I_V_60_fu_2700_p2 : x_l_I_V_104_reg_3913);

assign x_l_I_V_106_fu_2745_p3 = ((or_ln318_14_fu_2739_p2[0:0] == 1'b1) ? x_l_I_V_105_fu_2705_p3 : 20'd0);

assign x_l_I_V_107_fu_2892_p3 = ((or_ln331_3_fu_2870_p2[0:0] == 1'b1) ? x_l_I_V_63_fu_2886_p2 : x_l_I_V_106_fu_2745_p3);

assign x_l_I_V_108_fu_2934_p3 = ((or_ln318_16_fu_2928_p2[0:0] == 1'b1) ? x_l_I_V_107_fu_2892_p3 : 20'd0);

assign x_l_I_V_109_fu_3083_p3 = ((or_ln331_4_fu_3061_p2[0:0] == 1'b1) ? x_l_I_V_66_fu_3077_p2 : x_l_I_V_108_fu_2934_p3);

assign x_l_I_V_110_fu_3115_p3 = ((or_ln318_18_fu_3109_p2[0:0] == 1'b1) ? x_l_I_V_109_fu_3083_p3 : 20'd0);

assign x_l_I_V_111_fu_3270_p3 = ((or_ln331_5_fu_3250_p2[0:0] == 1'b1) ? x_l_I_V_69_fu_3265_p2 : x_l_I_V_110_reg_3948);

assign x_l_I_V_112_fu_3310_p3 = ((or_ln318_20_fu_3304_p2[0:0] == 1'b1) ? x_l_I_V_111_fu_3270_p3 : 20'd0);

assign x_l_I_V_113_fu_3457_p3 = ((or_ln331_6_fu_3435_p2[0:0] == 1'b1) ? x_l_I_V_72_fu_3451_p2 : x_l_I_V_112_fu_3310_p3);

assign x_l_I_V_19_fu_1043_p3 = ((icmp_ln1650_reg_3728[0:0] == 1'b1) ? x_l_I_V_fu_1037_p2 : x_l_I_V_82_fu_992_p3);

assign x_l_I_V_22_fu_1174_p2 = ($signed(x_l_I_V_84_fu_1068_p3) + $signed(20'd1048575));

assign x_l_I_V_23_fu_1180_p3 = ((icmp_ln1650_1_fu_1168_p2[0:0] == 1'b1) ? x_l_I_V_22_fu_1174_p2 : x_l_I_V_84_fu_1068_p3);

assign x_l_I_V_26_fu_1394_p2 = ($signed(x_l_I_V_86_fu_1319_p3) + $signed(20'd1048575));

assign x_l_I_V_27_fu_1400_p3 = ((icmp_ln1650_2_fu_1389_p2[0:0] == 1'b1) ? x_l_I_V_26_fu_1394_p2 : x_l_I_V_86_fu_1319_p3);

assign x_l_I_V_30_fu_1524_p2 = ($signed(x_l_I_V_88_fu_1435_p3) + $signed(20'd1048575));

assign x_l_I_V_31_fu_1530_p3 = ((icmp_ln1650_3_fu_1518_p2[0:0] == 1'b1) ? x_l_I_V_30_fu_1524_p2 : x_l_I_V_88_fu_1435_p3);

assign x_l_I_V_34_fu_1656_p2 = ($signed(x_l_I_V_90_fu_1566_p3) + $signed(20'd1048575));

assign x_l_I_V_35_fu_1662_p3 = ((icmp_ln1650_4_fu_1650_p2[0:0] == 1'b1) ? x_l_I_V_34_fu_1656_p2 : x_l_I_V_90_fu_1566_p3);

assign x_l_I_V_38_fu_1781_p2 = ($signed(x_l_I_V_92_reg_3858) + $signed(20'd1048575));

assign x_l_I_V_39_fu_1786_p3 = ((icmp_ln1650_5_fu_1776_p2[0:0] == 1'b1) ? x_l_I_V_38_fu_1781_p2 : x_l_I_V_92_reg_3858);

assign x_l_I_V_42_fu_1908_p2 = ($signed(x_l_I_V_94_fu_1820_p3) + $signed(20'd1048575));

assign x_l_I_V_43_fu_1914_p3 = ((icmp_ln1650_6_fu_1902_p2[0:0] == 1'b1) ? x_l_I_V_42_fu_1908_p2 : x_l_I_V_94_fu_1820_p3);

assign x_l_I_V_46_fu_2040_p2 = ($signed(x_l_I_V_96_fu_1950_p3) + $signed(20'd1048575));

assign x_l_I_V_47_fu_2046_p3 = ((icmp_ln1650_7_fu_2034_p2[0:0] == 1'b1) ? x_l_I_V_46_fu_2040_p2 : x_l_I_V_96_fu_1950_p3);

assign x_l_I_V_50_fu_2157_p2 = ($signed(x_l_I_V_98_reg_3886) + $signed(20'd1048575));

assign x_l_I_V_54_fu_2332_p2 = ($signed(x_l_I_V_100_fu_2197_p3) + $signed(20'd1048575));

assign x_l_I_V_57_fu_2519_p2 = ($signed(x_l_I_V_102_fu_2380_p3) + $signed(20'd1048575));

assign x_l_I_V_60_fu_2700_p2 = ($signed(x_l_I_V_104_reg_3913) + $signed(20'd1048575));

assign x_l_I_V_63_fu_2886_p2 = ($signed(x_l_I_V_106_fu_2745_p3) + $signed(20'd1048575));

assign x_l_I_V_66_fu_3077_p2 = ($signed(x_l_I_V_108_fu_2934_p3) + $signed(20'd1048575));

assign x_l_I_V_69_fu_3265_p2 = ($signed(x_l_I_V_110_reg_3948) + $signed(20'd1048575));

assign x_l_I_V_72_fu_3451_p2 = ($signed(x_l_I_V_112_fu_3310_p3) + $signed(20'd1048575));

assign x_l_I_V_74_fu_320_p3 = ((tmp_fu_300_p3[0:0] == 1'b1) ? p_Result_47_fu_308_p5 : zext_ln818_fu_292_p1);

assign x_l_I_V_75_fu_402_p3 = ((icmp_ln443_fu_368_p2[0:0] == 1'b1) ? x_l_I_V_74_fu_320_p3 : p_Result_48_fu_380_p5);

assign x_l_I_V_76_fu_484_p3 = ((icmp_ln443_1_fu_450_p2[0:0] == 1'b1) ? x_l_I_V_75_fu_402_p3 : p_Result_50_fu_462_p5);

assign x_l_I_V_77_fu_566_p3 = ((icmp_ln443_2_fu_532_p2[0:0] == 1'b1) ? x_l_I_V_76_fu_484_p3 : p_Result_52_fu_544_p5);

assign x_l_I_V_78_fu_648_p3 = ((icmp_ln443_3_fu_614_p2[0:0] == 1'b1) ? x_l_I_V_77_fu_566_p3 : p_Result_54_fu_626_p5);

assign x_l_I_V_79_fu_730_p3 = ((icmp_ln443_4_fu_696_p2[0:0] == 1'b1) ? x_l_I_V_78_fu_648_p3 : p_Result_56_fu_708_p5);

assign x_l_I_V_80_fu_848_p3 = ((icmp_ln443_5_reg_3712[0:0] == 1'b1) ? x_l_I_V_79_reg_3700 : p_Result_58_fu_829_p5);

assign x_l_I_V_81_fu_926_p3 = ((icmp_ln443_6_fu_892_p2[0:0] == 1'b1) ? x_l_I_V_80_fu_848_p3 : p_Result_60_fu_904_p5);

assign x_l_I_V_82_fu_992_p3 = ((icmp_ln443_7_fu_958_p2[0:0] == 1'b1) ? x_l_I_V_81_fu_926_p3 : p_Result_62_fu_970_p5);

assign x_l_I_V_83_fu_1056_p2 = (x_l_I_V_19_fu_1043_p3 - zext_ln1649_fu_1016_p1);

assign x_l_I_V_84_fu_1068_p3 = ((or_ln318_fu_1062_p2[0:0] == 1'b1) ? x_l_I_V_83_fu_1056_p2 : x_l_I_V_82_fu_992_p3);

assign x_l_I_V_85_fu_1194_p2 = (x_l_I_V_23_fu_1180_p3 - zext_ln1649_1_fu_1134_p1);

assign x_l_I_V_86_fu_1319_p3 = ((or_ln318_1_reg_3763[0:0] == 1'b1) ? x_l_I_V_85_reg_3758 : x_l_I_V_84_reg_3747);

assign x_l_I_V_87_fu_1413_p2 = (x_l_I_V_27_fu_1400_p3 - zext_ln1649_2_fu_1356_p1);

assign x_l_I_V_88_fu_1435_p3 = ((or_ln318_2_fu_1429_p2[0:0] == 1'b1) ? x_l_I_V_87_fu_1413_p2 : x_l_I_V_86_fu_1319_p3);

assign x_l_I_V_89_fu_1544_p2 = (x_l_I_V_31_fu_1530_p3 - zext_ln1649_3_fu_1484_p1);

assign x_l_I_V_90_fu_1566_p3 = ((or_ln318_3_fu_1560_p2[0:0] == 1'b1) ? x_l_I_V_89_fu_1544_p2 : x_l_I_V_88_fu_1435_p3);

assign x_l_I_V_91_fu_1676_p2 = (x_l_I_V_35_fu_1662_p3 - zext_ln1649_4_fu_1616_p1);

assign x_l_I_V_92_fu_1688_p3 = ((or_ln318_4_fu_1682_p2[0:0] == 1'b1) ? x_l_I_V_91_fu_1676_p2 : x_l_I_V_90_fu_1566_p3);

assign x_l_I_V_93_fu_1798_p2 = (x_l_I_V_39_fu_1786_p3 - zext_ln1649_5_fu_1745_p1);

assign x_l_I_V_94_fu_1820_p3 = ((or_ln318_5_fu_1814_p2[0:0] == 1'b1) ? x_l_I_V_93_fu_1798_p2 : x_l_I_V_92_reg_3858);

assign x_l_I_V_95_fu_1928_p2 = (x_l_I_V_43_fu_1914_p3 - zext_ln1649_6_fu_1868_p1);

assign x_l_I_V_96_fu_1950_p3 = ((or_ln318_6_fu_1944_p2[0:0] == 1'b1) ? x_l_I_V_95_fu_1928_p2 : x_l_I_V_94_fu_1820_p3);

assign x_l_I_V_97_fu_2060_p2 = (x_l_I_V_47_fu_2046_p3 - zext_ln1649_7_fu_2000_p1);

assign x_l_I_V_98_fu_2072_p3 = ((or_ln318_7_fu_2066_p2[0:0] == 1'b1) ? x_l_I_V_97_fu_2060_p2 : x_l_I_V_96_fu_1950_p3);

assign x_l_I_V_99_fu_2175_p2 = (p_Val2_110_fu_2162_p3 - zext_ln1649_8_fu_2127_p1);

assign x_l_I_V_fu_1037_p2 = ($signed(x_l_I_V_82_fu_992_p3) + $signed(20'd1048575));

assign xor_ln1651_1_fu_2473_p2 = (icmp_ln1651_1_fu_2467_p2 ^ 1'd1);

assign xor_ln1651_2_fu_2657_p2 = (icmp_ln1651_2_fu_2652_p2 ^ 1'd1);

assign xor_ln1651_3_fu_2840_p2 = (icmp_ln1651_3_fu_2834_p2 ^ 1'd1);

assign xor_ln1651_4_fu_3031_p2 = (icmp_ln1651_4_fu_3025_p2 ^ 1'd1);

assign xor_ln1651_5_fu_3222_p2 = (icmp_ln1651_5_fu_3217_p2 ^ 1'd1);

assign xor_ln1651_6_fu_3405_p2 = (icmp_ln1651_6_fu_3399_p2 ^ 1'd1);

assign xor_ln1651_7_fu_3586_p2 = (icmp_ln1651_7_fu_3580_p2 ^ 1'd1);

assign xor_ln1651_fu_2286_p2 = (icmp_ln1651_fu_2280_p2 ^ 1'd1);

assign xor_ln318_1_fu_1377_p2 = (icmp_ln318_2_fu_1372_p2 ^ 1'd1);

assign xor_ln318_2_fu_1506_p2 = (icmp_ln318_3_fu_1500_p2 ^ 1'd1);

assign xor_ln318_3_fu_1638_p2 = (icmp_ln318_4_fu_1632_p2 ^ 1'd1);

assign xor_ln318_4_fu_1764_p2 = (icmp_ln318_5_fu_1759_p2 ^ 1'd1);

assign xor_ln318_5_fu_1890_p2 = (icmp_ln318_6_fu_1884_p2 ^ 1'd1);

assign xor_ln318_6_fu_2022_p2 = (icmp_ln318_7_fu_2016_p2 ^ 1'd1);

assign xor_ln318_fu_1156_p2 = (icmp_ln318_1_fu_1150_p2 ^ 1'd1);

assign zext_ln1649_1_fu_1134_p1 = trunc_ln1649_1_fu_1126_p3;

assign zext_ln1649_2_fu_1356_p1 = trunc_ln1649_2_fu_1349_p3;

assign zext_ln1649_3_fu_1484_p1 = trunc_ln1649_3_fu_1477_p3;

assign zext_ln1649_4_fu_1616_p1 = trunc_ln1649_4_fu_1609_p3;

assign zext_ln1649_5_fu_1745_p1 = trunc_ln1649_5_fu_1738_p3;

assign zext_ln1649_6_fu_1868_p1 = trunc_ln1649_6_fu_1861_p3;

assign zext_ln1649_7_fu_2000_p1 = trunc_ln1649_7_fu_1993_p3;

assign zext_ln1649_8_fu_2127_p1 = trunc_ln1649_8_fu_2120_p3;

assign zext_ln1649_fu_1016_p1 = trunc_ln2_fu_1008_p3;

assign zext_ln443_1_fu_446_p1 = tmp_6_fu_428_p3;

assign zext_ln443_2_fu_528_p1 = tmp_7_fu_510_p3;

assign zext_ln443_3_fu_610_p1 = tmp_10_fu_592_p3;

assign zext_ln443_4_fu_692_p1 = tmp_13_fu_674_p3;

assign zext_ln443_5_fu_774_p1 = tmp_16_fu_756_p3;

assign zext_ln443_6_fu_888_p1 = tmp_19_fu_870_p3;

assign zext_ln443_7_fu_954_p1 = tmp_21_fu_942_p3;

assign zext_ln443_fu_364_p1 = tmp_1_fu_346_p3;

assign zext_ln813_1_fu_2509_p1 = signbit_1_fu_2485_p2;

assign zext_ln813_2_fu_2691_p1 = signbit_2_fu_2669_p2;

assign zext_ln813_3_fu_2876_p1 = signbit_3_fu_2852_p2;

assign zext_ln813_4_fu_3067_p1 = signbit_4_fu_3043_p2;

assign zext_ln813_5_fu_3256_p1 = signbit_5_fu_3234_p2;

assign zext_ln813_6_fu_3441_p1 = signbit_6_fu_3417_p2;

assign zext_ln813_7_fu_3628_p1 = res_FH_V_31_fu_3620_p3;

assign zext_ln813_fu_2322_p1 = signbit_fu_2298_p2;

assign zext_ln818_1_fu_2625_p1 = mul_FH_V_s_fu_2616_p4;

assign zext_ln818_2_fu_2804_p1 = mul_FH_V_10_fu_2795_p4;

assign zext_ln818_3_fu_2995_p1 = mul_FH_V_11_fu_2986_p4;

assign zext_ln818_4_fu_3190_p1 = mul_FH_V_12_fu_3181_p4;

assign zext_ln818_5_fu_3369_p1 = mul_FH_V_13_fu_3360_p4;

assign zext_ln818_6_fu_3564_p1 = mul_FH_V_14_fu_3555_p4;

assign zext_ln818_fu_292_p1 = trunc_ln_fu_282_p4;

always @ (posedge ap_clk) begin
    res_FH_V_33_reg_3752[15:0] <= 16'b0000000000000000;
    x_l_FH_V_33_reg_3769[0] <= 1'b0;
    x_l_FH_V_39_reg_3867[0] <= 1'b0;
    x_l_FH_V_45_reg_3895[0] <= 1'b0;
    x_l_FL_V_17_reg_3929[11:0] <= 12'b000000000000;
    x_l_FL_V_20_reg_3964[5:0] <= 6'b000000;
end

endmodule //CNN_sqrt_fixed_33_17_s
